### ISSUE TITLE
Poor performance in cmake builds

### ISSUE THREAD

**Issue by zstephens** [coelckers/prboom-plus#100]
Greetings,

I noticed pretty big performance hits in prb2517, especially in larger maps, which I've traced back to the switchover to cmake.

Here's an example, using prb2517 from this commit: bfcc1f7f60960728ff11043e7105e0f53d0a220b (i.e. the most recent one I found that still had the old project files).

compiled with ./bootstrap --> ./configure --> make:
<img width="360" alt="Screen Shot 2020-06-25 at 11 13 15 AM" src="https://user-images.githubusercontent.com/8508373/85768501-b68e5e80-b6de-11ea-8a87-ce4b3bba3cef.png">

compiled with cmake:
<img width="360" alt="Screen Shot 2020-06-25 at 11 12 18 AM" src="https://user-images.githubusercontent.com/8508373/85768476-b0987d80-b6de-11ea-9f18-679ed2e56fb9.png">

The difference is even more pronounced in gl graphics:

compiled with ./bootstrap --> ./configure --> make:
<img width="360" alt="Screen Shot 2020-06-25 at 12 31 47 PM" src="https://user-images.githubusercontent.com/8508373/85770146-3a951600-b6e0-11ea-8372-89bad08340a5.png">

compiled with cmake:
<img width="360" alt="Screen Shot 2020-06-25 at 12 32 57 PM" src="https://user-images.githubusercontent.com/8508373/85770223-4c76b900-b6e0-11ea-8c8a-994c5343456a.png">

Could be something as simple as compiler flags?

This is on mac, by the way, os x 10.14.6. I'm happy to provide more system details if it would help.

**Comment by alexey-lysiuk** [comment]
Did you built Release configuration? CMake default is Debug.

**Comment by zstephens** [comment]
Ok yeah that was it, didn't realize it wasn't Release by default. Thanks!
