### ISSUE TITLE
Portmidi interpereting pitch bends oddly after listening to certain midis

### ISSUE THREAD

**Issue by Alper002** [coelckers/prboom-plus#101]
Steps to recreate: (using [25 years on Earth](https://www.doomworld.com/forum/topic/108938-doom-ii-25-years-on-earth-32-map-limit-removing-old-school-megawad-released/) as an example wad)
1.Use portmidi as midi player
2.Load up the wad normally and use idclev to get to map29
3.Start the game again, this time with -warp 29
4.Compare how the pitch bends in the music sounds

Alternatively, in [Three is a crowd](https://www.doomworld.com/forum/topic/115177-three-is-a-crowd-vanilla-megawad-with-three-protagonists-finally-released/):
1.Use portmidi as midi player
2.Start the game with the wad loaded
3.use idmus10/idclev10
4.use idmus03/idclev03
5.use idmus10/idclev10
6.Compare how MAP10's pitch bends sound before and after playing MAP03's midi

I am assuming the reason there's a discrepancy between starting normally and idcleving compared to using -warp in 25yoe is that the title screen midi has the property that 3iac's MAP03 midi has.

**Comment by Alper002** [comment]
After some searching, I think I have a good guess for why this issue occurs. Pitch bend range changes caused by Registered Parameter Numbers (Which [this page](https://www.recordingblogs.com/wiki/midi-registered-parameter-number-rpn) seems to describe pretty well) aren't reset when a new midi is played. This causes all midis played afterwards to use the same pitch bend range until a new one is used by a midi.

**Comment by fabiangreffrath** [comment]
```
-- a/prboom2/src/MUSIC/portmidiplayer.c
+++ b/prboom2/src/MUSIC/portmidiplayer.c
@@ -387,6 +387,7 @@ static void pm_stop (void)
   int i;
   unsigned long when = Pt_Time ();
   pm_playing = 0;
+  const short norm_pitch = 0x2000;
   
 
   // songs can be stopped at any time, so reset everything
@@ -394,6 +395,7 @@ static void pm_stop (void)
   {
     writeevent (when, MIDI_EVENT_CONTROLLER, i, 123, 0); // all notes off
     writeevent (when, MIDI_EVENT_CONTROLLER, i, 121, 0); // reset all parameters
+    writeevent (when, MIDI_EVENT_PITCH_BEND, i, norm_pitch & 0x7f, (norm_pitch >> 7) & 0x7f); // reset pitch bending
   }
   // abort any partial sysex
   sysexbufflen = 0;
```

**Comment by fabiangreffrath** [comment]
This is a "blind" patch. Is anyone able to test this with the instructions given in the OP? I am currently unable to get it checked on Linux, because my portmidi falls back to using ALSA whereas I have pulseaudio running...

**Comment by fabiangreffrath** [comment]
That was too easy, this is the right patch (it's still missing comments, though):
```
--- a/prboom2/src/MUSIC/portmidiplayer.c
+++ b/prboom2/src/MUSIC/portmidiplayer.c
@@ -394,6 +394,13 @@ static void pm_stop (void)
   {
     writeevent (when, MIDI_EVENT_CONTROLLER, i, 123, 0); // all notes off
     writeevent (when, MIDI_EVENT_CONTROLLER, i, 121, 0); // reset all parameters
+    writeevent (when, MIDI_EVENT_CONTROLLER, i, 0x65, 0x00);
+    writeevent (when, MIDI_EVENT_CONTROLLER, i, 0x64, 0x00);
+    writeevent (when, MIDI_EVENT_CONTROLLER, i, 0x06, 0x02);
+    writeevent (when, MIDI_EVENT_CONTROLLER, i, 0x26, 0x00);
+    writeevent (when, MIDI_EVENT_CONTROLLER, i, 0x64, 0x7f);
+    writeevent (when, MIDI_EVENT_CONTROLLER, i, 0x65, 0x7f);
+
   }
   // abort any partial sysex
   sysexbufflen = 0;

```
