### ISSUE TITLE
[Bug] Key-bindings unusable after mouse-wheel-up/down

### ISSUE THREAD

**Issue by Coincident** [coelckers/prboom-plus#108]
I'm seeing some bugs when using the mouse-wheel-up/down for binds.
First I tried binding mouse-wheel-down to "USE". But after scrolling once with my finger (about 4-5 scroll-instances), the game no longer let's me "USE" anything until I die or restart the level.
Then I tried binding mouse-wheel-down to swap to the Chaingun. But after scrolling a few times, I can no longer swap to the Rocket Launcher or BFG (bound to "Q" and "F" on my keyboard, respectively), and if I swap to any other weapon (for example the shotgun), the game immediately swaps again to the Chaingun, for the rest of the level.
 
My **_guess_** is, because the 4-5 scroll-instances happen extremely fast, the game thinks that the scroll-down "key" is permanently "pressed-down".
I'm used to playing with 2.5.1.4, and this was not a problem in that version.

PS: I'm running the **_prboom-plus-2.5.1.7um-win32_** release from 16 June 2019 on Windows 7.

PS2: I tested some more, and the problem also happens in the 2.5.1.5 version, but not in 2.5.1.4

**Comment by fabiangreffrath** [comment]
This is because in SDL-1 (PrBoom+ 2.5.1.4) moving the mouse wheel is handled as a button press (and immediate release). In SDL-2 (PrBoom+ 2.5.1.5 and onward) moving the mouse wheel is handled differently by SDL, but for backwards compatibility it is still mapped to a mouse button press in most source ports.

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/e502f3fe71eb3e760ffbfae92ccdad2df1e8defb

Seems like it is a typo 😉

**Comment by fabiangreffrath** [comment]
That was last-minute!
https://github.com/coelckers/prboom-plus/commit/93a51060c8d4a429d82e13b2dfff65d1d62ce11a
