### ISSUE TITLE
GLB+ cannot sort sprites and walls simultaneously - causes issue w/boom translucent things

### ISSUE THREAD

**Issue by physixcat** [coelckers/prboom-plus#112]
I have noticed that using the OpenGL renderer results in Boom's translucent things to render as solid. I investigated the reason for this and found an old thread from 2012 that @fabiangreffrath made: https://sourceforge.net/p/prboom-plus/bugs/218/

According to Blondie: 

> _"Boom's translucent things (imp fireballs, plasma, teleporters, etc.) are **permanently disabled** at all complevels in OpenGL mode because **GLBoom cannot sort sprites and walls at the same time**."_

 Fortunately, Blondie provides a DEH patch that can force translucency to be enabled/disabled, but I suspect this is just supposed to be a bandaid solution.

Upon being asked about how to solve the issue, Blondie replied 

> _"You'll have to ask Andrey for the specifics. I reported the "smooth sprite edges" bug years ago to confirm if it was another manifestation of the sorting issue, and indeed it was. I also requested a config variable years ago to **toggle GL sprite translucency**, but it was never implemented. Doesn't matter, though, because those dehacked patches work just as well."_ 

I thought I'd bring the topic up again, in hopes that someone has an idea of how to solve the root cause

**Comment by JadingTsunami** [comment]
Does anyone have a picture of the effect (expected vs. actual) here? I am finding it hard to visualize what this means.

I don't think there should be any issue rendering projectiles as translucent, but I haven't looked into this issue yet.
