### ISSUE TITLE
Extend interbackdrop in UMAPINFO implementation to allow graphics

### ISSUE THREAD

**Issue by De-Seppe** [coelckers/prboom-plus#121]
The current specification for interbackdrop only allows for flats which are tiled.
Ancient Aliens and Valiant both provide graphic that should be used as a backdrop with the intermission text.
Please extend the implementation to also allow graphic files that are displayed fullscreen (instead of tiled)

Following link provides umapinfo files for both Ancient Aliens and Valiant
https://www.bountysource.com/issues/92317279-feature-request-umapinfo-files-for-popular-wads

**Comment by De-Seppe** [comment]
Thanks for fixing this.
I'm looking forward to the next build that includes it.

**Comment by tpoppins** [comment]
[Latest build](https://www.doomworld.com/forum/topic/106866-prboomumapinfo-v-2517/?do=findComment&comment=2270363) is up on Doomworld forums.
