### ISSUE TITLE
Any example of hi-res texture & sprite pack

### ISSUE THREAD

**Issue by Shchvova** [coelckers/prboom-plus#122]
Hey. So I was trying to get hi-res textures working and didn't find any "properly" packaged pack. If I edit confing and point it to "textures" directory, I get hi-res textures, which look weird with low-res sprites. Any place I can download sprites and textues (also patches and flats) to work properly?

**Comment by fabiangreffrath** [comment]
I don't think this is the right place to ask such questions. Here is where development takes place, this is not a community forum (but Doomworld is *hint*).

**Comment by Shchvova** [comment]
Thanks for your reply. I didn't really asked to recommend a texture pack or anything like that. I just wanted to get a texture pack which would fit the structure PrBoom+ requires. Any would do, even extracted original textures.
