### ISSUE TITLE
please add SVN log for historical reasons

### ISSUE THREAD

**Issue by fabiangreffrath** [coelckers/prboom-plus#13]
I think it would be fair if this had the output of `svn log` added as e.g. a `ChangeLog` file.

**Comment by coelckers** [comment]
I'll be honest here: I have no idea which commits I added. SVN is a major pain in the ass to work with when trying to merge changes into a Git repo, so what I did was to update the repo and then use a file compare tool to merge all changes manually.

**Comment by fabiangreffrath** [comment]
What I mean is, the history of this fork is preserved by the commit history of the GIT repository. But the history of all the development before that, i.e. in SVN, would be lost. I have attached the output of `svn log` from the original repository to this message, in case you want to add it to the sources.

[prboom-svn-log.txt.gz](https://github.com/coelckers/prboom-plus/files/3292871/prboom-svn-log.txt.gz)

**Comment by coelckers** [comment]
The changelog history until the fork date is completely there, it's only the things coming afterward I wasn't able to properly add to the commit because of not being able to do a real merge.

**Comment by fabiangreffrath** [comment]
Ah, indeed! I have only seen the later "update to latest SVN" kind of commits.
