### ISSUE TITLE
Way to automatically "pistol start" every level (feature)

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#132]
**Expected:**
Convenient way to "pistol start" every level.
In this "mode" the player starts each and every level with:
* 50 bullets and no other ammo
* a pistol, a fist and no other weapon
* 100% health and 0% armor

Player starts each and every level as if they just died and just respawned - automatically.

**Actual:**
Player has to remember to type IDCLEV... or to press Home when each new level starts after finishing the previous level.

**Possible solution:**
`-pistolstart` command line switch [like in crispy-doom](https://github.com/fabiangreffrath/crispy-doom/pull/659)

**Extra:**
It's not a huge deal I suppose as the IDCLEV... way is the way many/most of us always done "pistol start" all along I'd imagine but it would be nice if this could be automated/forced. I sometimes forget to press Home on a new level and then realise it later that I should restart the level as it wasn't a pistol start. In crispy-doom the command line switch works really conveniently.

**Comment by runlow** [comment]
quick and dirty hack that forces pistol start on every level
```diff
--- a/prboom2/src/g_game.c
+++ b/prboom2/src/g_game.c
@@ -819 +819 @@ static void G_DoLoadLevel (void)
-      if (playeringame[i] && players[i].playerstate == PST_DEAD)
+      //if (playeringame[i] && players[i].playerstate == PST_DEAD)
```

**Comment by fabiangreffrath** [comment]
How about a pull request? :wink:

**Comment by runlow** [comment]
Yeah, good idea. Will see what I can do in off time although if someone wants to write it in meanwhile - of course feel free.

**Comment by TheLonerD** [comment]
@bradharding, maybe we can adapt your pistol start code from your source port? (I'm sorry didn't use your port in a while).

**Comment by runlow** [comment]
Works as expected. Thanks for implementing this!
