### ISSUE TITLE
Nonstandard handling of spaces in file path

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#133]
_This command works as expected:_

`crispy-doom -iwad DOOM.WAD -file "/tmp/zip/Shotgun Symphony/sgnsym.wad"`

(it loads with the pwad https://www.doomworld.com/idgames/levels/doom/Ports/s-u/sgnsym)

_This command does not work as expected:_

`glboom-plus -iwad DOOM.WAD -file "/tmp/zip/Shotgun Symphony/sgnsym.wad"`

(expected PWAD splash screen as above but instead got the Ultimate Doom screen as if there was no PWAD in the command)

When I rename the directory so that it doesn't contain any spaces in its name then the PWAD works fine with glboom-plus.

(The person who uploaded the zip file to the archive put a space in the directory name before compressing it, and I mount zip files with `fuse-zip`, then search for relevant files in them)

One could argue that having spaces in directory names is ugly which it is, but I don't see any good reason why this command should not work as expected.

I believe that the user should not have to rename directories to accomodate this behaviour of the glboom-plus executable. Please correct me if I'm wrong.

**Comment by JadingTsunami** [comment]
What is your OS and shell?

I'm not seeing the same behavior on my system.

**Comment by runlow** [comment]
/bin/bash on Linux.

**Comment by JadingTsunami** [comment]
Could you try running with the command:

`glboom-plus -iwad DOOM.WAD -file "/tmp/zip/Shotgun Symphony/sgnsym.wad" -cout DICWEFA`

And paste the console output here? That will give a better idea of where PrBoom is checking for the file.

**Comment by runlow** [comment]
Here's the output http://sprunge.us/YiHeKw
Not seeing anything relevant though.

**Comment by runlow** [comment]
Wait, I may have messed up the report.

I said that the command starts with `glboom-plus` suggesting it's in $PATH but I actually put a bash script in $PATH
```
#!/bin/bash
cd ~/3/git/prboom-plus/build && ./glboom-plus $@ &>> /tmp/prboom-plus
rm ~/.prboom-plus/tranmap.dat
```
because if I don't do `cd ~/3/git/prboom-plus/build` each time it says
`PrBoom-Plus.wad not found. Can't continue.`
A workaround I found for that is to do
`export DOOMWADDIR=~/3/git/prboom-plus/build`
...but then I can't use DOOMWADDIR for what it's intended for, so instead I just `cd` into that directory

either way I just realised that when I do:
```
cd ~/3/git/prboom-plus/build
./glboom-plus -iwad DOOM.WAD -file "/tmp/zip/Shotgun Symphony/sgnsym.wad"
or
./glboom-plus -iwad DOOM.WAD -file /tmp/zip/Shotgun\ Symphony/sgnsym.wad
```
Then it works fine. Means I messed up the script I wrote.

Closing issue and apologies.

**Comment by fabiangreffrath** [comment]
Does it help if you put the `$@` in quotation marks, i.e. `"$@"`?

**Comment by runlow** [comment]
That's exactly it, thank you.
