### ISSUE TITLE
Config file space padding inconsistent

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#134]
It might not matter much to users who don't edit the config file by hand. Those who do might appreciate a more consistent formatting.

Possible solutions (regardless which - same rule should be apply to every entry):

- change the format entirely to `variable value` on each line (only one space separating the two)
- increase the number of spaces each entry is padded with so that the longest variables fit

Here's a screenshot of `crispy-doom.cfg` for comparison (right)

![2020-11-16-005239_1920x1080_scrot](https://user-images.githubusercontent.com/2176657/99202128-1082e400-27a6-11eb-932b-a3edd87d353b.png)

**Comment by fabiangreffrath** [comment]
Indeed, in PrBoom+'s config file the /key/ strings are padded up to 25 characters with spaces, then follows another space and then the /value/, which is either a left-aligned string, a left-aligned hex value or a decimal number right-aligned in a 5 character wide field padded with spaces to the left. He?

https://github.com/coelckers/prboom-plus/blob/676d818c5bbc1d45f0a191def0d7629ed73a84cb/prboom2/src/m_misc.c#L1384

**Comment by runlow** [comment]
I think I meant that all the values should align in a column regardless of type.

So you're saying there already is a consistent rule and I didn't notice it. OK, checking. Maybe I should have worded it better.

**Comment by runlow** [comment]
What I meant that for example the value for `hudadd_crosshair_target_color` on that screenshot isn't in the same column as the value above it and it's the same type.

I generated the config file many months ago so maybe it formats it differently now. Will check that too.

**Comment by fabiangreffrath** [comment]
You realized that I just fixed this according to the suggestions you gave earlier? 😉

**Comment by runlow** [comment]
Oh right! Huge thanks and sorry for the misunderstanding! Completely overlooked it.
