### ISSUE TITLE
[Feature Suggestion] Resurrection cheat

### ISSUE THREAD

**Issue by jackrjli** [coelckers/prboom-plus#135]
Basically, the ability to revive oneself in-place after death. Useful for casual play or exploring/learning a map without having to keep saves ready. In Crispy Doom, this is made part of the god mode cheat, which I think is nice.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/e6bc2b96f61294bdc8012645539392c9271dee7c
