### ISSUE TITLE
[Suggestion] Support for widescreen graphics

### ISSUE THREAD

**Issue by UnluckySpade7** [coelckers/prboom-plus#142]
Since the Unity port, Crispy Doom and GZDoom have Widescreen graphics support I would like to see Prboom+ get the same treatment, maybe something could be done with [Widepix](https://forum.zdoom.org/viewtopic.php?f=46&t=67843) as well but repackaged into .wad formats.

**Comment by fabiangreffrath** [comment]
Calling out for @SmileTheory

**Comment by fraansg** [comment]
The use of Widepix can cause a disarrangement in the cases of files that incorporate graphics that replace the dynamic intermission screens (e.g. this happens when loading HD texture patches for *zdoom, desynchronizing the animations presented by the Ultimate Doom intermission screens)

**Comment by fabiangreffrath** [comment]
With this simple change it draw the patches at least centered, but I somehow cannot get them drawn outside their horizontal boundaries:
```patch
--- a/prboom2/src/v_video.c
+++ b/prboom2/src/v_video.c
@@ -425,6 +425,9 @@ static void V_DrawMemPatch(int x, int y, int scrn, const rpatch_t *patch,
   if (!trans)
     flags &= ~VPT_TRANS;
 
+  if (patch->width > 320 && x == 0)
+    x = (320 - patch->width) / 2;
+
   if (V_GetMode() == VID_MODE8 && !(flags & VPT_STRETCH_MASK)) {
     int             col;
     byte           *desttop = screens[scrn].data+y*screens[scrn].byte_pitch+x*V_GetPixelDepth();
```
