### ISSUE TITLE
[Suggestion] new keyword in UMAPINFO to allow for monsters telefragging outside of MAP30

### ISSUE THREAD

**Issue by Alper002** [coelckers/prboom-plus#150]
As far as I am aware, monsters currently cannot telefrag other things outside of MAP30 at all. 
This means that if you want to make use of the icon of sin monster spawners in an elegant way, you can:
**A:** Only have one map making use of them, and
**B:** have to specifically make the maps go out of order to make use of it, unless MAP30 is the 30th level.

Not to mention, if you _don't_ want monsters telefragging on the 30th level you have to make the level progression skip MAP30.

It's the only major thing I think UMAPINFO is really missing, since the point of MAPINFO is allowing you to change what was hardcoded about the mapslots.

I'd suggest the key be called "AllowMonsterTelefrags", like in zdoom's mapinfo.

**Comment by kraflab** [comment]
This isn't really a question for prboom+, right? That's a question for the UMAPINFO standard, which is a conversation to be had elsewhere I guess.

**Comment by Alper002** [comment]
I suppose you're right.
