### ISSUE TITLE
[Feature] Support for MBF sky transfers in vanilla/limit-removing complevels (2, 3 and 4)

### ISSUE THREAD

**Issue by srmoco42** [coelckers/prboom-plus#152]
Hi,

From what I can gather this was originally implemented on MBF, yet it's commonly mistaken for a Boom feature due to its presence in the equivalent PrBoom+ complevels. In recent years community wads aimed for vanilla/limit-removing source-ports have started to make use of this feature, for example [Remnant](https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/remnant) and a bonus area in E3M7 of [No End In Sight](https://www.doomworld.com/idgames/levels/doom/Ports/megawads/neis) (where it's supposed to show the original E1 sky). When playing these two examples under the recommended complevel (cl2 for the former, cl3 for the latter) the sky doesn't change as intended, whereas the effect works fine in cl9 and above.

Seeing as Crispy Doom already supports this feature and since it's a purely aesthetic effect (hence not breaking demo compatibility), hopefully it's possible to make it work in cl2-4.

Thanks and keep up the great work!

**Comment by fabiangreffrath** [comment]
I am not opposed to it, as sky transfers are purely cosmetical. What do others think?

**Comment by JadingTsunami** [comment]
A bit esoteric perhaps, but ultimately should be harmless. I would say if some WADs use it, why not?

A new optional editing trick in Vanilla mode based on a longstanding convention from MBF. Sounds like a good feature candidate to me.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/pull/155

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/2119b6f006a5dbb561ee950c5bf3177e8023f401
