### ISSUE TITLE
let's get rid of the "Screen Multiple Factor" feature

### ISSUE THREAD

**Issue by fabiangreffrath** [coelckers/prboom-plus#159]
Since the switch to SDL2 we have seamless scaling of the game window. This means, we don't need to explicitly multiply pixels in order to scale a low resolution up to the desired window size anymore. This works for all rendering modes, both windowed and fullscreen - except for OpenGL rendering, but this doesn't support the "screen multiple factor" feature either.

Any objections or ideas? Is there anyone who still has this option set to anything but `1` in the current version?

**Comment by MoskovchenkoD** [comment]
Nope. I have never touched this feature. However, I was curious about what it does =)

**Comment by solbjorn** [comment]
Nope, and IFAIR this scaler is pretty unprecise and messes up the output.

I would like to see another feature instead -- an ability to set the ingame resolution separately from display resolution. I mean, sometimes I want to play it "canonical way", with 320x200 fullscreen. If I just set the resolution to this, this will cause changing the display resolution, also messing up the result on LCD.
If we'd have separate display and ingame resolutions, I could set the first to my native (1920x1080) and the second to the desired (e.g 320x200) and then get the "canonical" feeling without any distortions. This behaviour would be similar to Chocolate DOOM's and DOSBox' ones when setting the resolution to native -- ingame one stays the same, the output image just get software scaled up to the native (preserving the aspect ratio of the original image).

There's also the ultimate option for DOSBox via GL shaders: pixel-perfect scaling. This means that we can't have fractional scaling factor -- if the display resolution is 1920x1080 and ingame is 320x200 (320x240 after correction), we can scale only up to 1280x960 (320x240 * 4, as 320x240 * 5 = 1600x1200 which exceeds the height of 1080), then we put this in the center and fill the rest with black.
Not so much needed as the first feature, but I really like how the result looks like in comparison to "standard" scaling.

**Comment by fabiangreffrath** [comment]
@solbjorn I guess you will like the changes I am preparing in https://github.com/coelckers/prboom-plus/pull/160. Here, I change the meaning of the "Screen Multiple Factor" from a mere intermediate overscaling of the framebuffer to a "window size factor". That is, your game window will have an initial size of (factor * resolution), just like the `-1`, `-2`, `-3` etc. parameters in Chocolate Doom. It doesn't work for fullscreen, though, as the game is always scaled up to fill the entire screen in that case. However, this PR will also introduce an "Integer Screen Scaling" option which does exactly what you suggest and restricts the screen size to integer multiples of the game resolution.

**Comment by solbjorn** [comment]
@fabiangreffrath, will be glad to check it out when it's done!

**Comment by solbjorn** [comment]
Just tried it, and it's awesome, thanks!

Noticed one issue here, not sure if it's not intended: mouse sensivity is way lower on low resolutions.

**Comment by fabiangreffrath** [comment]
> Just tried it, and it's awesome, thanks!

Thanks!

> Noticed one issue here, not sure if it's not intended: mouse sensitivity is way lower on low resolutions.

But this is not new since this commit, right?

**Comment by solbjorn** [comment]
> But this is not new since this commit, right?

Didn't tried low resolutions prior to this change, so can't tell for sure, but seems like it's an old one.
Should I create a new issue then?

**Comment by fabiangreffrath** [comment]
Not sure. I am afraid, people will jump into my face when I change the mouse code.
