### ISSUE TITLE
Fist/Chainsaw toggle not working

### ISSUE THREAD

**Issue by doomplayer666** [coelckers/prboom-plus#161]
i have it on but it just doesnt work for me, any fixes?

**Comment by doomplayer666** [comment]
either im dumb or its a bug

**Comment by JadingTsunami** [comment]
What option are you talking about? What key are you pressing and what is it bound to in your configuration?

**Comment by doomplayer666** [comment]
im talking about the doom_weapon_toggle option, i am pressing the 1 key

**Comment by doomplayer666** [comment]
nvm i got it fixed
