### ISSUE TITLE
back to one binary "prboom-plus" with OpenGL rendering

### ISSUE THREAD

**Issue by fabiangreffrath** [coelckers/prboom-plus#166]
The current situation with two binaries - one with support for OpenGL rendering and one without - is a relic of the 1990. I don't remember which version of Windows 95/98 exactly came with OpenGL out-of-the-box, but it was not a given fact back then that your OS would support that interface. However, today every mobile phone could be expected to provide such functionality.

So, I propose to build only one binary by default which has of course OpenGL enabled. We should leave it as a compile time option, though, for those rare cases that don't support it, but by today's standards it should be enabled by default. Thus, this would merely boil down to a change in the CMake build system, all the `#ifdef GL_DOOM` checks in the code should remain in place.

@alexey-lysiuk As you are the main author of our current CMake build system, would you like to have a look at this?

**Comment by alexey-lysiuk** [comment]
No, I have zero interest in doing this. Revert 8638d7ba04ffb02068920ae188a1bd1d4a820169 if you want to.

**Comment by fabiangreffrath** [comment]
Oh, is it because you don't like the idea or have you lost interest in this project?

**Comment by alexey-lysiuk** [comment]
Because no matter what we do, there will be a bunch of people how will complain like we broke everything again.
This is especially true for conservative projects like PrBoom.
I tried to make things better, but it led to new complains, see #91 for example.

**Comment by kraflab** [comment]
I'm definitely in favor of having only one exe. That's a point of confusion I see come up now and then for new players. If there are bugs in the gl build then the solution isn't to have 2 exes but to fix the issues I think.
