### ISSUE TITLE
mouse sensitivity is resolution-dependent

### ISSUE THREAD

**Issue by fabiangreffrath** [coelckers/prboom-plus#167]
When switching to lower resolutions and upscaling them to screen, mouse movement seems to be generated relative to the original framebuffer coordinates. This needs further investigation.

**Comment by fabiangreffrath** [comment]
```
--- a/prboom2/src/SDL/i_video.c
+++ b/prboom2/src/SDL/i_video.c
@@ -315,10 +315,11 @@ while (SDL_PollEvent(Event))
   case SDL_MOUSEMOTION:
     if (mouse_enabled && window_focused)
     {
+      int xrel, yrel;
       event.type = ev_mouse;
-      event.data1 = I_SDLtoDoomMouseState(Event->motion.state);
-      event.data2 = Event->motion.xrel << 4;
-      event.data3 = -Event->motion.yrel << 4;
+      event.data1 = I_SDLtoDoomMouseState(SDL_GetRelativeMouseState(&xrel, &yrel));
+      event.data2 = xrel << 4;
+      event.data3 = -yrel << 4;
       D_PostEvent(&event);
     }
     break;
```

**Comment by kraflab** [comment]
Is this going to end up changing everyone's effective mouse sensitivity?

**Comment by fabiangreffrath** [comment]
Well, as it is now, mouse sensitivity depends on the framebuffer resolution hat gets scaled up to your screen size. After this change, mouse sensitivity will only depend on your screen size, independent of the framebuffer resolution. 

If you played only with your screen's native resolution before, you won't notice a difference.

**Comment by kraflab** [comment]
I play in a smaller window :^)
I'm fine readjusting personally, but do we need a setting that toggles the old behaviour?

**Comment by fabiangreffrath** [comment]
I guess I put it wrong. If framebuffer size matches screen or window size, you won't feel a difference.

As it is now, if you scale a 320x200 framebuffer up to 640x480 and then play with unscaled 640x480 framebuffer, the mouse will feel differently. With the new code, it won't.

**Comment by kraflab** [comment]
Aha, alright then 👌

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/8340ffc505b9d7aa3406a2be144474d40e849b3d
