### ISSUE TITLE
OpenGL rendering issues

### ISSUE THREAD

**Issue by T-Will133** [coelckers/prboom-plus#173]
When using the OpenGL renderer, some textures become misaligned and sectors with F_SKY1 can block sectors behind it if the ceiling is set low enough.

Using E4M6 to demonstrate.

8-bit software
![doom03](https://user-images.githubusercontent.com/59149832/104963992-3a70a680-59a1-11eb-8fbe-b2272ca6899c.png)

OpenGL
![doom02](https://user-images.githubusercontent.com/59149832/104964002-3fcdf100-59a1-11eb-8ead-388c2923d531.png)

Build
64-bit (commit e96bc52)

OS
Windows 10 Home 2004

**Comment by fabiangreffrath** [comment]
This has been reported before:
https://sourceforge.net/p/prboom-plus/bugs/235/

**Comment by T-Will133** [comment]
Since this has been reported before, what is preventing it from being resolved?

**Comment by JadingTsunami** [comment]
It's not a simple fix. I don't think anyone has been interested to try and re-write the parts of the renderer that would need to be re-done to address it.

**Comment by T-Will133** [comment]
Had a feeling it wouldn’t be easy to fix. Still great to see PrBoom being supported on some way.

**Comment by JadingTsunami** [comment]
I thought of a simple way to fix this, but it will need some thought and testing to ensure there are no caveats that cause glitches elsewhere.

The basic idea would be skip generation of blocking sky walls when the front-facing sector is higher than the back-facing sector, and both sectors are sky textured.

I tested and verified this fixes this particular E4M6 issue.

**Comment by fabiangreffrath** [comment]
Reopening as this is currently being worked on.
