### ISSUE TITLE
Doesn't work on Arch Linux

### ISSUE THREAD

**Issue by amiga1985** [coelckers/prboom-plus#175]
When I compile prboom+ on Arch, the compilation finishes without errors. I launch the program, and I can see the title screen and can access the menu. When I try to start a level or when the demo starts playing, the program crashes. When I run as sudo, it works, but it breaks many of the midi settings.
Output:
$  ./prboom-plus -iwad /usr/share/games/doom/DOOM2.WAD     
M_LoadDefaults: Load system defaults.
 default file: /home/steelarm/.prboom-plus/prboom-plus.cfg
 found prboom-plus.wad

PrBoom-Plus v2.5.1.7 (http://prboom-plus.sourceforge.net/)
I_SetAffinityMask: manual affinity mask is 1
 found /usr/share/games/doom/DOOM2.WAD
IWAD found: /usr/share/games/doom/DOOM2.WAD
PrBoom-Plus (built Jan 23 2021 10:30:17), playing: DOOM 2: Hell on Earth
PrBoom-Plus is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.
V_Init: allocate screens.
V_InitMode: using 8 bit video mode
I_CalculateRes: trying to optimize screen pitch
 test case for pitch=640 is processed 63284 times for 100 msec
 test case for pitch=672 is processed 102278 times for 100 msec
 optimized screen pitch is 672
I_InitScreenResolution: Using resolution 640x480
 found prboom-plus.wad
D_InitNetGame: Checking for network game.
W_Init: Init WADfiles.
 adding /usr/share/games/doom/DOOM2.WAD
 adding prboom-plus.wad
W_InitCache

M_Init: Init miscellaneous info.
SetRatio: width/height parameters 640x480
SetRatio: storage aspect ratio 4:3
SetRatio: assuming square pixels
SetRatio: display aspect ratio 4:3
SetRatio: gl_ratio 1.600000
SetRatio: multiplier 1/1
R_Init: Init DOOM refresh daemon - 
R_LoadTrigTables: Endianness...ok.
R_InitData: Textures Flats Sprites 
R_Init: R_InitPlanes R_InitLightTables R_InitSkyMap R_InitTranslationsTables R_InitPatches 
P_Init: Init Playloop state.
I_Init: Setting up machine state.
I_InitSound:  configured audio device with 2048 samples/slice
I_InitSound: sound module ready
S_Init: Setting up sound.
S_Init: default sfx volume 8
HU_Init: Setting up heads up display.
I_InitGraphics: 640x480
I_UpdateVideoMode: 0x20, SDL buffer, direct access
SetRatio: width/height parameters 640x480
SetRatio: storage aspect ratio 4:3
SetRatio: assuming square pixels
SetRatio: display aspect ratio 4:3
SetRatio: gl_ratio 1.600000
SetRatio: multiplier 1/1
ST_Init: Init status bar.
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
I_SignalHandler: Exiting on signal: Segmentation fault
Segmentation fault (core dumped)

**Comment by fabiangreffrath** [comment]
Do you happen to have libfluidsynth 2.1.6 installed? If yes, please downgrade to 2.1.5.

Please check if starting with `-warp 1` works but typing `IDCLEV02` instantly crashes.

**Comment by amiga1985** [comment]
I compiled fluidsynth 2.1.5 and then installed it over 2.1.6 and it works perfectly now. Thanks! :-)

**Comment by fabiangreffrath** [comment]
Great, please inform the SDL maintainers at Arch Linux about this (Debian and Suse are already fixed):
https://www.fluidsynth.org/news/2021/01/23/sdl2-mixer-bug/
