### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by fabiangreffrath** [coelckers/prboom-plus#185]
I guess it's clear that this port needs a new release in the short term. The previous "official" release is more than 1.5 year ago now, and there are ~150 commits in between which fix bugs and add features.

This raises two questions:

1. Which executables do we use for the official release? @alexey-lysiuk Is there a way to get a hand on the executables that are compiled during the CI workflow?
2. Which will be an appropriate version number? I think 2.5.1.8um would be an understatement, so how about 2.5.2 or 2.6 or even 3.0 (though, I feel the latter sounds to "finished", given that the port is still in vivid motion)?

**Comment by kraflab** [comment]
My vote would be 2.6, as I think we've far eclipsed the 2.5 family of versions. We could use the second position to indicate the major addition to headers and demo format represented by the umapinfo merge. I'd agree that 3.0 sounds too much like we're finished 🤠

**Comment by fabiangreffrath** [comment]
Thank you! As always, your opinion is highly appreciated.

**Comment by fabiangreffrath** [comment]
As long as this fork doesn't have a distinct name, should we continue appending "UM" to version numbers to make clear where it comes from?

**Comment by kraflab** [comment]
Ya, I think keeping the um at the end makes sense. Or you could rename the port fabioom+ 😂

**Comment by JadingTsunami** [comment]
I think PrBoom-2.6um is fine for a release title as well. I agree we are beyond the sub-bullets in terms of breadth of change.

At some point the port *should* be renamed entirely, but that's a discussion for another day...

**Comment by fabiangreffrath** [comment]
I am going to hijack the `NEWS` file, which currently contains the changelog up to PrBoom 2.5.0, for our changelog since the fork. So the `doc/prboom-plus-history.txt` file, which contains the PrBoom+ changelog, remains intact.

**Comment by fabiangreffrath** [comment]
Obviously, other documentation needs to be updated as well, but that's not to delay the release any further.

**Comment by MoskovchenkoD** [comment]
Voting for 2.6 as well.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/361b86cba437d9a45b9fb0e9feb8dd1ce5194c46
