### ISSUE TITLE
[Suggestion] Toggle for explosion sound cutoff

### ISSUE THREAD

**Issue by UnluckySpade7** [coelckers/prboom-plus#186]
I realize that the cutoff was in the original DOS version, but it's distracting that the explosion sound just stops out of nowhere, a toggle to turn it off would make it sound a lot better.

Version I'm using is 2.5.1.7 February 7th build

**Comment by MoskovchenkoD** [comment]
You mean, make an option which replaces rocket explosion sound with a barrel explosion?

**Comment by maxmanium** [comment]
> 
> 
> You mean, make an option which replaces rocket explosion sound with a barrel explosion?

They both use DSBAREXP. I think OP is suggesting something similar to misc. sound fixes, like seen in Crispy Doom. Seems like a lot of Fabian's work might not be restricted to his own works!

**Comment by fabiangreffrath** [comment]
I guess we are talking about this: 
https://github.com/fabiangreffrath/woof/commit/c6919c220f3b8c4d3e87e1c39a63c4deb24ecde7

**Comment by fabiangreffrath** [comment]
Native speakers, is this feature called "play sounds at full length" or better "with full length" or "in full length" or "till the end" - or whatever would you call it?

**Comment by UnluckySpade7** [comment]
"Play sounds in full length" sounds good.

**Comment by kraflab** [comment]
At full length sounds more natural, but I'd probably call the option "Disable sound cutoff" or something like that 🤔

**Comment by fabiangreffrath** [comment]
>  "Disable sound cutoff" 

Yep, that one is good.
