### ISSUE TITLE
[Bug] Tracker music in .MOD format doesn't play

### ISSUE THREAD

**Issue by srmoco42** [coelckers/prboom-plus#188]
Hey again,

I've noticed recently that [tracker music](https://en.wikipedia.org/wiki/Module_file) in the .MOD format doesn't play in this fork, while it plays fine in the latest version of regular PrBoom+ (both the stable and test versions). Other formats of tracker music I've seen used in wads (.S3M, .XM, and .IT) play correctly, so it's an issue specific to the .MOD format.

[NoReason's Speedmaps 2](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/nosp2) is an example of a wad that uses some tracker music in the .MOD format, including its D_DM2TTL lump, so it should be easy to compare the behaviour difference between the aforementioned PrBoom+ versions.

Thanks in advance and keep up the great work!

**Comment by fabiangreffrath** [comment]
This might as well be due to the used MOD rendering library (i.e. libdumb).

**Comment by alexey-lysiuk** [comment]
DUMB 2.0.3 doesn't work correctly indeed. Version 0.9.3 seems to play MOD files fine.

I guess, support for 2.x was never completed in the original PrBoom+.
Maybe unrelated, but `duh_render()` function is marked as deprecated.

**Comment by fabiangreffrath** [comment]
Does it help if we replace `DUMB_MOD_RESTRICT_OLD_PATTERN_COUNT` with `DUMB_MOD_RESTRICT_NO_15_SAMPLE ` or even `0` here?

https://github.com/coelckers/prboom-plus/blob/fdbd0a8115cf4bea7e5101e50381668a83530dd0/prboom2/src/MUSIC/dumbplayer.c#L147

**Comment by fabiangreffrath** [comment]
The values may even get `OR`ed, so `3` is also valid.

**Comment by alexey-lysiuk** [comment]
It works with `DUMB_MOD_RESTRICT_NO_15_SAMPLE`, and with `0` too.

**Comment by fabiangreffrath** [comment]
From looking at `readmod.c:it_mod_load_sigdata()`, I conclude that setting this to `0` will correspond to the old libdumb 0.9.3 behaviour.

**Comment by fabiangreffrath** [comment]
@alexey-lysiuk Would you like to adjust this in the code?

**Comment by alexey-lysiuk** [comment]
Done. It would nice to know why that flag was used for DUMB 2.x though.

**Comment by fabiangreffrath** [comment]
I introduced that change back then but don't remember why, honestly.

**Comment by fabiangreffrath** [comment]
This provides some insight into this issue: https://github.com/kode54/dumb/issues/86

Upstream recommends setting this to `1` which would invalidate 15 sample modules, but since this restriction wasn't in libdumb 0.9.3 before, either, I guess we play safe with leaving it at `0`.
