### ISSUE TITLE
Simplify Build Process

### ISSUE THREAD

**Issue by 01y** [coelckers/prboom-plus#19]
Will help to keep track of/ eliminate dependencies, also to facilitate ports to other platforms (such as Playstation Vita, Switch, etc.). And to provide an easier way to keep up with changes to various platforms, for instance, at the time of this post, on MacOS, compiling requires using --disable-gl, by default it fails.

(creating an issue to correspond to the existing discussion on the Doomworld forums, re: CMake)

**Comment by Rathori** [comment]
Moving to CMake would be nice, meanwhile I made a pull request https://github.com/coelckers/prboom-plus/pull/23 to fix macOS builds.

**Comment by coelckers** [comment]
CMake would be nice indeed, what's blocking this mainly is the multitude of libraries that need to be declared as dependencies. Some are a bit obscure and I have no idea how to name them in CMake so that Linux picks them up.

**Comment by coelckers** [comment]
CMake was added today.
