### ISSUE TITLE
[Issue] The Video Rendering within the Window Scales to Windows-Set System-Wide Scale.

### ISSUE THREAD

**Issue by PhoxFyre** [coelckers/prboom-plus#192]
![ApplicationFrameHost_B1CzYRCP2b](https://user-images.githubusercontent.com/16215326/107603372-1eec6a80-6bf2-11eb-943a-41649c9ae0b9.png)
I cannot have my Windows set at 150% scale (as shown in photo) as it will scale and misalign the actual video rendered inside PrBoom+. it works fine when the scale is 100% but was wondering if there is any way that this can be fixed to not scale or scale properly with system-wide scaling?

**Comment by fabiangreffrath** [comment]
This is probably what the more-or-less undocumented `SDL_WINDOW_ALLOW_HIGHDPI` SDL_Window flag is for. Does this affect both software and OpenGL rendering? DO you have a chance to check if this makes a difference?

```
--- a/prboom2/src/SDL/i_video.c
+++ b/prboom2/src/SDL/i_video.c
@@ -1173,6 +1173,9 @@ void I_UpdateVideoMode(void)
     init_flags = SDL_WINDOW_OPENGL;
   }

+  // Set the highdpi flag
+  init_flags |= SDL_WINDOW_ALLOW_HIGHDPI;
+
   // Fullscreen desktop for software renderer only - DTIED
   if (desired_fullscreen && V_GetMode() != VID_MODEGL)
     init_flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;

```

**Comment by PhoxFyre** [comment]
Apologies for getting back to you so late on this issue. I have confirmed it only has the issue with OpenGL renderer as the 8 and 32bit renderers work fine with the scaling, it is only the OpenGL renderer that has that issue of not rendering properly.

**Comment by JadingTsunami** [comment]
I have been working to address the OpenGL issues but I don't have a Windows machine to work on this one.

I would consider seeing if `SDL_GetDisplayDPI` can return what is needed, if I were to start on this.

**Comment by fabiangreffrath** [comment]
> This is probably what the more-or-less undocumented `SDL_WINDOW_ALLOW_HIGHDPI` SDL_Window flag is for. 

Nope, this doesn't fix it.

**Comment by fabiangreffrath** [comment]
Apparently we need to find the ratio between the results of `SDL_GetDisplayDPI()` and the "default DPI" without SDL telling us anything about the latter: 

https://nlguillemot.wordpress.com/2016/12/11/high-dpi-rendering/

**Comment by fabiangreffrath** [comment]
This could work (sorry, no chance to test on Windows currently);
```patch
diff --git a/prboom2/src/SDL/i_video.c b/prboom2/src/SDL/i_video.c
index 234ee034..1bf5ce73 100644
--- a/prboom2/src/SDL/i_video.c
+++ b/prboom2/src/SDL/i_video.c
@@ -1132,6 +1132,21 @@ video_mode_t I_GetModeFromString(const char *modestr)
   return mode;
 }
 
+static float GetDisplayScalingFactor(void)
+{
+    float dpi;
+    int ret;
+
+    ret = SDL_GetDisplayDPI(0, NULL, &dpi, NULL);
+
+#if defined(__APPLE__)
+    if (ret == 0) return dpi / 72.0f; else
+#elif defined(_WIN32)
+    if (ret == 0) return dpi / 96.0f; else
+#endif
+    return 1.0f;
+}
+
 void I_UpdateVideoMode(void)
 {
   int init_flags = 0;
@@ -1198,6 +1213,8 @@ void I_UpdateVideoMode(void)
   if (V_GetMode() == VID_MODEGL)
   {
 #ifdef GL_DOOM
+    float scaling = GetDisplayScalingFactor();
+
     SDL_GL_SetAttribute( SDL_GL_RED_SIZE, 0 );
     SDL_GL_SetAttribute( SDL_GL_GREEN_SIZE, 0 );
     SDL_GL_SetAttribute( SDL_GL_BLUE_SIZE, 0 );
@@ -1218,7 +1235,7 @@ void I_UpdateVideoMode(void)
     sdl_window = SDL_CreateWindow(
       PACKAGE_NAME " " PACKAGE_VERSION,
       SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
-      SCREENWIDTH, SCREENHEIGHT,
+      (int)(scaling * SCREENWIDTH), (int)(scaling * SCREENHEIGHT),
       init_flags);
     sdl_glcontext = SDL_GL_CreateContext(sdl_window);
 
```
