### ISSUE TITLE
do any of these wads work for prboomlus?

### ISSUE THREAD

**Issue by DOOMMARINE117** [coelckers/prboom-plus#194]
does this support alien_Eradication_TC.pk3 mod? i see it has eradicationmapset.wad. what about the main one? 

how do you load master levels?

does doom_complete.pk3 support this?

what about rekkr an heretic? 

it loads zblood. what about the other 3 files of zblood? 

wolfenstein 3d mod by afadoomer?

castlevania simon destiny mod?

a new update has been added to temple of doom mod. 

is the DN3DOOM mod will work on this too? 

will other music mods work on here? like custom made ones?

thanks.

**Comment by UnluckySpade7** [comment]
First off, let me state that any PK3 file mod won't work in PRboom, so no, Doom Complete, Alien Eradication, Simon's Destiny or DN3Doom won't work.
Second, Rekkr does work but Heretic doesn't.
Third, AfaDoomer's Wolfenstein TC won't work either, neither will Zblood.
And lastly, music mods are possible.

**Comment by DOOMMARINE117** [comment]
cool, thanks.
