### ISSUE TITLE
SDL quit, memory leak

### ISSUE THREAD

**Issue by BeWorld2018** [coelckers/prboom-plus#200]
Hi

I see a memory leak... 
When you call I_ShutdownSDL(), you dont destroy screen, surface, texture, window, renderer etc....

I test and you can put that before SDL_Quit();

if (sdl_glcontext) SDL_GL_DeleteContext(sdl_glcontext);
if (screen) SDL_FreeSurface(screen);
if (buffer) SDL_FreeSurface(buffer);
if (sdl_texture) SDL_DestroyTexture(sdl_texture);
if (sdl_renderer) SDL_DestroyRenderer(sdl_renderer);
SDL_DestroyWindow(sdl_window);

thanks

**Comment by fabiangreffrath** [comment]
Exactly what I thought earlier today: 
https://github.com/coelckers/prboom-plus/issues/191#issuecomment-778125276

**Comment by BeWorld2018** [comment]
yes i dont see this comment :-) thanks
