### ISSUE TITLE
Full screen alt-tab broken

### ISSUE THREAD

**Issue by kraflab** [coelckers/prboom-plus#202]
Daerik reported to me that when you alt tab while playing at full screen the game doesn't release the cursor and you can't click on anything currently (at least on windows).

**Comment by fabiangreffrath** [comment]
Sounds like this issue:
https://github.com/fabiangreffrath/woof/commit/cb98e17d728fc3a88babaabded099f3ce0d307b5

**Comment by kraflab** [comment]
Looks like it, you always have a fix already 🤠
