### ISSUE TITLE
PrBoom+/UMAPINFO v 2.5.1.7 fails to save settings

### ISSUE THREAD

**Issue by GelgoogJager** [coelckers/prboom-plus#209]
Hi, I´m copying post I made on Doomworld forums, regarding the issue

"HELLOOOO DOOMWORLD!

I´m making my first post here after years of lurking around the forums to report a minor, but annoying bug with the newest version of PrBoom+/UMAPINFO v 2.5.1.7.
If your Windows username, like mine, contains non-latin characters, in my example as a Czech user that would be letters like Š, Č, Ř, Ž, Ť, Á and so on, then PrBoom+ will not save your setting.

What do I mean by that? Well frankly put if you start Prboom+, fiddle a bit with settings and then exit the program and start it again, you will notice that the settings reverted to default (starts windowed, all custom bindings set to default, resolution in default, etc.), also you can´t save your progress.

How am I sure that the bug is caused by this? Simple, I logged into a new account on my machine containing no non-latin character simply called Host, and the port sucesfully saved all my settings.
This wasn´t the first time it happened to me, other aplications like Halo Custom Edition with the chimera fan patch/mod, also had problems running and official releases like Nightdive´s System Shock Enhanced Edition still has these problems, although unlike Prboom+ they all crashed after launch.
I also noticed this issue with version 2.5.1.5. but strangely version 2.5.1.4. does not have this bug, so it´s probably something that started in version 2.5.1.5.
For those curious here are my specs, although I believe this is a software issue.

 

OS: Windows 10
Graphics Card: Nvidia Gtx 1050 Ti

Procesor: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz 3.20 GHz

RAM: 12,0 GB"

**Comment by MoskovchenkoD** [comment]
Looks like the issue is [solved](https://www.doomworld.com/forum/topic/119873-prboomumapinfo-v-2517-fails-to-save-settings/) and the case can be closed.

**Comment by fabiangreffrath** [comment]
Na, this is merely a workaround. We should be able to write the config into our own directory - or at least into a directory where we can find it again upon next start.
