### ISSUE TITLE
Signal 22 error starting in 2.6um

### ISSUE THREAD

**Issue by Narienn** [coelckers/prboom-plus#214]
Hi there, kraflab sent me this way from Discord.
I'm currently using PRB+ 2.5.1.7um with no issues, but the new 2.6um will not launch on my PC with the error `I_SignalHandler: Exiting on signal: signal 22`. I have copied the folder to my laptop and it works fine there and I've done a lot of reading threads/Discord/the other issues on this page so I know that (almost) nobody is encountering this and it's something specific to my PC. Unfortunately I don't know where to start to diagnose it. I'm on Windows 10 20H2 on both devices with a completely fresh install of 2.6um. I've tried all the IWADs available to me and get the same result. I have a feeling this is something simple but like I said the error message doesn't give me much to go on. I'm having the same issue with dsda-doom but it seems pretty likely that the solution will be the same. I would appreciate any advice, thanks!

**Comment by fabiangreffrath** [comment]
Signal 22 appears to be `SIGABRT`, i.e. "Abnormal termination", which is quite generic. Do you have any chance to build the executable yourself on this very computer, preferably using MSYS2?

**Comment by Narienn** [comment]
I would be glad to try but I'm a complete novice at this and would pretty much need step-by-step instructions. I've installed MSYS2, run through their "Getting Started" page, and started following the instructions in the INSTALL file but am having trouble determining which packages I need. Here's the output after I enter the `cmake` command: [output.txt](https://github.com/coelckers/prboom-plus/files/6029115/output.txt). There's obviously a lot of errors there but I'm not sure what to do now. 

This is probably not worth your time since it's such an isolated issue, so I'll understand if you tell me to just deal with it and close this.

**Comment by fabiangreffrath** [comment]
Even if you don't get to compile it yourself, it would be very helpful if you could paste the output to the terminal window that's printed when you start the v2.6um game executable.

**Comment by Narienn** [comment]
I'm embarrassing myself here but I'm not sure what you mean by that. I don't know how to launch the executable in a way that would give me feedback like that.

**Comment by fabiangreffrath** [comment]
No problem. Please open the MSYS2 or MINGW32 shell and navigate to the directory where you have stored the v2.6um release. For example, if you have stored it under `D:\Games\Doom\PrBoom-Plus` the command you'll have to type is `cd /d/Games/Doom/PrBoom-Plus`. If your path contains blank spaces or non-Latin characters, try to hit Tab after typing the first letter to ask for auto-completion. Once you have navigated to the directory containing prboom-plus.exe, type `./prboom-plus.exe` in the command shell window. It should then start the executable and print desbug messages into the shell window.

**Comment by Narienn** [comment]
Ahh okay, here we go:

```
Nathan@NATEYSTATION3 MSYS ~/prboom-plus-26um-w32
$ ./prboom-plus.exe
M_LoadDefaults: Load system defaults.
 default file: D:\msys2\home\Nathan\prboom-plus-26um-w32/prboom-plus.cfg
 found D:\msys2\home\Nathan\prboom-plus-26um-w32/prboom-plus.wad

PrBoom-Plus v2.6um (https://github.com/coelckers/prboom-plus)
 found D:\msys2\home\Nathan\prboom-plus-26um-w32/doom2.wad
IWAD found: D:\msys2\home\Nathan\prboom-plus-26um-w32/doom2.wad
PrBoom-Plus (built Feb  9 2021 04:13:48), playing: DOOM 2: Hell on Earth
PrBoom-Plus is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.
V_Init: allocate screens.
V_InitMode: using 8 bit video mode
I_CalculateRes: trying to optimize screen pitch
 test case for pitch=640 is processed 185140 times for 100 msec
 test case for pitch=672 is processed 114411 times for 100 msec
 optimized screen pitch is 640
I_InitScreenResolution: Using resolution 640x480
 found D:\msys2\home\Nathan\prboom-plus-26um-w32/prboom-plus.wad
D_InitNetGame: Checking for network game.
W_Init: Init WADfiles.
 adding D:\msys2\home\Nathan\prboom-plus-26um-w32/doom2.wad
 adding D:\msys2\home\Nathan\prboom-plus-26um-w32/prboom-plus.wad
W_InitCache

M_Init: Init miscellaneous info.
SetRatio: width/height parameters 640x480
SetRatio: storage aspect ratio 4:3
SetRatio: assuming square pixels
SetRatio: display aspect ratio 4:3
SetRatio: gl_ratio 1.600000
SetRatio: multiplier 1/1
R_Init: Init DOOM refresh daemon -
R_LoadTrigTables: Endianness...ok.
R_InitData: Textures Flats Sprites
R_Init: R_InitPlanes R_InitLightTables R_InitSkyMap R_InitTranslationsTables R_InitPatches
P_Init: Init Playloop state.
I_Init: Setting up machine state.
I_InitSound:  configured audio device with 2048 samples/slice
Fluidplayer: Fluidsynth version 2.1.6
I_SignalHandler: Exiting on signal: signal 22
I_ShutdownSound:
 default file: D:\msys2\home\Nathan\prboom-plus-26um-w32/prboom-plus.cfg
IWAD found: D:\msys2\home\Nathan\prboom-plus-26um-w32/doom2.wad
PrBoom-Plus (built Feb  9 2021 04:13:48), playing: DOOM 2: Hell on Earth
PrBoom-Plus is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.
Assertion failed!

Program: D:\msys2\home\Nathan\prboom-plus-26um-w32\prboom-plus.exe
File: ../portaudio/src/hostapi/wdmks/pa_win_wdmks.c, Line 1061

Expression: FALSE
I_SignalHandler: Exiting on signal: signal 22
```

**Comment by fabiangreffrath** [comment]
Okay, so it seems to fail some assertion in portaudio. Could you please open your prboom-plus.cfg file and change the value on the line starting with `snd_midiplayer` to read `"sdl"` or `"opl2"` ?

**Comment by Narienn** [comment]
That did it! I didn't have a prboom-plus.cfg in the 2.6 folder yet (I assume it was never getting far enough to create one) but I grabbed my current one out of my 2.5.1.7 install and changed that line and now 2.6 is launching correctly. Thank you so much, I'm sorry it took so long to actually get the information you needed to diagnose this.

**Comment by fabiangreffrath** [comment]
No problem, I'm glad I could help. Needless to say something like this shouldn't happen in the first place...

**Comment by kraflab** [comment]
@fabiangreffrath 

Krankdud had this problem as well and was looking into it...he was able to make it work by copying over the dlls from the old windows_dependencies zip. Specifically all 5 of these:

```
libfluidsynth-2.dll
glib-2.dll
libintl.dll
libiconv.dll
libcharset.dll
```

Fluidsynth for instance is version 2.1.0 in the old zip and is 2.1.6 in pr+ 2.6. Fwiw this problem also exists for dsda-doom with different versions. Idk if there is a bug there that affects some users or what exactly...

**Comment by Krankdud** [comment]
I looked into it a bit more and it looks like it has something to do with the portaudio dll. Replacing it with the dll from [here](https://github.com/adfernandes/precompiled-portaudio-windows/) works. I'll try to dig more into it later.

**Comment by kraflab** [comment]
Daerik reported that another person with this issue couldn't fix it by changing the midiplayer and can only launch with `-nomusic`.
