### ISSUE TITLE
Mous6 and mouse7 buttons are not saving in my weapon binds

### ISSUE THREAD

**Issue by JuanchoES** [coelckers/prboom-plus#215]
https://user-images.githubusercontent.com/70743149/108787679-83a2b000-7576-11eb-8ad9-702d899db325.mp4

**Comment by kraflab** [comment]
https://github.com/coelckers/prboom-plus/blob/f404802515cf26ce933e54873d71ee9aa29540ff/prboom2/src/m_misc.h#L116

Seems like the config file has a separate mouse button limit defined compared to the input code, so when we added mouse buttons previously that didn't translate to the config file.
