### ISSUE TITLE
line-teleport height clitch

### ISSUE THREAD

**Issue by simc2** [coelckers/prboom-plus#216]
Flying monsters above ground (and leaping players during demo playback) first appear on the floor after line-line-teleportation, after which their height from the floor "is adjusted" to match the height at the moment of the teleport launch. The height adjustment happens seemingly during one tic.

This happens both with 8-bit software and opengl modes but only with uncapped framerate. It happens from PrBoom-Plus 2.2.6.19 (the earliest?) to the latest 2.6um. I can't observe this in PrBoom 2.5.0 or before.

Here's test level for Doom2 map01. 
[teleport_test.zip](https://github.com/coelckers/prboom-plus/files/6026839/teleport_test.zip)

Shoot the pistol and a group of cacodemons start teleporting repeatedly. Slow down the game speed to see better.

**Comment by fabiangreffrath** [comment]
Hm, indeed it seems the mobj's previous z-coordinate, which is used to interpolate with the current coordinate, is set to the target sector's floorz value here:
https://github.com/coelckers/prboom-plus/blob/051c4a5222fcb21df11f50f154036ce1196ea6ed/prboom2/src/p_map.c#L353

Apparently, this isn't always the best solution. It's probably better to set this to `thing->PrevZ = thing->z` ?
