### ISSUE TITLE
fluidsynth breaks as soon as songs start looping

### ISSUE THREAD

**Issue by locque** [coelckers/prboom-plus#218]
I'm playing Eviternity with Arachno, and while the songs sound great the first time, something goes wrong as soon as the first loop starts. The volume of some instruments gets scrambled, and it sounds like some parts are played completely out of time.

Listen to this and compare the timestamps I've put in the description: https://youtu.be/QEM8jKK4XGo

**Comment by fabiangreffrath** [comment]
Does this help?
```patch
--- a/prboom2/src/MUSIC/flplayer.c
+++ b/prboom2/src/MUSIC/flplayer.c
@@ -455,7 +455,10 @@ static void fl_render (void *vdest, unsigned length)
             // fix buggy songs that forget to terminate notes held over loop point
             // sdl_mixer does this as well
             for (i = 0; i < 16; i++)
+            {
               fluid_synth_cc (f_syn, i, 123, 0); // ALL NOTES OFF
+              fluid_synth_cc (f_syn, i, 121, 0); // RESET ALL CONTROLLERS
+            }
             continue;
           }
           // stop, write leadout

```

**Comment by locque** [comment]
I'd love to try it, but I can't figure out how to build for Windows. I managed to build for Linux using Ubuntu on the WSL, but I don't understand the cross-compiling instructions. I can't even find configure.ac, where is that supposed to be?

**Comment by TwelveEyes** [comment]
> Does this help?
> 
> [snip]

This seems to have fixed it.

Test recording, only tested 2 loops of the midi: https://youtu.be/bq2AzOI1SZU

**Comment by fabiangreffrath** [comment]
> I'd love to try it, but I can't figure out how to build for Windows. I managed to build for Linux using Ubuntu on the WSL, but I don't understand the cross-compiling instructions. I can't even find configure.ac, where is that supposed to be?

So, the issue doesn't occur on Linux? Or why do you think you would have to cross-compile? Also, this project has switched build systems to CMake, so there is no `configure.ac` file around anymore.

**Comment by locque** [comment]
No that's not what I meant, I don't have a Linux machine right now. It's just that there are only build instructions for Linux, and I have no idea how to setup up compilation and the dependencies on Windows. I couldn't run it though since there's no X server on the WSL.

Can CMake be configured to cross-compile? Even if I managed to manually set everything up on Windows, it seems way more comfortable to build on the WSL with a package manager.

**Comment by fabiangreffrath** [comment]
Cmake should be native to any platform. You can generate Unix Makefiles but also Visual Studio projects out of it. If you could setup MSYS2 it will even allow you to build native binaries using MingW/gcc just as on Linux.

**Comment by fabiangreffrath** [comment]
Related: https://github.com/coelckers/prboom-plus/wiki/Building-PrBoom-Plus-on-Windows
