### ISSUE TITLE
Way to delete saves (feature)

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#219]
Not super important and perhaps just a pet-peeve of mine but I'd find it convenient to be able to delete saves by pressing the "delete" key on the keyboard - either with or without a confirmation. This would work in both "Load" and "Save" sections. Currently I delete them by removing the save files or by overwriting them with new saves.

**Comment by snoggie1487** [comment]
Yes, please

**Comment by runlow** [comment]
Works very well, thank you!
