### ISSUE TITLE
Exclusive fullscreen option for g-sync/freesync monitors

### ISSUE THREAD

**Issue by Kappa971** [coelckers/prboom-plus#225]
It would be useful to have an option to turn on exclusive full screen for owners of a g-sync/freesync monitor

**Comment by fabiangreffrath** [comment]
I could add this as a "secret" option that is available in the config file but not exposed to the in-game menu.

**Comment by fabiangreffrath** [comment]
Wait a minute. Just to make sure we are talking about the same. What you mean is mode-changing fullscreen, i.e. `SDL_WINDOW_FULLSCREEN` instead of `SDL_WINDOW_FULLSCREEN_DESKTOP`, right? Fullscreen mode with the Opengl renderer already does this. So, this id what you want but for the software renderer?

**Comment by Kappa971** [comment]
Yes exclusive fullscreen for software renderer

**Comment by fabiangreffrath** [comment]
Alright, thank you. I was asking, because when you first mentioned freesync I thought you were talking about this adaptive V-Sync stuff. But this wouldn't have anything to do with fullscreen then.

**Comment by Kappa971** [comment]
In the meantime, thanks for your availability. Actually a freesync or g-sync monitor needs the game to support exclusive full screen to work properly. Prboom+ in the software renderer works in borderless fullscreen, so the monitor refresh rate does not change, which is why an option to activate exclusive fullscreen would be useful

**Comment by fabiangreffrath** [comment]
Alright. I' like to add this by accepting the `2` for the `use_fullscreen` config variable. Unfortunately, PrBoom+'s config file format doesn't allow for any per-key comments (as MBF's does), so this needs to get properly documented anywhere else.
