### ISSUE TITLE
[REQUEST] Master Levels support

### ISSUE THREAD

**Issue by snoggie1487** [coelckers/prboom-plus#229]
Currently in Crispy Doom, Master Levels maps that require Dead Simple tags will be able to use them, even if they are not in slot 7. In map15 (Mephisto's Mausoleum), you need to kill some mancubi for some tag 666 walls to lower. This works fine in Crispy Doom, but does nothing in PrBoom+

**Comment by JadingTsunami** [comment]
This port supports UMAPINFO; this would seem to be the proper way to resolve this issue.

**Comment by snoggie1487** [comment]
> This port supports UMAPINFO; this would seem to be the proper way to resolve this issue.

What UMAPINFO tag do I need to use?

**Comment by JadingTsunami** [comment]
`bossaction` should be what you're looking for. The documentation has details on it.
