### ISSUE TITLE
Mouse Investigation

### ISSUE THREAD

**Issue by kraflab** [coelckers/prboom-plus#238]
Mouse input in pr+ is multiplied by 16, then multiplied by the horizontal sensitivity, and then divided by 10.

If you have a horizontal sensitivity of 1, this means that an SDL input of 1 will yield a mousex value of 1.
An SDL input of 2 will yield a mousex value of 3 (32 * 1 / 10).

Here's a graph displaying the effect of truncating the mouse value in this way, for horizontal sensitivity of 1:
https://cdn.discordapp.com/attachments/776233266411339786/819480864102678548/chart_1.png

The x axis is the value reported by SDL, and the y axis is the ratio between the truncated integer value and the full input value (input * 16 / 10) as a double.

This graph looks better the higher your sensitivity. Here is the same graph for horizontal sensitivity 7:
https://cdn.discordapp.com/attachments/776233266411339786/819480616055603260/chart.png

---

This issue is especially bad in pr+ because mouse input is handled for each SDL_MOUSEMOTION event, instead of only being checked once per game tic. That means that a value of 7 accrued over one turn may be reported as 7 events with a value of 1, leading to high truncation. The likelihood of that is based on your mouse's polling rate. Adopting a once-per-tic evaluation of mouse position significantly reduces the error rate, but doesn't completely remove it.

I addressed a whole bunch of issues related to this here: https://github.com/kraflab/dsda-doom/pull/13

Most likely adopting the once-per-tic evaluation is sufficient and simple for pr+ (and mirrors what happens in, e.g., crispy). I went further in dsda-doom and applied carries to all the fractional mouse movement, as well as adjustments to mouse input scaling, and other elements of mouse configuration, which are probably not as relevant or desired in mainline pr+. The commits are relatively well-separated though 🧐

**Comment by fabiangreffrath** [comment]
> I addressed a whole bunch of issues related to this here: [kraflab/dsda-doom#13](https://github.com/kraflab/dsda-doom/pull/13)

I have ported what I consider the most relevant part over to the prboom-plus code base here: #239

Now, how do I get rid of the stupid game of multiply by 16 and then divide by 10 without forcing everyone to readjust their mouse sensitivities? :thinking:

**Comment by runlow** [comment]
If the mouse is to work better overall - I think having to readjust the mouse sensitivity setting is not such a big deal.

**Comment by fabiangreffrath** [comment]
Well, telling *everybody" to increase their sensitivities by factor 1.6 is probably a bigger deal than you might think. Remember the shitstorm when I introduced the colored blood palette hack as an optional gimmick? I am not going through this again anytime soon.
