### ISSUE TITLE
Kills/Items/Secret line for the advanced HUD

### ISSUE THREAD

**Issue by fabiangreffrath** [coelckers/prboom-plus#240]
People asked for it. It is going to look like the implementation in DSDA (but without the percentage, I guess) but will be adapted to the existing advanced HUD infrastructure that is already there in `hu_stuff.c`.

**Comment by fabiangreffrath** [comment]
@kraflab I will need your assistance here. In this one thread on DW you stated that the HUD is tightly tailored to specific DSDA needs. What exactly does this mean? Which parts of the code will I need to change in order to turn the information into something generally valid?

**Comment by kraflab** [comment]
The numbers in pr+ aren't invalid, but they aren't the numbers that a speedrunner would want. So, the average user of pr+ may actually prefer the current totals that pr+ uses. E.g., if you're playing doom 2 map 30 and 100 enemies spawned, would a user want to see x/101 kills or x/1, which is what dsda-doom would show.

As an example, monsters spawned by the icon of sin aren't required to be killed in the UV Max category, so in dsda-doom we track the spawn source and check it when counting kills. Monsters that spawn in the middle of a level but not from an icon of sin, like arachnorbs in valiant, do count for UV Max.

So basically in dsda-doom there was a stage where the numbers appearing in the advanced hud were changed, and then later on the extended hud was implemented, with those new numbers. So, that's what I meant in the thread - to implement dsda-doom's numbers exactly, it would require the adjustment to tracking as well. But to simply take the existing advanced hud logic and put it above the status bar, that wouldn't be required.

In case you want to change the tracking, I dug up a bunch of commits, hopefully it collects the whole picture...

Tracking icon spawns:
https://github.com/kraflab/dsda-doom/commit/88a83760a4bd8bc10554b605267f0ff711b092ae

Changing "smart totals":
https://github.com/kraflab/dsda-doom/commit/179ab533f3c81634c06a68a2aa5ebd4c92c74fae

Rename to "max totals" (disambiguate from the pr+ measurement):
https://github.com/kraflab/dsda-doom/commit/3da31a7a821767f5636e208623a5e11fe5562f23

Account for non-icon spawns during a map:
https://github.com/kraflab/dsda-doom/commit/b71fd7c3e7f075b4fae6a44d3ba428ba107ab048

Extended hud:
https://github.com/kraflab/dsda-doom/commit/41742f462d0304c3d11ba89dfe166774e22aec58

As I mentioned on dw, the extended hud is still wip. For instance, its display position is based on the doom format for the status bar. Users who have the bar scaled differently end up seeing a gap between the hud and the bar. So, you can assume that any code related to it may have errors. 🤷 I'm going to add lots of stuff to that hud eventually, so I've been saving bug fixes for whenever I decide to work on that.

**Comment by fabiangreffrath** [comment]
Alright, thank you!

Since there is already the "monsec" widget available in the HUD [1], we more-or-less only need to add a level time widget and a means to show the "monsec" widget above the status bar.

[1] https://github.com/coelckers/prboom-plus/blob/fb34cc0b7060e73ae4012a956682ea308183b9ae/prboom2/src/hu_stuff.c#L1905

**Comment by fabiangreffrath** [comment]
> add a level time widget 

Wait a minute, this is already there, but disabled by default. So, we just need a proper condition for showing the widgets, taking all of automap, overlay, etc. into account - and a way to properly arrange it above the status bar. Something like `2*viewwindowy + viewheight` probably?
