### ISSUE TITLE
next map info on >32 maps incorrect (bug)

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#244]
I get that maybe going beyond `map32` is non-standard (and hence maybe unsupported?), but it's a thing and it works in `prboom-plus`.

**Expected:**
When you `IDCLEV` beyond `map32` in a pwad that has more than 32 maps - the next map shown is the map you would land on if you gone to the exit.

**Observed:**
It always seems to show "map03" as next when beyond 32 - which seems incorrect.

Tested on [mayhem2020](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/mayhem20)

**Steps:**
1. Start prboom+ with the DOOM2.WAD iwad and mayhem2020 pwad
2. Type `IDCLEV33`
3. Type `IDCLEV` and notice the "next" map, it will say "map03"
4. find the exit with `IDCLIP` and and end the level
5. notice that you're on "map34" next (not "map03")

Pressing PageDown actually takes you to the map the `IDCLEV` cheat shows as "next" (`map03`) so I'm guessing the cheat only *shows* where pressing it would take you. In other words maybe switching levels with PageDown would have to change to work with >32 maps rather than the information shown? Alternatively maybe the next map info should be removed altogether for >32 maps?
![2021-03-19-235246_1920x1080_scrot](https://user-images.githubusercontent.com/2176657/111852290-47ad0180-890e-11eb-8929-055a04b03402.png)

**Comment by TwelveEyes** [comment]
I'm placing this here as it is also related with going above map 32. Map 33 will have the map number and title displayed properly in the automap, but any levels above 33 will not be displayed, instead showing nothing.

**Comment by fabiangreffrath** [comment]
Indeed. From having a look at [1] it seems that the engine simply goes on to the next map if not exiting to or from a secret map. We should probably teach the "Next Map" key to just do the same.

[1] https://github.com/coelckers/prboom-plus/blob/a2cdfe5dfbd8cbd99176abdef232865685cc9718/prboom2/src/g_game.c#L1681

**Comment by fabiangreffrath** [comment]
> I'm placing this here as it is also related with going above map 32. Map 33 will have the map number and title displayed properly in the automap, but any levels above 33 will not be displayed, instead showing nothing.

I agree that the title widget should at least show the generic map lump name (i.e. ExMy or MAPxx).

**Comment by TwelveEyes** [comment]
`IDCLEV` works properly now on maps > 33, but `IDCLEV` on map 33 will still show the next map as map 03, and pressing the "Next Map" key will indeed take you to map 03 instead of map 34 as expected.
