### ISSUE TITLE
hudadd_timests covers map name on automap (bug)

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#245]
Not sure if this was intended to work this way so apologies in advance.

**Expected:**
With `hudadd_timests` set to `1` the player is still able to check the map name in the automap.

**Observed:**
Once the widget is on there doesn't seem to be a way to see the map name any more.

**Steps:**
1. set `hudadd_timests` to `1` in your `prboom-plus.cfg`
2. Start `prboom-plus` with any iwad and pwad
3. Press Tab and try to check the `HUSTR` on the bottom of the screen - it's gone.

**Possible Solutions:**
* Make the widget disappear when the automap is on, make the automap show map name as usual
* Position the map name elsewhere on the automap when the widget is on
![2021-03-19-235556_1920x1080_scrot](https://user-images.githubusercontent.com/2176657/111852400-ad998900-890e-11eb-8096-cd77eb4ce5c0.png)

**Comment by TwelveEyes** [comment]
From a cursory glance at the code, AFAIK it looks like this is intended behavior if you have automap overlay mode activated.

**Comment by fabiangreffrath** [comment]
Indeed, the map title widget is only disabled in overlay mode. This behavior has been explicitly suggested when I announced this feature on the forum:
https://www.doomworld.com/forum/topic/106866-prboomumapinfo-v-2517/?page=32&tab=comments#comment-2273831

Also, AFAICT this behavior matches that of the reference implementation in dsda-doom and also that of the regular advanced HUD.

**Comment by runlow** [comment]
Ah so it **does** work and you just have to toggle the "overlay mode" to see it. (I have it binded to "o")

Never mind then. Thank you!

(one could argue that it's a bit obscure but as long as there's a way - all good!)
