### ISSUE TITLE
(Feature request) An option to disable translucency in projectiles in software﻿ mode

### ISSUE THREAD

**Issue by JuanchoES** [coelckers/prboom-plus#248]
Title, you can switch to opengl and then switch again to software mode to disable translucency in projectiles somehow tho, but i want this as an option.

**Comment by TwelveEyes** [comment]
Already exists as `no predefined translucency for some things` in the prboom-plus settings section of the compatibility menu. You could also use [these](https://sourceforge.net/p/prboom-plus/bugs/_discuss/thread/3c2d4f2a/5d9f/attachment/trans.7z) deh files to disable translucency.

**Comment by JuanchoES** [comment]
> Already exists as `no predefined translucency for some things` in the prboom-plus settings section of the compatibility menu.

 Yea, that does not work with most of complevels, like boom or MBF

> You could also use [these](https://sourceforge.net/p/prboom-plus/bugs/_discuss/thread/3c2d4f2a/5d9f/attachment/trans.7z) deh files to disable translucency.

Thats cool but prboom has an option to disable translucency, but not for projectiles.

**Comment by TwelveEyes** [comment]
> Yea, that does not work with most of complevels, like boom or MBF

When #246 is taken care of I don't believe this should be a problem anymore.

> Thats cool but prboom has an option to disable translucency, but not for projectiles.

Those deh files do exactly what you're looking for, force disable (or enable) translucency on projectiles / items _only_, no matter the complevel. So you can have linedef transparency without projectiles / items (e.g. soulsphere) being transparent using the deh file trans_off, or you can force transparency on in complevels that prohibit it using the deh file trans_on.

**Comment by fabiangreffrath** [comment]
Could anyone please point me to a map that uses a translucent midtexture - preferably with an Imp or Caco in the same room?

**Comment by JuanchoES** [comment]
> Could anyone please point me to a map that uses a translucent midtexture - preferably with an Imp or Caco in the same room?

In Comunity Chest 4 the first map has a translucent texture if you look to the right and in the next room there are imps
