### ISSUE TITLE
map33 still shows map03 as next (bug)

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#249]
This could be a simple off-by-one oversight.

The recent fix works great for me (thank you) on all >33 mapsbut not for map33 which still shows `map03` as the next level.

Tested it on a 6d06b1bb build.

**Steps**
1. Start DOOM2 with mayhem2020
2. Type `idclev33` then `idclev`
3. Look at the next map

**Comment by TwelveEyes** [comment]
This is proper behavior for map 33 to support the BFG Ed. Doom 2 IWAD. The BFG Ed. IWAD has an extra secret level (map 33: betray) which upon exiting will go to map 03. Any map (without UMAPINFO definitions) in the map 33 slot will have this same behavior as it is hard coded.

**Comment by fabiangreffrath** [comment]
Right. The MAP02->MAP33->MAP03 transition is canonical:
https://doomwiki.org/wiki/MAP33:_Betray_(Xbox_Doom_II)

**Comment by runlow** [comment]
I see. Could it not check though the md5sum or some other identifier for the IWAD and apply the MAP33 stuff only to the BFG Ed IWAD not the regular DOOM2.WAD?

Please correct me if I'm misunderstanding something. I don't understand why this has to apply to a different IWAD.

**Comment by fabiangreffrath** [comment]
There are already PWADs available that provide a MAP02->MAP33->MAP03 level transition based on the BFG Edition Doom2.wad, e.g. D2TWID.

**Comment by runlow** [comment]
@fabiangreffrath yes, and I'd assume - if wanting to be super correct about it - they (those PWADs) should require the BFG Edition IWAD. Using a normal DOOM.WAD for MAP33 sounds like a hack. Going >32 is also a hack. Going by the IWAD seems like a lesser evil to me but I'm not an expert or anything. Is my reasoning flawed? I'm happy to accept I'm wrong, just trying to understand. Apologies in advance.

**Comment by fabiangreffrath** [comment]
You mean like this?
```patch
--- a/prboom2/src/e6y.c
+++ b/prboom2/src/e6y.c
@@ -455,7 +455,7 @@ int G_GotoNextLevel(int *e, int *m)
                if (gamemode == commercial)
                {
                        epsd = 1;
-                       if (map >= 0 && map <= 32)
+                       if (map >= 0 && (map <= 31 || (bfgedition && map <= 32))
                                map = doom2_next[map];
                        else
                                map = gamemap + 1;

```

**Comment by runlow** [comment]
Yes. Or the other way around if you like - say if it's what I call "normal" Doom 2 (mine and I'm guessing of most of others' is Doom 2 v1.9 md5sum `25e1459ca71d321525f84628f45ca8cd`) then `map<= 31` and otherwise `map<=32`.

It feels a like a bodge but >32 maps are that tbh. Maybe @TwelveEyes has some insight?

**Comment by runlow** [comment]
I think I understand better now.

1. Going to `map03` is intended behaviour on map33 but for a different IWAD (not v1.9, the xbox version `a793ebcdd790afad4a1f39cc39a893bd`)
2. Most people will run it on v1.9 anyway me included because people are lazy.
3. If it's made proper-proper (according to my train of thought at least on what proper would mean - requiring xbox version DOOM2 and checking for IWAD type/edition/version/md5sum) it will not take players from map33 to map03 like they hoped it would on their `v1.9 Doom2` and they won't get xbox version just for this
4. it comes down to hack vs hack and which one wins. Checking for IWAD edition sounds more scalable to me but again - I don't have the same knowledge.

**Comment by kraflab** [comment]
Why is this a bug exactly? There is no canonical "next map" for a map above 32 except for map 3. There's no reason to assume they don't go to map 3. If a 33 should go to 34, that's a concern for umapinfo, we can't assume anything there so the only canonical example seems like the right choice.

**Comment by fabiangreffrath** [comment]
In general, the canonical next map for map x is x+1. There are exceptions like the 15->31->16 and the 15->31->32->16 route, and with the introduction of the BFG Edition the 02->33->03 route has become canonical as well. Note that the route through the Wolfenstein levels is based on the availability of these maps, and not on IWAD checksum, so they could be provided by a PWAD as well. Likewise, we should check for the availability of a MAP33 lump and adjust the route accordingly. Beyond that, there is no other canonical route available, though.

**Comment by runlow** [comment]
@kraflab 
> Why is this a bug exactly?

It's not - technically, now that I think about it - as it's not meant to go >32 or >33 to begin with on `v1.9` so it's hard to say what "should" happen - if anything at all!

> There is no canonical "next map" for a map above 32

Fully agreed and understood.

>  except for map 3.
> If a 33 should go to 34, that's a concern for umapinfo

Why is a different md5sum iwad "canonical" for an iwad with a different md5sum though? As I wrote I'm not an expert and happy to be corrected. This sounds a lot like the complevels.

Same thing could be argued for the current solution. If one wanted to emulate Doom2 Bfg/Xbox edition for v1.9 one could do it via UMAPINFO rather than requiring it in the sourceport or using the iwad it was meant for. No?

Going to the next level up just makes things simpler. Simpler is usually better (not always). `03` being next from `33` is not canonical at all for `Doom 2 v1.9`. :smiley: Maybe I'm wrong. Is this issue already treaded path? Was this or something similar addressed elsewhere before?

Each time bathesta releases a commercial DOOM2 variation with an extra map and extra route it's going to be adjusted in the source port as "canonical" behaviour even if the player doesn't own the iwad? :thinking:

@fabiangreffrath 
>Likewise, we should check for the availability of a MAP33 lump and adjust the route accordingly.

If I understand correctly - currently hitting PageDown on `map15` takes to `map31` but hitting PageDown on `map03` does not take to `map33` even if it's availabe.

**Comment by fabiangreffrath** [comment]
> If I understand correctly - currently hitting PageDown on `map15` takes to `map31` but hitting PageDown on `map03` does not take to `map33` even if it's availabe. 🤔

I guess you mean map02, which is the one with the secret exit to map33. 😉 This route only works if the IWAD has been identified as the BFG Edition IWAD (by presence of some characteristic lumps, no checksum ivolved). However, if you reached map33 by other means (i.e. IDCLEV33 or `-map 33`), it will always bring you back to map03.

**Comment by runlow** [comment]
>  guess you mean map02, which is the one with the secret exit to map33.

Yes, apologies. (corrected what I wrote) Haven't played BFG edition myself. I heard nasty things about BFG edition so stayed away from it.

> However, if you reached map33 by other means (i.e. IDCLEV33 or -map 33), it will always bring you back to map03.
>  only works if the IWAD has been identified as the BFG Edition IWAD (by presence of some characteristic lumps, no checksum ivolved)

I see. [This patch](https://github.com/coelckers/prboom-plus/issues/249#issuecomment-803966811) makes sense to me then. The "canonic" explanation - although I understand where it's coming from as it's nice to see sourceports evolving/converging decades after vanilla - "canonical" doesn't speak to me especially given: 
1. how badly devs gone about it in the xbox version based on what I've read, feels like masters levels
2. that it would **still work** if they used the right iwad
3. and if the wad creator doesn't care to make an UMAPINFO to make sure it works on all sourceports - then why should the application try to correct this? xbox devs didn't follow what's "canonic" themselves, why should this be a standard?
4. Unlike map 15 which continues the maps where they left off at 16 - map33 doesn't currently bring the player to somewhere they left off and implementing it is relatively complicated

Then again it doesn't affect me all that much as >32 is more like a trivia/novelty/interest/curiosity than something I encounter very often. I can be "attentive to detail" so the pedant part is is really inclined towards:

either:
* make all this canonic stuff kick in for the BFG edition only OR
* all expected map02/map33 "canonic" behaviours consistent for **all** DOOM2 iwads (based on some rule that takes into account map33 not existing OR
* remove all of the bfg stuff completely (except where it doesn't attack the integrity of "instantiation" in a broader sense

not:
* a mix of all of the above, an approach which usually is bug prone and should not be pushed as a standard even if it's emerging somewhere else it should not be endorsed going forwards - which the "canonic" argument is all about ("going forwards")

My 2cents from my partially uninformed POV, sorry for the essay. Feel free to call me out on bs.
