### ISSUE TITLE
PageDown on the last >32 map closes program (bug)

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#250]
It's not a huge deal but something I noticed.

**Expected:**
Typing `idclev` on `map48` (last bonus >32 map in [mayhem2020](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/mayhem20)) shows `map01` as next. Pressing PageDown warps the player to `map01`

**Observed:**
Typing `idclev` shows `map49` as next.
When pressing PageDown on `map48` prboom-plus closes with `W_GetNumForName: map49 not found` 

Tested on [mayhem2020](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/mayhem20)

Other than that it works well, big thanks.

**Comment by runlow** [comment]
Not sure if it's the best approach but maybe something like [checking](https://github.com/coelckers/prboom-plus/blob/master/prboom2/src/w_wad.h#L141) if a lump `MAP49` (or whichever) "marker" exists in the WAD archive(s) before showing/warping could be a way to verify that the next >32 map is going to work? Maybe I'm looking too deep into it.

Alternatively, maybe >32 is noman's land and it's ok for it to abruptly end. Maybe this doesn't need fixing if the solution was to be too complicated.

**Comment by fabiangreffrath** [comment]
> When pressing PageDown on `map48` prboom-plus closes with `W_GetNumForName: map49 not found`

This is exactly what would happen if you hit the exit switch on MAP48. And the latest request was to make the behavior of the "Next Level" key match that of the exit switch. So, what is it now? Once you cheated yourself into MAPxx with xx > 33 there is no canonical way back to MAP01.

What I can offer, though, is to only show a "next" map on IDCLEV if it actually exists.

**Comment by runlow** [comment]
Just reporting, take it easy. Not sure what's best for this myself and if this justifies a ticket. Just pointing out that it's there.

Haven't looked into how this works in detail yet - but is it not possible to deny warping with PageDown the same way as warping with `idclev` is denied if the map doesn't exist? Just asking, not saying it **has to** work that way.

**Comment by fabiangreffrath** [comment]
> Haven't looked into how this works in detail yet - but is it not possible to deny warping with PageDown the same way as warping with `idclev##` is denied if the map doesn't exist? 

I agree we should do that. It shouldn't be possible to accidently quit the game by attempting to warp to the next (non-existent) level.

**Comment by runlow** [comment]
The way it works now (e2570ae) is perfect, including the warning explaining why it's not going to the next level at `map48`!
Big thanks for that. Better overall imo.
Closing issue.
