### ISSUE TITLE
Exit action on >32 maps ends the game (feature)

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#252]
Hope this won't cause upheaval and it isn't too pedantic, but here is an idea.
(Can close the issue if you think it's trivial nitpicking/counterproductive/going too far, apologies in advance.)

**What if when:**
1. on a map >32
2. **and** finishing the level by triggering an exit line action
3. **and** there is no next map

...what if **then:**
The equivalent of pressing `F7` and `y` happens?
ie the game ends but without the application exiting?

Don't know if it's technically feasible but will see if I can figure it out.

(been testing this on [mayhem2020](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/mayhem20) if anyone wants to try it)

**Steps:**
1. Start prboom-plus with Doom 2 and mayhem2020
2. type `idclev48` then `tntem` `iddqd` `idclip`
3. go straight ahead from starting point until reaching a room that resembles the last doom 2 map (cubes, icon of sin)
4. there will be a pink eye switch opposite to Baphomet (turn around when you see Baphomet), press it
5. The level will end and `prboom-plus` will exit with the message `W_GetNumForName: map49 not found`

Starting the program again is not a big deal but ending the game would look less glitched and I think it's a better user experience. Again, I realise that this isn't a critical/very important thing.

**Alternatively:**
* it could assume you want `map01`
* it could assume you want the same level again
* endgame animation as if finishing `map30`

**Comment by fabiangreffrath** [comment]
While I like this idea in general, this would add even more to hard-coded behavior in the engine - whereas we want to encourage people to use UMAPINFO instead.

**Comment by runlow** [comment]
I see, that makes sense as it *would* actually give an incentive to use it. :thinking:

I'll see if I can come up with anything interesting with `UMAPINFO` for this.

I'm guessing it's not possible to load `UMAPINFO` separate to the wad from the command line for testing - similar to how you can append a separate  dehacked file regardless what the full command is ( `... -deh foobar.deh`).

I'm guessing it has to be a lump in a wad. The way I could go about it is to create a separate wad only containing `UMAPINFO` and load it with other pwads.

**Comment by fabiangreffrath** [comment]
You should be able to save it as a text file and load this as `-file umapinfo.lmp`.

**Comment by runlow** [comment]
That's pretty awesome/convenient. Didn't know you could do that.
This works in `zsh` by the way (changes the level name to "foobar"):
```zsh
TMPPREFIX=umapinfo. TMPSUFFIX=.lmp prboom-plus -warp 1 -file =(<<<'MAP MAP01{levelname="foobar"}')
```

**Comment by runlow** [comment]
This works for the exit action on `MAP48` bringing player to `MAP01` and it even works with PageDown, and is shown on the info displayed by `idclev`:
```zsh
TMPPREFIX=umapinfo.; TMPSUFFIX=.lmp; prboom-plus -iwad DOOM2.WAD \
 -file /tmp/zip/MAYhem20.wad =(<<<'MAP MAP48{next="MAP01"}')
 ```
 
Hopefully #255 is a step in right direction for encouraging UMAPINFO (it certainly helps me)

The reasoning makes sense to me and solutions provided are working. Closing issue I suppose. Thank you.
