### ISSUE TITLE
Intermission screen shows the original "next map" even if the game is ending (Doom 2, UMAPINFO)

### ISSUE THREAD

**Issue by Alper002** [coelckers/prboom-plus#263]
The issue is as simple as what the title says.
It's a tiny thing that's noticable in the few mapsets that have been released using UMAPINFO, like fork in the road.
It only happens in Doom 2, though. In Ultimate Doom the issue doesn't seem to happen.

Simple example PWAD for Doom 2 is inside the attached zip file: [DontShowNextMap.zip](https://github.com/coelckers/prboom-plus/files/6252278/DontShowNextMap.zip)
MAP01 has a normal exit to MAP02 and a secret exit to MAP03. The exits on MAP02 and MAP03 end the game, but the intermission screen erroneously shows "entering" as well as the name of what _would_ be the next map if progression wasn't messed with.

**Comment by fabiangreffrath** [comment]
Posting the contents of the UMAPINFO lump here for discussion:
```

map MAP01
{
	levelname = "The Start"
	next = "MAP02"
	nextsecret = "MAP03"
}

map MAP02
{
	levelname = "The second"
	intertext = "Did you see the mapname for MAP03?"
	endpic = "CREDIT"
}

map MAP03
{
	levelname = "The \"\"\"\"secret\"\"\"\""
	intertext = "Did you see the mapname for MAP04?"
	endpic = "CREDIT"
}
```

**Comment by fabiangreffrath** [comment]
I guess you'll have to set `nointermission = true` to entirely skip the intermission screen. I don't think it is possible to only show the "Finished" part but skip the "Entering" part.

**Comment by Alper002** [comment]
Why couldn't the intermission screen act like it seems to when beating MAP30 in vanilla? (I.E. it goes into the "entering" mode, but only shows the intermission background)
That'd be good enough for me.

**Comment by fabiangreffrath** [comment]
I'd like to have the engine skip the "Entering" part of the intermission screen if the `endpic` keyword is set for the current map.

**Comment by fabiangreffrath** [comment]
This should be it:
```patch
--- a/prboom2/src/wi_stuff.c
+++ b/prboom2/src/wi_stuff.c
@@ -1073,6 +1073,13 @@ void WI_drawShowNextLoc(void)
       WI_drawOnLnode(wbs->next, yah);
   }

+  if (gamemapinfo != NULL &&
+      gamemapinfo->endpic[0] &&
+      strcmp(gamemapinfo->endpic, "-") != 0)
+  {
+    return;
+  }
+
   if (gamemission == pack_nerve && singleplayer && wbs->last == 7)
     return; // MAP08 end game


```
