### ISSUE TITLE
Screen appears cut off in OpenGL mode

### ISSUE THREAD

**Issue by skyrain128** [coelckers/prboom-plus#266]
Running PrBoom+ on my father's laptop, When I set video mode to OpenGL, the screen appears cut off.
The laptop's screen scale set to 125%, and the resolution is 1920x1080.
Please make the game screen appears correctly on higher than 100%  scale.
![20210404_222902](https://user-images.githubusercontent.com/50762042/113510401-a8d30700-9595-11eb-9b30-403efb537150.jpg)

**Comment by fabiangreffrath** [comment]
Duplicate of https://github.com/coelckers/prboom-plus/issues/192
