### ISSUE TITLE
Music tracks assigned with UMAPINFO reset when a map resets.

### ISSUE THREAD

**Issue by TrilbyTrillion** [coelckers/prboom-plus#279]
Music tracks assigned with UMAPINFO reset when a map resets, such as with a death. 

map E4M1
{
   music = "D_E4M1"
}

This only happens with tracks reassigned with this method and not with the usual method of replacing existing tracks.  A minor glitch that doesn't break anything, but felt it was worth bringing attention to.

**Comment by fabiangreffrath** [comment]
Isn't this a duplicate of https://github.com/coelckers/prboom-plus/issues/102?

**Comment by TrilbyTrillion** [comment]
Oh, Sorry, I hadn't seen that. I had reported it over on the Doomworld forum and was told to submit an issue here.

**Comment by JadingTsunami** [comment]
I wasn't aware of the duplicate issue and mentioned that @TrilbyTrillion should file an issue here. Apologies for encouraging the dupe. It does look like the same issue and the fix from Crispy Doom seems appropriate to me.

**Comment by fabiangreffrath** [comment]
Could anyone provide a PR for this please?

**Comment by JadingTsunami** [comment]
Sure, as requested: #281
