### ISSUE TITLE
Add control to sound slice length 

### ISSUE THREAD

**Issue by RamonUnch** [coelckers/prboom-plus#283]
I was looking at the sound ﻿code and wondering where the sound slice length was and I realized that it is hard coded to `SAMPLECOUNT = 512` later adjusted as `audio﻿_buffers ﻿﻿= SAMPLECOUNT﻿﻿*﻿snd_samplerate﻿﻿﻿/11025` ﻿﻿﻿﻿﻿﻿﻿﻿like on the old prboom+. ﻿﻿﻿﻿﻿﻿﻿

This is a bit of a shame, because it corresponds ﻿to ~46ms sound delay and using directsound on my old machine i can decrease this value to SAMPLECOUNT=256 without ﻿experiencing sound distortions. ﻿﻿﻿

I changed the code for myself to let the user adjust it: under the `samplerate` option I just added the `samplecount` option in `m_misc.c`, then the `snd_samplecount` variable is ﻿added as `extern` in `i_sound.h` and is used instead of the `static SAMPLECOUNT` in the `i_sound.c` (being carefull not to modify the value of this new variable). ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿

Maybe `snd_slice_samplecount` would be a more appropriate name but is should be user adjustable to take in account the ability of different sound drivers.

**Comment by fabiangreffrath** [comment]
If you have the code available already, please file a PR. Thanks!

**Comment by RamonUnch** [comment]
I will submit the PR tonight.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/4c8d90c008725e0aaf53f057b8f44b136ddbfb2a
