### ISSUE TITLE
Vanilla fuzz effect in OpenGL renderer

### ISSUE THREAD

**Issue by skyrain128** [coelckers/prboom-plus#288]
Could you make an option to use vanilla fuzz effect in OpenGL renderer?

**Comment by JadingTsunami** [comment]
The exact vanilla fuzz effect can't realistically be replicated in OpenGL.

But a "shadow" style function is certainly doable. See below for a simple example of what that would look like, which I put together in the OpenGL renderer just now as an example.

![image](https://user-images.githubusercontent.com/7446082/115795660-2c0d9e80-a385-11eb-889a-f3bd60fbe2ee.png)

**Comment by fabiangreffrath** [comment]
Erm, wow!

**Comment by fabiangreffrath** [comment]
What exactly is the difference to the current implementation?

**Comment by JadingTsunami** [comment]
> What exactly is the difference to the current implementation?

Today, the GL renderer draws a darkened, transparent version of the original sprite when rendering a partially invisible sprite.

The implementation above discards the original sprite color data and instead draws a darkened "shadow" where the sprite would be.

This looks close to the vanilla renderer without the "fuzzing" effect. Recreating the vanilla fuzzing effect would require a new fragment shader and would affect performance. In fact I would recommend against it as I don't see an efficient way to recreate the effect as it is in vanilla without serious performance implications, especially with more than a few partially invisible sprites on screen at once.

Another option could be to require a custom fuzz texture and do an additional rendering pass using the stencil buffer. But this too would hit performance as we'd need to clear the stencil buffer each time, for each transparent sprite. Ideally we'd do one stencil pass but this is not possible if we have multiple sprites on-screen.

I think the above is a fair compromise for those who want a more vanilla look. But I welcome suggestions also.

**Comment by kraflab** [comment]
Definitely digging the shadow effect as a good middleground 👍

**Comment by fabiangreffrath** [comment]
Could you please post a PR for this?

**Comment by JadingTsunami** [comment]
Sure, I will spend some time on this soon.

**Comment by fabiangreffrath** [comment]
Although we still don't have the original Vanilla Doom fuzz effect on the OpenGL renderer, I think this has been sufficiently improved by https://github.com/coelckers/prboom-plus/commit/15431b3a9aac0800c72276aa8dabb13a8f12632e.
