### ISSUE TITLE
[Suggestion] Co-Op Spawn Parameter (not -solo-net)

### ISSUE THREAD

**Issue by DwarsYT** [coelckers/prboom-plus#290]
Basically, just the spawns of -solo-net without the limitations that come with that option like respawns, weapons staying, and certain cheats not working. I imagine it'd be kind of like the Unity port's version of UV-Plus, but without the mandatory fast monsters.

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/compare/3c541c7c37af9708adb49f6329aa9ba9cdacd844..8e5a940f54e854d35f28c46db734e59b5de311f2 if you want it
