### ISSUE TITLE
[Suggestion] Autoload folder

### ISSUE THREAD

**Issue by T-Will133** [coelckers/prboom-plus#291]
I think an autoload feature would be highly beneficial as some things like Widescreen Assets and mods will be easier to set up and load compared to launchers and batch files. Maybe have it be like Chocolate Doom with individual folders for each IWAD and an "All WADS" folder.

**Comment by kraflab** [comment]
You can set 2 wads and 2 dehs to autoload currently in the menu fyi (not saying autoloading a folder isn't also a good feature, but just in case you weren't aware).

**Comment by T-Will133** [comment]
That's definitely useful, but too simplistic. To give an example with the widescreen wads. I can only load the specific assets one at a time otherwise they'll be implemented wrong (like having the Doom 1 title screen when loading up Doom 2). Expanding upon it into IWAD and General autoload folders would allow better customizability. Plus, if possible, the folders could hold music files if one were to use say the SC55 Music Packs for the IWADs to further avoid weird things like D_RUNNIN playing in TNT's Map 01.

**Comment by fabiangreffrath** [comment]
I agree we should have this. I have been through adding this to Woof! just some days ago and it has been pretty straightforward porting over from Choco.
