### ISSUE TITLE
[REQUEST] UMAPINFO flag to disable prepending the map marker name to the automap name

### ISSUE THREAD

**Issue by maxmanium** [coelckers/prboom-plus#294]
Unsure how to phrase this, but basically I want to be able to give the appearance of the episodic format in Doom 2 (ExMy) through the already-existing options, but setting the level name in UMAPINFO appends the MAPxx: marker name in front. I don't want this to show up if I'm creating (the facade of) an episodic format. So, if I typed "E1M1: Hangar" for levelname in MAP01, it would show up on the automap as MAP01: E1M1: Hangar, which I don't want. Normally you can just change the entire string with a DEHACKED patch, but naturally this only addresses the first 32 maps, so there's no way around this if you want to exceed the original 32-map limit.

**Comment by JadingTsunami** [comment]
On the implementation side, this would be a new flag to _not_ prepend the map name.

Here is the relevant code that prepends the map name or number.

`hu_stuff.c:740`
```c
  if (gamemapinfo != NULL)
  {
	  s = gamemapinfo->mapname;
	  while (*s)
		  HUlib_addCharToTextLine(&w_title, *(s++));

	  HUlib_addCharToTextLine(&w_title, ':');
	  HUlib_addCharToTextLine(&w_title, ' ');
	  s = gamemapinfo->levelname;
	  if (!s) s = "Unnamed";
	  while (*s)
		  HUlib_addCharToTextLine(&w_title, *(s++));

  }
```

**Comment by fabiangreffrath** [comment]
Indeed, this behavior is currently hard-coded: 
https://github.com/coelckers/prboom-plus/blob/15431b3a9aac0800c72276aa8dabb13a8f12632e/prboom2/src/hu_stuff.c#L742

**Comment by fabiangreffrath** [comment]
Sorry, I didn't check for other responses first.

**Comment by JadingTsunami** [comment]
I suppose the big question here is: how do we make updates to the UMAPINFO specification now that multiple ports implement it?

Introducing a new field could break cross-port compatibility for UMAPINFO.

Introducing some new special characters into the map string could work and would only make it visually ugly if a port did not support this. So this is the backward-compatible option, albeit not as elegant.

E.g., beginning a level name string with '-' could skip printing the map name and ": " characters.

**Comment by Shadow-Hog** [comment]
You should probably ask printz for input on this. As I recall, contention over this very issue between him and Graf was part of why Eternity doesn't have an UMAPINFO implementation yet (at least, as far as I'm aware).

**Comment by fabiangreffrath** [comment]
> You should probably ask printz for input on this. As I recall, contention over this very issue between him and Graf was part of why Eternity doesn't have an UMAPINFO implementation yet (at least, as far as I'm aware).

Well then. @printz

**Comment by fabiangreffrath** [comment]
> E.g., beginning a level name string with '-' could skip printing the map name and ": " characters.

Or, we skip adding the map name if the level name does already contain a colon.

**Comment by rfomin** [comment]
> Well then. @Printz

Actually @ioan-chera :)

**Comment by ioan-chera** [comment]
I came to an agreement with @coelckers (via a private message), using a special option to disable the prefix (need to recall the name of that). I just didn't get to add UMAPINFO in EE because I got sidetracked by other stuff (now I'm busy with slopes, which are even more overdue, for example).

**Comment by fabiangreffrath** [comment]
> I came to an agreement with @coelckers (via a private message), using a special option to disable the prefix (need to recall the name of that). 

Yepp, that would help. :+1:

**Comment by ioan-chera** [comment]
I've looked in past messages and the field in question is `label`, which you can set to any string you like. I assume that if you want to remove it, you'd have set it either to "" or to `clear`.

**Comment by rfomin** [comment]
> Introducing a new field could break cross-port compatibility for UMAPINFO.

I think we could safely add `label` because UMAPINFO parsers should ignore unknown keywords. I've tested PrBoom, GZDoom, Woof, Doom Retro - they all work this way.

**Comment by fabiangreffrath** [comment]
We should probably bump the spec to Rev 2 if we introduce this.

**Comment by fabiangreffrath** [comment]
It seems not even GZDoom's UMAPINFO parser knows about the `label` keyword.

**Comment by ioan-chera** [comment]
Yeah because @coelckers also was a bit busy when we talked about it, just like me, so he probably went on with other stuff. He really suggested in the Doomworld thread where I was a bit unsure (and got into the unhappy situation) about the `label` keyword as a "compromise" to allow different start names. When I resume UMAPINFO work on EE, I _will_ add the keyword, because it's useful, regardless of what others do. But I guess I'm not developing PrBoom+, so i have more freedom do add stuff, it's not the cornerstone of Doom metrics like PrBoom+.

**Comment by JadingTsunami** [comment]
If `label` is going to be the official field, then an implementation like this would be fairly harmless:

1. Default to existing behavior.
2. `label = clear` removes the prefix, showing only `levelname`.
3. `label = "string"` uses the provided prefix.

For ports that don't implement `label`, the automap name would appear with an undesired map identifier prefix but would otherwise not break anything.

In fact all we really need is `label = clear` but I don't see any harm in an explicit label field either.

**Comment by fabiangreffrath** [comment]
So, the `label` field would only replace the `mapname` part but not affect the `levelname` field?

**Comment by fabiangreffrath** [comment]
And does it make a difference if we set `label = clear` or `label = ""`? To me it shouldn't.

**Comment by JadingTsunami** [comment]
> So, the `label` field would only replace the `mapname` part but not affect the `levelname` field?

Right. This is why I meant we could get away with just a `clear` command to erase the prefix. But an explicit `label` field is fine too.

> And does it make a difference if we set label = clear or label = ""? To me it shouldn't.

I think this shouldn't matter in the scheme; both would be equivalent. Having a `clear` option is just consistent with other fields like `intertext`.
