### ISSUE TITLE
Ouch Face fix for all complevels and SSG Flash fix

### ISSUE THREAD

**Issue by hackneyed-one** [coelckers/prboom-plus#295]
Since the Ouch Face and SSG Flash bugs have been fixed in many other ports (Crispy, Woof, Eternity etc). I'm requesting the Ouch Face bug be decoupled from complevels so that it can be displayed in Vanilla, Boom, MBF etc and be toggled back on using the comp_ouchface setting for people who want to turn the bug back on as it does for the higher prboom complevels. 

Also a fix for the erroneous frame of muzzle flash when firing the SSG. Again in line with Crispy, Woof, Eternity etc.

As a small aside or additional request maybe the SSG fix could be a toggle too? Maybe just hidden in the config as SSG_flash_glitch 0/1 or something. I understand if you don't want to add a toggle and frankly that makes sense. It is a small purely cosmetic bug fix that is standard in many contemporary ports. Fix it and forget it like the rest. However I was a little disappointed that transparency can no longer be coupled to complevels and must be turned on or off for all complevels since I liked the nostalgia of not having transparency in Vanilla and having transparency in Boom. 

Even though I think I'll leave transparency on for all complevels because it is a nice addition it IS still possible to restore the Vanilla look with a menu setting or multiple config files. So maybe SSG_flash_glitch 0/1 should have a config too. I probably wouldn't turn it back on but something to consider for the purists.

Thanks!

**Comment by fabiangreffrath** [comment]
> I'm requesting the Ouch Face bug be decoupled from complevels so that it can be displayed in Vanilla, Boom, MBF etc and be toggled back on using the comp_ouchface setting for people who want to turn the bug back on as it does for the higher prboom complevels.

Sure, we have done the same for the translucency setting before.

> Also a fix for the erroneous frame of muzzle flash when firing the SSG. Again in line with Crispy, Woof, Eternity etc.

The fix was introduced in MBF, so it should probably get unconditionally applied to its complevel.

> However I was a little disappointed that transparency can no longer be coupled to complevels and must be turned on or off for all complevels since I liked the nostalgia of not having transparency in Vanilla and having transparency in Boom.

Seriously?! This was requested using the exact same reasoning that you apply to the Ouch Face fix here ("it's purely cosmetic, fixed in all other ports, there is already a switch for it"). You just cannot do it right it seems.

As a rule of thumb, I think if the player is already given a choice for a fix in the form of a menu switch, then this choice should be respected regardless of compatibility level - as long as the fix doesn't break compatibility of course.

**Comment by hackneyed-one** [comment]
> Seriously?! This was requested using the exact same reasoning that you apply to the Ouch Face fix here ("it's purely cosmetic, fixed in all other ports, there is already a switch for it"). You just cannot do it right it seems.
> 
> As a rule of thumb, I think if the player is already given a choice for a fix in the form of a menu switch, then this choice should be respected regardless of compatibility level - as long as the fix doesn't break compatibility of course.

Ha ha yes seriously and I am aware of the irony. I absolutely agree a user controlled menu setting is the right call on transparency and the Ouch Face. "Vanilla" is not lost it's just a little more effort for a few users who might want it. I've read and agree that you want to be thoughtful and conservative with the non-Crispy ports you work on.

That was my reason for discussing a possible SSG_flash_glitch config setting. It should be fixed for all complevels because slime trails, transparency, ouch face etc are all getting fixed and rightly so. It's just too minor to put in the menu but more "Vanilla" will be lost from PrBoom-Plus if there is no option at all. PrBoom has historically been about preservation and an improved user experience. So please fix it and maybe have an option?

Thanks for listening and thanks for all the ports and maintenance you are doing. I really appreciate it!

**Comment by fabiangreffrath** [comment]
> That was my reason for discussing a possible SSG_flash_glitch config setting. It should be fixed for all complevels because wall wiggle, transparency, ouch face etc are all fixed here or in other ports and rightly so. It's just too minor to put in the menu but more "Vanilla" will be lost from PrBoom-Plus if there is no option at all. PrBoom has historically been about preservation and an improved user experience. So please fix it and maybe have an option?

Sorry, but there won't be a menu switch for this. There are already too many and this issue is too minor. Also, contrary to line wobble and ouch face, this can be fixed by a simple DEHACKED patch and many projects even already include this fix.

**Comment by hackneyed-one** [comment]
I'm sorry I never ment to get so side tracked on this one little issue. I agree I never said it should have a menu entry.

I said I think it should be fixed (like contemporary ports) and maybe have a line in the config file for historical preservation. So thank you for taking the time to discuss and share some information on the glitch. 

Anyway, yeah if this glitch is important to some obscure mod the dehacked could be tweaked or they could use the bless-ed Chocolate Doom and be done. Even an option for this bug in the cfg is just dead weight in a modern PrBoom-Plus.

I tend to agree 100% with your well thought out and reasoned commits even if I don't 100% like it. ha ha ;)
