### ISSUE TITLE
Undefined References

### ISSUE THREAD

**Issue by GarethH96** [coelckers/prboom-plus#3]
When compiling I get this:

> r_demo.o: In function `G_ReadDemoFooter':
/home/gareth/oth/prg/prboom-plus/prboom2/src/r_demo.c:1078: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
g_game.o: In function `G_LookupMapinfo':
/home/gareth/oth/prg/prboom-plus/prboom2/src/g_game.c:2671: undefined reference to `Maps'
/home/gareth/oth/prg/prboom-plus/prboom2/src/g_game.c:2671: undefined reference to `Maps'
g_game.o: In function `G_LookupMapinfoByName':
/home/gareth/oth/prg/prboom-plus/prboom2/src/g_game.c:2684: undefined reference to `Maps'
/home/gareth/oth/prg/prboom-plus/prboom2/src/g_game.c:2684: undefined reference to `Maps'
d_main.o: In function `D_DoomMainSetup':
/home/gareth/oth/prg/prboom-plus/prboom2/src/d_main.c:1840: undefined reference to `ParseUMapInfo'
f_finale.o: In function `F_Drawer':
/home/gareth/oth/prg/prboom-plus/prboom2/src/f_finale.c:663: undefined reference to `FMI_Drawer'
f_finale.o: In function `F_StartFinale':
/home/gareth/oth/prg/prboom-plus/prboom2/src/f_finale.c:90: undefined reference to `FMI_StartFinale'
f_finale.o: In function `F_Ticker':
/home/gareth/oth/prg/prboom-plus/prboom2/src/f_finale.c:233: undefined reference to `FMI_Ticker'
collect2: error: ld returned 1 exit status
Makefile:552: recipe for target 'prboom-plus' failed
make[3]: *** [prboom-plus] Error 1
make[3]: Leaving directory '/home/gareth/oth/prg/prboom-plus/prboom2/src'
Makefile:684: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/gareth/oth/prg/prboom-plus/prboom2/src'
Makefile:451: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/gareth/oth/prg/prboom-plus/prboom2'
Makefile:369: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by coelckers** [comment]
Someone who can test needs to fix the Linux project.

**Comment by coelckers** [comment]
I got a fix submitted yesterday.
