### ISSUE TITLE
Sounds are cutting off other sounds when using -complevel 2, 3, and 4

### ISSUE THREAD

**Issue by Terraformer9x** [coelckers/prboom-plus#302]
I first noticed this with complevel 2. The most prominent example of it occurring is whenever you use the pistol against a zombieman and the sound of the pistol shot that kills the zombieman is sometimes cut off by their death scream. It occurs most often when you use the pistol against them at close range.

I tested to see if this was just hard-coded behavior with sounds using complevel 2 by seeing if the same thing happens in Chocolate Doom but it didn't occur there. I then checked to see if it also occurred on other complevels and it did for 3 and 4. However the bug didn't seem to happen on complevels 9 and 11.

_(Just to clarify, this is not related to how sounds are abruptly stopped when the actor playing them are deleted.)_

**Comment by JadingTsunami** [comment]
> I'm not _too_ savvy with delving into source codes. However, I'm thinking what's causing it mainly is that when two sounds are played at the same time, instead of assigning them to separate channels, they both get assigned the same channel which causes one sound to cut off the other.

Right, I think the point is the behavior is intentional as part of retaining Doom's original sound quirks. So the solution would be to decouple it from complevels.

**Comment by Terraformer9x** [comment]
> 
> 
> > I'm not _too_ savvy with delving into source codes. However, I'm thinking what's causing it mainly is that when two sounds are played at the same time, instead of assigning them to separate channels, they both get assigned the same channel which causes one sound to cut off the other.
> 
> Right, I think the point is the behavior is intentional as part of retaining Doom's original sound quirks. So the solution would be to decouple it from complevels.

I know keeping the behavior is intentional, however I think emulation of the quirks in PrBooom+ are inaccurate, mostly when it comes to how weapon sounds are seemingly muted by enemy sounds, mainly zombies.

I've recorded a quick demo in Doom 2 using Chocolate Doom to showcase the inaccuracy. Play the demo in Chocolate or Vanilla Doom and then play it in PrBoom+ and compare to how the zombieman sounds affect the pistol sounds in both ports.

[Demo](https://www.dropbox.com/s/64f6ys1kjq9kha5/SoundTest.lmp)
