### ISSUE TITLE
A_Refire does not switch weapons at all when ammo is zero with boom_autoswitch set to 0

### ISSUE THREAD

**Issue by maxmanium** [coelckers/prboom-plus#303]
To reproduce, hold fire with the pistol until ammo is depleted -- it stays in its WeaponReady state without bobbing until you let go of the fire button.

**Comment by fabiangreffrath** [comment]
Hm, `boom_autoswitch` again? Indeed, it seems the whole `!demo_compatibility` code path is disabled if `boom_autoswitch == 0`:
https://github.com/coelckers/prboom-plus/blob/635be4806561ff3fcf46ad948e60e813dda8905c/prboom2/src/g_game.c#L581-L583

To restore the prvious behaviour, it should probably read `(!boom_autoswitch || (boom_autoswitch && !done_autoswitch))` which condenses to `(!boom_autoswitch || !done_autoswitch)`, right?

```patch
--- a/prboom2/src/g_game.c
+++ b/prboom2/src/g_game.c
@@ -579,7 +579,7 @@ void G_BuildTiccmd(ticcmd_t* cmd)
 
   // Make Boom insert only a single weapon change command on autoswitch.
   if ((!demo_compatibility && players[consoleplayer].attackdown && // killough
-       !P_CheckAmmo(&players[consoleplayer]) && !done_autoswitch && boom_autoswitch) ||
+       !P_CheckAmmo(&players[consoleplayer]) && (!boom_autoswitch || !done_autoswitch)) ||
        gamekeydown[key_weapontoggle])
   {
     newweapon = P_SwitchWeapon(&players[consoleplayer]);           // phares
```
