### ISSUE TITLE
Please make the software renderer more optimized

### ISSUE THREAD

**Issue by skyrain128** [coelckers/prboom-plus#310]
I never seen software renderer over 130FPS.
When using OpenGL mode, the framerate is over 4700+ FPS, but in software mode, the framerate doesn't over 130FPS....
Resolution is 2560x1440.

**Comment by JuanchoES** [comment]
I have heard that in some older versions of prboom+ software rendering was much better, but nobody knows why.

**Comment by maxmanium** [comment]
I've noticed this too -- on my weaker laptop, the software renderer gets 50-55 fps on Entryway. Enabling exclusive fullscreen does give a slight boost but not much (~10 fps).

**Comment by JadingTsunami** [comment]
Dupe of #265

**Comment by fabiangreffrath** [comment]
> Dupe of #265
