### ISSUE TITLE
Intermission text replacements from DEHACKED lumps do not display if empty lines are present in [STRINGS], but display correctly if loaded from standalone deh file

### ISSUE THREAD

**Issue by revragu** [coelckers/prboom-plus#312]
Vesrsion: PrBoom-Plus 2.6um
OS: Windows 10 Pro 20H2

Expected functionality: DEHACKED lumps and standalone deh files should be interpreted the same way.
Actual functionality: prboom+ does not seem to fully process the DEHACKED lump's strings section if there are empty lines present between strings, but it processes all of the strings regardless of whether there are empty lines if loaded from a deh file.

Replicating the issue:
In the files I attached, h2h_fix.wad contains a DEHACKED lump with C*TEXT intermission replacement strings.
If I run prboom+ with the attached wads using the following flags:
`prboom-plus.exe -file "h2h-xmas.wad" "h2h_fix.wad"`
Warp to MAP06, finish the map, and the standard Doom2 intermissions play. If you go to the automap, you can see that the map title replacement strings are being read from the DEHACKED lump and displayed correctly.

If I run prboom+ with
`prboom-plus.exe -file "h2h-xmas.wad" -deh "h2h-xmas.deh"`
Warp to MAP06, finish the map, and the replacement intermission text is displayed correctly. The formatting of the DEHACKED lump in h2h_fix.wad and the formatting of the standalone h2h-xmas.deh are identical.

I removed the empty lines in the [STRINGS] section of the DEHACKED lump, and if I run prboom+ with
`prboom-plus.exe -file "h2h-xmas.wad" -file "h2h_fix_dehacked_fixed.wad"`
The intermission text is taken from the DEHACKED lump, as expected.

I've also included my prboom-plus.cfg file

Extremely minor issue, but something unusual I came across, so I thought I would report it.

[deh_ctext_replacement.zip](https://github.com/coelckers/prboom-plus/files/6525764/deh_ctext_replacement.zip)

**Comment by fabiangreffrath** [comment]
Indeed, it appears that the DEH parser is only able to roll back to the start of a line following a blank line and re-process it with the last valid block code handler if the DEH patch comes from a file.
