### ISSUE TITLE
"Enable fist/chainsaw and sg/ssg toggle" has no effect

### ISSUE THREAD

**Issue by maxmanium** [coelckers/prboom-plus#316]
See title. When disabled, 1 and 3 still toggle between the two weapons respectively.

**Comment by fabiangreffrath** [comment]
Yes, indeed! It seems the corresponding check has been unconditionally enabled. Compare this line with the same one from MBF:

https://github.com/coelckers/prboom-plus/blob/5c19818982d4a7a895e904222d49250b9ad2680b/prboom2/src/g_game.c#L621

https://github.com/fabiangreffrath/woof/blob/96cc3704893e52fc4b49cc63f5dfee1a7a73347c/Source/g_game.c#L494

According to "git blame" it has been so like this since the initial revision from some 21 years ago.

**Comment by fabiangreffrath** [comment]
Are we supposed to fix this back to the intended behavior as per MBF? @kraflab

**Comment by kraflab** [comment]
I'd just as well remove the option entirely I guess. Is there a benefit to toggling it off?

**Comment by maxmanium** [comment]
> 
> 
> I'd just as well remove the option entirely I guess. Is there a benefit to toggling it off?

I know it's not a popular option but it's nice to have it available -- mostly so you don't have to take longer to switch to the berserk fist when you have the chainsaw. It can also serve as a QOL improvement if the chainsaw is replaced with DEHACKED so it's not unfittingly before the fist.

**Comment by kraflab** [comment]
Can't you pick the first thing to select using the weapon preferences configuration? I'm not entirely familiar with how that feature works - if it doesn't work, then I think adding an option like "prefer berserk fist over chainsaw" as an option would be more direct.

**Comment by maxmanium** [comment]
> 
> 
> Can't you pick the first thing to select using the weapon preferences configuration? I'm not entirely familiar with how that feature works - if it doesn't work, then I think adding an option like "prefer berserk fist over chainsaw" would be more explicit for this need.

That's for when the game selects a new weapon to use when you run out of ammo.

**Comment by kraflab** [comment]
```c
          // only select chainsaw from '1' if it's owned, it's
          // not already in use, and the player prefers it or
          // the fist is already in use, or the player does not
          // have the berserker strength.

          if (newweapon==wp_fist && player->weaponowned[wp_chainsaw] &&
              player->readyweapon!=wp_chainsaw &&
              (player->readyweapon==wp_fist ||
               !player->powers[pw_strength] ||
               P_WeaponPreferred(wp_chainsaw, wp_fist)))
            newweapon = wp_chainsaw;
```

**Comment by kraflab** [comment]
Seems like this already accounts for the behaviour you want 🤔 
Is it broken or am I misreading it?

**Comment by maxmanium** [comment]
> 
> 
> Seems like this already accounts for the behaviour you want 🤔
> Is it broken or am I misreading it?

The option in question is broken, yes. I'm not talking about when you run out of ammo, I'm talking about switching to it on your own volition.

**Comment by kraflab** [comment]
I just tested this. If you put fist above chainsaw in your preference hierarchy, then pressing `1` while you have berserk power switches to the fist. If you don't have berserk, it switches to chainsaw.

**Comment by maxmanium** [comment]
> 
> 
> I just tested this. If you put fist above chainsaw in your preference hierarchy, then pressing `1` while you have berserk power switches to the fist. If you don't have berserk, it switches to chainsaw.

I was not aware of this. Thanks.

**Comment by fabiangreffrath** [comment]
So, can we just remove this switch from the weapons menu?

**Comment by JadingTsunami** [comment]
> So, can we just remove this switch from the weapons menu?

That'd be my vote. It doesn't work and weapon priority seems like a more comprehensive solution anyway.

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/87508fde62051871c51f2ed810cc60feb08b91cf

**Comment by fabiangreffrath** [comment]
Applied, thanks!

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/751badbd0738d9521ca530f77f1bc053370536d7
