### ISSUE TITLE
Screen melt to title screen has an error

### ISSUE THREAD

**Issue by Some1NamedNate** [coelckers/prboom-plus#318]
At the end of each title screen demo, it usually melts to credits of the engine and IWAD, and then the title screen. In this case, however, after the end of a demo, the screen melted to the IWAD credits, and then after the melt completed, went to the title screen.

**Comment by fabiangreffrath** [comment]
The order of the title/demo/credits sequence is defined here:
https://github.com/coelckers/prboom-plus/blob/1634029cb15d485063675d290d8bea3b9c18ed5b/prboom2/src/d_main.c#L606

The third and fourth elements of each array correspond to the "commercial" and "retail" gamemodes, respectively, i.e. Doom 2 and Ultimate Doom.

Looks like everything is going as it's supposed to be, judging from your report.

**Comment by JadingTsunami** [comment]
Right, to my knowledge this is not a bug and is indeed intended behavior.

**Comment by Some1NamedNate** [comment]
This was actually after the third demo. When that ended it was supposedly going to screen wipe to TITLEPIC. But it wiped to CREDIT before changing to TITLEPIC. 

https://user-images.githubusercontent.com/33171016/120088963-e3938000-c0aa-11eb-86ef-ed388750187b.mp4

**Comment by Some1NamedNate** [comment]
This was actually after the third demo. When that ended it was supposedly going to screen wipe to TITLEPIC. But it wiped to CREDIT before changing to TITLEPIC. 

https://user-images.githubusercontent.com/33171016/120088963-e3938000-c0aa-11eb-86ef-ed388750187b.mp4

**Comment by fabiangreffrath** [comment]
That video makes it clear, thank you! It tries to play DEMO4, but doesn't find the corresponding lump. Though this doesn't cause the loop to crash, it prevents the TITLEPIC patch from being drawn before the wipe screen, so it wipes to the last "wipe target" screen before actually drawing TITLEPIC.

**Comment by Some1NamedNate** [comment]
Thank you! 😊
