### ISSUE TITLE
16:10 resolution forced to 4:3

### ISSUE THREAD

**Issue by kraflab** [coelckers/prboom-plus#320]
Hello,

Shepardus reported this issue with the latest source (noticed in the diff between dsda-doom v0.18 and v0.19, but it affects pr+ as well).

When selecting 16:10 resolution on windows, pr+ forces the rendering to 4:3 with black bars on the sides. It affects both windowed and fullscreen mode. Setting auto aspect ratio versus 16:10 didn't help. Exclusive software fullscreen didn't help. The issue is in the software render but not in opengl. I wasn't able to reproduce this myself.

There aren't a lot of commits that could be related, so hopefully it's not hard to pinpoint.

**Comment by kraflab** [comment]
Shepardus found this one: https://github.com/coelckers/prboom-plus/commit/7aca841928eaa1d415a545d05c939dffb5b770b0

Guessing we need something like "and resolution is low" 😅

**Comment by fabiangreffrath** [comment]
Hm, do you know which exact resolution Shepardus tried to set? Because, I am not sure if we should apply aspect ratio correction to e.g. 960x600 or not.

**Comment by kraflab** [comment]
960x600 and 1920x1200 were both tried and failed.
