### ISSUE TITLE
Pain palette abnormalities on 32-bit renderer

### ISSUE THREAD

**Issue by DwarsYT** [coelckers/prboom-plus#323]
On any WAD with a 4:3 HUD or vanilla, this phenomenon seems to happen regarding the pain palette and the sides of the status bar in the 32-bit renderer. The 8-bit renderer works fine, and it should also be mentioned that both renderers work properly with widescreen assets.
![image](https://user-images.githubusercontent.com/54383651/120483425-15913480-c380-11eb-8e46-02725aafe8e5.png)

**Comment by fabiangreffrath** [comment]
Yes, that's because while the whole status bar is redrawn upon palette changes in hicolor modes, the bezel indeed isn't:
https://github.com/coelckers/prboom-plus/blob/56d2aa2ecd3deaf345896b0923354546886d8e74/prboom2/src/st_stuff.c#L826

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/8d21402df2ee202e30be9d3dc3f316ea40e7678b
