### ISSUE TITLE
OpenGL status bar palette

### ISSUE THREAD

**Issue by kraflab** [coelckers/prboom-plus#327]
The status bar / hud in opengl don't respect palette changes (pain, radsuit, etc).

I fixed this here:

https://github.com/kraflab/dsda-doom/commit/bb770244fb972c8d3cdd6ff51d52b919fa14a516

But...I don't really understand opengl. It works and I haven't seen an issue but idk if there are possible side effects related to rearranging this code. So, maybe an expert can take a look and see if it makes sense before we merge this in pr+? 😅 

Or I will just update this after the next release of dsda-doom if anyone reported an issue :^)

**Comment by fabiangreffrath** [comment]
Calling @JadingTsunami to the rescue!

**Comment by DwarsYT** [comment]
I'm curious if this 'feature' should be a toggleable option in the Status Bar/HUD settings for all rendering modes if possible. I know that a few people actually like that palette changes aren't respected by the status bar.

**Comment by JadingTsunami** [comment]
Hey! This looks pretty harmless to me. It just reorders the palette effect overdraw after both the scene and status bar are rendered. Probably I am saying obvious things. :)

As long as overdraw is called prior to `I_FinishUpdate()` (which it is) I don't foresee any problems.
