### ISSUE TITLE
can you add back the old options menu like in prboom-plus 2.5.1.3

### ISSUE THREAD

**Issue by prboompluskid** [coelckers/prboom-plus#342]
![image](https://user-images.githubusercontent.com/86818475/124223752-8cac1b00-db2e-11eb-879e-72891a902cb4.png)

**Comment by prboompluskid** [comment]
and add the low detail mode option

**Comment by fabiangreffrath** [comment]
In the screenshot you are showing, the menu items are rendered from graphics (i.e. this is not a font rendering!) that are composed of glyphs taken from IWAD assets - which are id software's property are were thus removed. If you want your options menu displayed this way, you'll need to provide a PWAD which contains the graphics lumps:
https://github.com/coelckers/prboom-plus/blob/d935d883e338b86cb0087a92cc0c8eb747027544/prboom2/src/m_menu.c#L1128

Also, AFAICT PrBoom+ never had a low detail mode.
