### ISSUE TITLE
Microfreezes in gl when new enemy appears

### ISSUE THREAD

**Issue by lafoxxx92** [coelckers/prboom-plus#351]

**Comment by JadingTsunami** [comment]
This is way too vague for me to look into - can you please post more information about exactly what you're seeing? At a minimum:

1. What you did
2. What you expected to happen
3. What happened instead

Your system stats and any loaded WADs or DeHackEd patches would be helpful as well.

**Comment by lafoxxx92** [comment]
sorry -- here's the proper description
1 get windows x64-based pc with similar config: x470 chipset, zen+ cpu, gtx1060 gpu, 2x8gb ddr4 sdram, creative sb0880
2 unpack [prboom-plus.zip](https://github.com/coelckers/prboom-plus/files/6837074/prboom-plus.zip) to game dir
3 drag and drop bf_thud.wad to exe
4 start new game
5 idclev03
6 shoot some generic enemies at starting position, then get to arachnotron on right
actual: stuttering when enemy provoked/killed
expected: no stuttering

might be system-specific?

**Comment by JadingTsunami** [comment]
Ok, thanks for the detail. I'm not able to reproduce this either. If you are able to reproduce it reliably, please let me know. Also if you can reproduce it, if you can check whether the issue is exclusive to OpenGL rendering or happens in SW rendering modes also that would be helpful.

**Comment by lafoxxx92** [comment]
Closed for now because seems system-specific so far
