### ISSUE TITLE
Incorrect gamemode when respawning from a savegame while a demo is playing.

### ISSUE THREAD

**Issue by SharlLegreg** [coelckers/prboom-plus#352]
Tested on latest SourceForge release ( 2.5.1.5 ) and Github's  2.6um.

Ways to replicate :

1. Load a custom wad with a deathmatch demo inside ( Alien Vendetta DEMO1 is a deathmatch game )
2. Start a new game 
3. Save the game
4. End the game by the "End Game" Option or closing the program
5. Launch the game and wait for a deathmatch demo to play
6. Load the save game. Now you can notice the status bar has a Frag counter.
7. Kill yourself
8. Respawn. Now you will respawn on a deathmatch spawn with all 6 keys

----------------------------------------------------------------------------------------------------------------------------------------------

Some interesting notes 

Chocolate Doom ( and by extension vanilla doom ) doesn't allow you to load a savegame while a netgame demo is playing. This might be because Vanilla Doom treats demos as an actual game. Crispy Doom doesn't have this bug; you can load a savegame while a netgame demo is playing and the loaded game will have no issues at all.

I will attach a video when the compression is done. No way I'm sending 70MB of raw 1-minute footage.

**Comment by SharlLegreg** [comment]
Extra note: Start a new game before the demo starts.

**Comment by SharlLegreg** [comment]
https://user-images.githubusercontent.com/63714563/126348462-4725d226-0940-4b1b-9d55-61e08ca4cee1.mp4

**Comment by fabiangreffrath** [comment]
@rfomin Could you probably file a PR containing the same fix as for Woof here?
