### ISSUE TITLE
Options menu uses small font

### ISSUE THREAD

**Issue by lafoxxx92** [coelckers/prboom-plus#355]
Why on earth would you change it? 
Or at least please make the distance between the entries smaller, and without skull, like in options submenus (Quake-style).
This kells the eitire feel of the port, whiich used to be as close to vanill aas possible in all aspects, such as this one.

**Comment by JadingTsunami** [comment]
Dupe of #342

**Comment by lafoxxx92** [comment]
[Reopen]
Or at least please make the distance between the entries smaller, and without skull, like in options submenus (Quake-style).
Possible?

**Comment by fabiangreffrath** [comment]
The HUD font entries are just placeholders for actual menu graphics provided by a PWAD, so they are drawn at the same vertical coordinates. Technically, the Options menu is different from its submenus and thus gets a skull and the usual menu entry spacing. And, honestly, I see no compelling reason to change that.

**Comment by lafoxxx92** [comment]
Ok, I'll just use the prboom-plus.wad from version 2.5.13, seems to work fine so far.

**Comment by lafoxxx92** [comment]
Workaround exists
Use earlier prboom-plus.wad
