### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by lafoxxx92** [coelckers/prboom-plus#357]
Cannot use sounds not in DOOM WAVE format, or not 8 Bit.
Distant sounds (such as dsfirxpl) stop abruptly before the sound file has finished playing.
Sound not interpolated ("crispy" when output rate is higher than sound file samplerate)

General question:
Is this expected (you use same sound code as in DOOM2.EXE – that's fine)?
Any plans on improving sound code (add hrtf, add linear interpolation, add possibility to play more sounds ata a time like in PSX DOOM)?

**Comment by fabiangreffrath** [comment]
The current code is able to read RIFF/WAV files in 8-bit and 16-bit formats.

**Comment by fabiangreffrath** [comment]
RIFF/WAV files in 8-bit and 16-bit formats are supported by the 2.6.1um release.
