### ISSUE TITLE
Some sprites still pixelated after setting only Sprites to be filtered

### ISSUE THREAD

**Issue by lafoxxx92** [coelckers/prboom-plus#358]
Steps:
Adjust the game so that textures/flats are unfiltered, while gun/monster sprites are smoothed
See what happens

Actual:
Some monster states still pixelated

Expected:
All sprites linear, all textures/flats pixelated

More precise steps will be added later

**Comment by fabiangreffrath** [comment]
This really needs more information...

**Comment by JadingTsunami** [comment]
Right. I tried to reproduce this myself but I don't see it. Screenshots and exact settings would be helpful.

**Comment by lafoxxx92** [comment]
Unable to reproduce anymore. Must be system-specific or resolved in **current** version.
