### ISSUE TITLE
[Feature] show messages over STBAR instead of top left corner (like in PSX DOOM)

### ISSUE THREAD

**Issue by lafoxxx92** [coelckers/prboom-plus#371]

**Comment by fabiangreffrath** [comment]
Why should we?

**Comment by lafoxxx92** [comment]
For accessibility. 
All important information is concentrated in the lower part of the screen, so moving your eyes on the top each time might be 

Just my opinion though – wontfix if disagree.

**Comment by fabiangreffrath** [comment]
This will clash with any of the more advanced HUD.
