### ISSUE TITLE
OpenGL Backfill

### ISSUE THREAD

**Issue by kraflab** [coelckers/prboom-plus#373]
Previously we fixed opengl status bar palette here: https://github.com/coelckers/prboom-plus/commit/87fef9d2aa3d4eea1625f86ce9d33cac5cdce832

This had a side effect where the backfill would cover the game window in opengl after pressing the minus key (because we called R_FillBackScreen after drawing the game window).

Looking into this, I started to ask myself why we need to call R_FillBackScreen again at all in opengl. This function is always called before drawing the game window, and the palette is applied to the whole screen anyway. But, just removing the redundant call to this method didn't fix the palette. If you remove the call in ST_refreshBackground it will cause the alpha effect to stack on the sides, as if that party of the screen is not being refreshed at all (see image below). If the bar is redrawn in its entirety every frame (as is the case in opengl), how is it possible that part of the screen is not refreshed?

Eventually I figured out that it _is_ refreshing the screen, but the color settings from the previous frame were leaking into the next one. So it would draw with the last frame's alpha already applied, and then apply another layer on top, causing the stacking effect.

I fixed this in dsda-doom here:
https://github.com/kraflab/dsda-doom/commit/8ab2949eeb1d2db4b2bb4fd3bef8f1a189a8e1cc (dsda-doom has no 15/16 bit mode, so keep that in mind for the conditional)

I assume this is fine, but @JadingTsunami should confirm 😃 

![doom23](https://user-images.githubusercontent.com/25529060/127741082-1189300a-556d-4249-9cec-6c6f3f19dbff.png)

**Comment by fabiangreffrath** [comment]
> (dsda-doom has no 15/16 bit mode, so keep that in mind for the conditional)

So, in our case that would be `if (V_GetMode() == VID_MODE15 || V_GetMode() == VID_MODE16 || V_GetMode() == VID_MODE32)`, right? (It's high time we get rid of the intermediate bit depths as well...)

**Comment by kraflab** [comment]
Yes, that should work afaik

**Comment by JadingTsunami** [comment]
Yep, this looks good. Don't see any cause for concern from the OpenGL side.
