### ISSUE TITLE
Skies are broken in OpenGL Mode 

### ISSUE THREAD

**Issue by srludicolo** [coelckers/prboom-plus#374]
For some reason, the skies are broken in OpenGL mode. I was playing Eviternity and in MAP01, the moon is flattened and in the center of the screen, rather than being circular and at the top of the screen. Is there an option I do not have checked, or is this a bug?

(The top screenshot was taken in OpenGL mode, while the bottom screenshot was taken in 32-bit software mode)

![doom00](https://user-images.githubusercontent.com/83472414/128278225-51ee6369-4d08-4483-ac53-9277371dd3cc.png)
![doom01](https://user-images.githubusercontent.com/83472414/128278234-fbf66509-86b8-4ab6-8fc1-de0c3fc452bf.png)

**Comment by Kappa971** [comment]
This problem was partially fixed a few months ago (although the sky is not shown as in the render software). Wait for a new release or compile from source

**Comment by Kappa971** [comment]
@srludicolo if you are interested, this is Prboom+ compiled with Visual Studio 2019 for Windows 10 64 bit: 
[Prboom-plus_Win64.zip](https://github.com/coelckers/prboom-plus/files/6938836/Prboom-plus_Win64.zip)

**Comment by srludicolo** [comment]
Cool! In between your response, I found a pseudo-solution for the time being. Enabling freelook, and then setting the freelook slider completely to the left on the slider fixes the skies for the time being. By the way, I think it would be great if there was a guide on compiling the code from source :)

**Comment by fabiangreffrath** [comment]
There is a mostly reasonable compilation guide available in the https://github.com/coelckers/prboom-plus/blob/master/prboom2/INSTALL document.

**Comment by Kappa971** [comment]
> There is a mostly reasonable compilation guide available in the https://github.com/coelckers/prboom-plus/blob/master/prboom2/INSTALL document.

This guide is for Linux only

**Comment by Pedro-Beirao** [comment]
> > There is a mostly reasonable compilation guide available in the https://github.com/coelckers/prboom-plus/blob/master/prboom2/INSTALL document.
> 
> This guide is for Linux only

So? It is very easy to translate Unix instructions to Windows. Just install the required libraries (something like Chocolatey should work), create a “build” directory, then cmake and make.

Yes, **make** is a GNU tool, but you can get it on windows with Mingw or Cygwin

**Comment by Kappa971** [comment]
Are there any advantages of using Mingw instead of Visual Studio on Windows to compile Prboom+? Does anything change in performance?

**Comment by rfomin** [comment]
> Are there any advantages of using Mingw instead of Visual Studio on Windows to compile Prboom+? Does anything change in performance?

I am building with both and no, I think there is no observable difference.

**Comment by Kappa971** [comment]
@rfomin Thanks

**Comment by fabiangreffrath** [comment]
Skies are fixed in OpenGL mode in v2.6.1um.
