### ISSUE TITLE
V-sync and fullscreen mode tank framerate

### ISSUE THREAD

**Issue by srludicolo** [coelckers/prboom-plus#379]
It's pretty much in the title. I can't seem to use fullscreen or vsync without them halving my framerate. This has been an issue with prboom for as long as I can remember for some reason.

**Comment by fabiangreffrath** [comment]
So, what is your screen's refresh rate and what is the game's rate as reported by the IDRATE cheat?

**Comment by srludicolo** [comment]
I have a 60fps AMD Freesync monitor, but this happened with my old VGA monitor as well. Without vsync or fullscreen, I get ~1150 FPS. With fullscreen and no vsync, I get ~1350 FPS, but with horrendous screen tear, as should be expected. With fullscreen and vsync both turned on, I get 60 FPS, but the video is clearly at a lower framerate than that. I'd estimate I get around ~25 FPS. If it helps, I tested this on MAP32 of Alien Vendetta.

**Comment by Kappa971** [comment]
@srludicolo What video card do you have? Try reinstalling the video drivers, enable Freesync and VSync from the video card control panel, Freesync in the monitor and disable VSync from Prboom+.

The problem I've always had with Prboom+ (with different PCs, different monitors, different versions eg 2.5.1.4 - 2.5.1.5 - 2.6um - etc) is stuttering at regular intervals. I don't know if it's your same problem. I also noticed that the higher the fps, the less you notice the problem. With a 60hz/60fps monitor, the phenomenon is very noticeable. At 144hz the stuttering is still present (even with a Freesync monitor) but it is much less pronounced, almost irrelevant.
I imagine that solving such a problem may require a lot of work on the part of the developers, however this is a problem that has plagued Prboom+ for many years and I hope that one day it will be solved.

**Comment by srludicolo** [comment]
Agreed. This might seem silly, but perhaps implementing a GZDoom/Raze-style Vulkan renderer would help mitigate the issue? The whole reason I use ports like prboom+ and Woof! is to be as vanilla/boom/mbf accurate as possible, and GZDoom has innacuracy baked into its very core. I have a love/hate relationship with prboom+, but I have to use it because there are only so many options...

**Comment by Kappa971** [comment]
I would like to specify that the above happens with both the Software and OpenGL renderings. Other source ports that use only the Software render (Crispy Doom, Eternity Engine, etc) do not suffer from this problem, so I guess there is some programming error in Prboom+ (Present for a long time)

**Comment by vittau** [comment]
I've always had lots of stuttering with v-sync enabled in PrBoom+. What I do is limit the fps to 120 in the video driver (which is double my refresh rate, to minimize tearing) and that's it.

**Comment by Kappa971** [comment]
> I've always had lots of stuttering with v-sync enabled in PrBoom+. What I do is limit the fps to 120 in the video driver (which is double my refresh rate, to minimize tearing) and that's it.

Another way to make stuttering "acceptable" is to enable Fast Sync from the Nvidia control panel (I don't know if the AMD counterpart exists). This way the game, on a 60hz monitor, will run at 120fps. It doesn't solve the problem but it makes the game playable.
