### ISSUE TITLE
Sky floor "bleeding" in GL mode

### ISSUE THREAD

**Issue by XaserAcheron** [coelckers/prboom-plus#380]
Sky rendering has been improved a ton in recent prboom builds (big props!), but there's still one sticky issue that persists. For better or worse, in Doom's software renderer, the good ol' "sky hack" only applies to ceilings, not floors (i.e. if you have two adjacent F_SKY1 sectors with different floor heights, they will _not_ be merged into a single plane) -- in prboom's GL mode, however, the sky hack works on the floor, which results in some textures bleeding through the sky in certain vanilla maps.

Random example from [UDTWID](https://www.doomworld.com/idgames/levels/doom/s-u/udtwid) E4M8's exit room -- here's what it looks like in Software (as intended):
![doom03](https://user-images.githubusercontent.com/4601589/129654630-1cff225f-bc32-4200-9d85-b2d900617fe2.png)

And here's GL (whoops! texture bleeds):
![doom02](https://user-images.githubusercontent.com/4601589/129654617-be67b09d-8119-4db3-9d8a-97c9733e39c6.png)

For ease of testing, here's a quick isolated testcase wad -- ideally you should see nothing but sky, but in GL the SKSPINE2 textures bleed through:
[skybleed.zip](https://github.com/coelckers/prboom-plus/files/6996620/skybleed.zip)

Shame, since I've always wished you could skyhack the floor, but... better be an opt-in feature somewhere rather than have maps go bork. :P

**Comment by fabiangreffrath** [comment]
Who you gonna call? @JadingTsunami!

**Comment by JadingTsunami** [comment]
Sure, this is a quick fix. But I think it will require some extensive testing. I have the fix working locally; I will try a few test maps to try and ensure its robustness.

**Comment by JadingTsunami** [comment]
I created PR #381 to address this. The fix is working on my sky tricks test WAD and various rendering tricks WADs, but I would very much appreciate others checking it out as well. Rendering tricks tend to be finicky.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/79e89952c8c34437883317d43bbe74d853981e58
