### ISSUE TITLE
Unable to play at 320x200 when I start the sourceport with software exclusive fullscreen at 640x400 or more

### ISSUE THREAD

**Issue by El-Juancho** [coelckers/prboom-plus#387]
Title, i need to restart with software eclusive fullscreen turned off for play doom at 320x200, I would like not to restart every time I want to play at 320x200p in prboom+.

**Comment by fabiangreffrath** [comment]
Well, that's because exclusive fullscreen actually changes your screen's resolution and if your screen doesn't support 320x200 then we cannot offer this resolution as well.

**Comment by fabiangreffrath** [comment]
This would need implementation of https://github.com/coelckers/prboom-plus/issues/354 before.
