### ISSUE TITLE
(SUGGESTION) OpenGL video mode: Replace glBSP with AJBSP

### ISSUE THREAD

**Issue by Some1NamedNate** [coelckers/prboom-plus#388]
Andrew Apted, one of the developers of the glBSP node builder, has a fork of his called AJBSP which I think should be looked into.

https://gitlab.com/andwj/ajbsp

**Comment by JadingTsunami** [comment]
This doesn't seem relevant to prBoom+ as this is only a nodebuilder.

Are you proposing adopting some specific extensions to the GLnode specification?

Can you clarify?

**Comment by Some1NamedNate** [comment]
I wasn't completely sure what node builder is used for the OpenGL renderer.

**Comment by JadingTsunami** [comment]
The renderer does support GL nodes already; the node builder is a separate application that generates those nodes for the port to use.

So I think everything is already supported here, unless something specific is suggested.

**Comment by Some1NamedNate** [comment]
So PrB+ has its own, original OpenGL node builder?

**Comment by JadingTsunami** [comment]
> So PrB+ has its own, original OpenGL node builder?

Node builders produce nodes.

PrBoom consumes nodes.

PrBoom doesn't contain a node builder, it contains a node "consumer" which is compatible with the node builders you linked.

**Comment by Some1NamedNate** [comment]
Understood.
