### ISSUE TITLE
"Error loading song: Couldn't open /etc/timidity++/freepats.cfg" on Arch Linux

### ISSUE THREAD

**Issue by Valmar33** [coelckers/prboom-plus#394]
I have timidity++. Config file location on Arch is `/etc/timidity/timidity.cfg`

**Comment by fabiangreffrath** [comment]
This is hardly PrBoom+'s fault, as it doesn't even use Timidity itself. It merely uses it by means of SDL2_Mixer, so please report this issue to the respective package maintainers at Arch.

**Comment by Valmar33** [comment]
Oh? I didn't know, sorry! I'll get onto that.

Thanks regardless for all of the hard work you put into PrBoom+. :)

**Comment by IsaacMvmv** [comment]
Same here, any fix?
