### ISSUE TITLE
Incorrect Cacodemon sprite clipping when set to "Smart" in OpenGL

### ISSUE THREAD

**Issue by Fireb3rt** [coelckers/prboom-plus#395]
The Cacodemon's death animation has a very noticeable jump when sprite clipping is set to "Smart" with the OpenGL video mode.

**Comment by JadingTsunami** [comment]
Can you please post pictures of what you're seeing vs. what you expected?

**Comment by Fireb3rt** [comment]
![cacodeath](https://user-images.githubusercontent.com/77512209/135775858-14c35ae5-688f-45cc-8864-e413d4ba89a3.png)
OpenGL (left) vs software (right)
Its a little awkward to show in an image but the this frame of the cacodemon's death juts out much further than it probably should in OpenGL

**Comment by JadingTsunami** [comment]
Thanks for providing the additional data. I think this is expected just given how smart clipping works.

Have you tried the following settings? They may meet your needs:

1. Sprite clipping = constant
2. Sprite out of floor offset = 2

You can adjust the sprite out of floor offset to suit your tastes.

**Comment by Fireb3rt** [comment]
This does seem to be a good option, thanks.
