### ISSUE TITLE
Line-line teleport course deviation

### ISSUE THREAD

**Issue by simc2** [coelckers/prboom-plus#417]
Repeatedly line-line teleported items on a conveyer floor slowly drift off from their expected course. This is repeatable, it happens to every direction and it occures already in Boom 2.0 (in Dosbox).

Item's speed and moving direction (and the teleport line's angle) have an effect to the strength of this. It's too weak for the player to notice in game but voodoo players travelling the same loop endlessly may end up in wrong places.

For example in Sine Die map02 (Advanced engine needed : Boom) a decorative floor mover desyncs around 29:40 from the level start. (Voodoo player thing 290, sector 2488) At 59:14 the voodoo player gets stuck to the wall.
https://www.doomworld.com/idgames/?id=15135

In Eviternity map19 (PrBoom+ or GZdoom) the ceiling fan apparently has an autocorrect feature. It seems to push the voodoo player back after this has drifted too far. (Voodoo player thing 1912, sector 6541)
https://www.doomworld.com/idgames/?id=19304

But in most cases the items end up just scrolling alongside the wall without problems. The end results depend somewhat of the complevel though. It'd be nice if something could be done for the future complevels.

A test level, map01 Doom2:
[line-line-teleport-drift.zip](https://github.com/coelckers/prboom-plus/files/7488853/line-line-teleport-drift.zip)

Edit (2021-11-06): Removed the last sentence wish about new compatalability options for this.
Edit 2 (2021-11-06): Reeturned the original post.

**Comment by kraflab** [comment]
We don't change game behaviour in this port, nor is this repo the place for discussing future standards.
