### ISSUE TITLE
(From DSDA-Doom) Support for low-res widescreen

### ISSUE THREAD

**Issue by OpenRift412** [coelckers/prboom-plus#428]
Recently DSDA-Doom got an update, supporting Crispy/Woof-styled low-res widescreen options. The addition seems simple enough to add into PRB+UM. Can't really do a pull request since the current version of DSDA isn't a fork, but here's [the commit itself](https://github.com/kraflab/dsda-doom/commit/d149147bcc129b1a8073385d98fef3d78b38f7f5#diff-8ee0fd9d6c5f8bd2e74d61c8daca3d8064796d9c3f504d7c4d10337de84c48da). Hope we can see this added, I always love the little things like this.

**Comment by fabiangreffrath** [comment]
Already done. 
https://github.com/coelckers/prboom-plus/commit/9ff6f87242024ca834ec2952c65211557580f536

**Comment by OpenRift412** [comment]
> Already done. [9ff6f87](https://github.com/coelckers/prboom-plus/commit/9ff6f87242024ca834ec2952c65211557580f536)

Ohhhh okay thank you!
