### ISSUE TITLE
Hi, How Do you get the map label, time, secrets, kills an items count on top of the status screen left side?

### ISSUE THREAD

**Issue by DOOMMARINE117** [coelckers/prboom-plus#437]
Like How do you do all of that like in decino videos?

how do you use xbox series x controller?

**Comment by coelckers** [comment]
Here's the right place to ask: 
https://forum.zdoom.org/viewforum.php?f=4

**Comment by fabiangreffrath** [comment]
It's on the second page of Status Bar and HUD Settings: SHOW TIME/STS ABOVE STATUS BAR

Also, PrBoom+ related questions are better asked here: https://www.doomworld.com/forum/topic/106866-prboom-261um-aug-16-2021/
