### ISSUE TITLE
SDL Audio Sound Effects Bug

### ISSUE THREAD

**Issue by Raddatoons** [coelckers/prboom-plus#440]
This might just be a me problem, but when I set my preferred MIDI player to SDL, all of the sound effects become incredibly high pitched and sped up, like chipmunk noises.  The MIDIs themselves play fine and sound great though.  I was wondering if there was any way to fix this, either on my end or if it's something that needs an update port-wise.  Other source ports like Woof! don't seem to have this issue with SDL audio for me, which just confuses me even more.  Maybe one of my library files is messed up?

I'm running with the following specs on Windows 10 21H2:
CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
GPU: Nvidia GeForce GTX 1660 TI
RAM: 8 GB

My previous workaround has simply been to use PortMIDI instead, but it's comparatively far quieter than the other MIDI players, so if I can find a solution to make SDL work better then I'd really appreciate it.

**Comment by tpoppins** [comment]
Is this with an official release? You could try a [dev build](https://www.doomworld.com/forum/topic/106866-prboom-261um-aug-16-2021/?do=findComment&comment=2412761). Be sure to put the DLLs from their subfolder in your %PATH% or the prboom-plus folder.

What is the value of _samplerate_ in your prboom-plus.cfg (#Sound settings, line 92)? For integrated audio chipsets the best value is probably 48000.

**Comment by Raddatoons** [comment]
I'm using release version 2.6.1um.

I did adjust the samplerate and shifted around the midi soundfont file, but that didn't seem to work.

I also checked to see if perhaps I'd adjusted a separate setting wrong, but when I reinstalled the source port in a new location and set audio to SDL, it had the same issue with the clean install.  I'll try the dev build DLLs next.

**Comment by Raddatoons** [comment]
Installed the new DLLs into that fresh install, unfortunately none of them seemed to fix that particular snag.  It might just be with my computer specifically, which kinda stinks.

SDL is the only sound format this happens with.  Fluidsynth and OPL2 have normal sound effects, although I don't like the MIDI choices for them.  PortMIDI and ALSA sound just like SDL in terms of MIDI quality, and have normal sound effects, even if the MIDI tracks are lower in volume on those settings than on SDL.  It's bizarre, but in the long run I think it's merely a minor issue.

**Comment by tpoppins** [comment]
> Fluidsynth and OPL2 have normal sound effects, although I don't like the MIDI choices for them.

You can load different soundfonts with Fluidsynth. Scc1t2, WeedsGM3 and Arachno are three of the most popular ones but there are dozens of others. [This](https://www.doomworld.com/forum/topic/115527-doom-soundfont-sampler-pack-comparing-40-soundfonts-10-drum-soundfonts-using-doom-midi/) thread on DW should get you started.
