### ISSUE TITLE
Desync on JCM2-16 E2M8 v1.2 demo

### ISSUE THREAD

**Issue by tpoppins** [coelckers/prboom-plus#441]
WAD: [JCM2-16](https://www.doomworld.com/idgames/levels/doom/j-l/jcm2-16)
demo: DEMO1 in JCM-E2M8.WAD in [DOOM_J2D.ZIP](https://archive.org/download/cdrom-1001-nights-doom/1001NightsOfDoom1995wickedSensations.iso/LMPS%2FDOOM_J2D.ZIP)

This HMP demo plays back correctly to the end (10:56) with v1.2 vanilla and my private Crispy fork that incorporates all of SmileTheory's v1.0-1.2 fixes (PRs [#1205](https://github.com/chocolate-doom/chocolate-doom/pull/1205) and [#1207](https://github.com/chocolate-doom/chocolate-doom/pull/1207) on the Choco repo). 

The demo desyncs under current prb+ and Crispy masters. It starts to go out visibly of sync around 4:15-4:20, when the player is supposed to enter a hallway from outside and fight the Cacos in there, and by the 4:40 mark it goes haywire. The player never makes it into the hallway.

I found that I could fix this for the Crispy master by applying ST's commit [3fe7123](https://github.com/chocolate-doom/chocolate-doom/pull/1207/commits/3fe712316d947353a1576dd0bb91d3a395d8513b) (Emulate pre-v1.25 always active plats) from PR #1207; however, this single change is not enough in prb+'s case. Apparently it's missing at least one other critical fix from the same PR, probably [eebc685](https://github.com/chocolate-doom/chocolate-doom/pull/1207/commits/eebc68589a4efc0fc9b5b4a7d8e5c077053b6ca6) (Fix inaccurate v1.0/v1.1/v1.2 sight calculations) or [046ae69](https://github.com/chocolate-doom/chocolate-doom/pull/1207/commits/046ae694c2ef47a824fb266db830f2dc353bba42) (Emulate pre-v1.25 lowerAndChange behavior).

**Comment by kraflab** [comment]
I'll address this after I'm back from holiday vacation, unless someone wants to take it before the new year.

**Comment by tpoppins** [comment]
> I found that I could fix this for the Crispy master by applying ST's commit [3fe7123](https://github.com/chocolate-doom/chocolate-doom/pull/1207/commits/3fe712316d947353a1576dd0bb91d3a395d8513b) (Emulate pre-v1.25 always active plats) from PR #1207; however, this single change is not enough in prb+'s case. 

Of course not, because there are **two** places in prb+'s p_plats.c where active plats are removed as opposed to one in the Choco/Crispy counterparts. With the second instance compat-optioned the demo finally plays to the end. A PR is coming up.

@kraflab: please do have a look at porting over the other two ST fixes mentioned above.
