### ISSUE TITLE
Issues with UMAPINFO partime

### ISSUE THREAD

**Issue by Bytefyre** [coelckers/prboom-plus#450]
I spoke with JadingTsunami on Doomworld, and it appears I've uncovered a couple of UMAPINFO issues related to partime.  First, that attribute is ignored for entries of the style ExMy when x > 4, as I was attempting to create a better UMAPINFO for the main SIGIL.wad file which uses E5My map entries.  Second, I had tried to make one for Plutonia 2, but that was also ignored because of an apparent longstanding issue where only par times found in DeHackEd patches are honored for modified games.

**Comment by JadingTsunami** [comment]
Two issues:

1. Episodes >4 are not eligible for par times. This check should be ignored when UMAPINFO has set the par time. 
`src/wi_stuff.c:934`
```c
    if (wbs->epsd < 4)
```

2. Par times running a modified game are only considered valid if they are loaded from DeHackEd patches. There should be a similar check for par times loaded from UMAPINFO.
`/src/wi_stuff.c:932`
```c
  if (!(modifiedgame && !deh_pars) || (gamemission == pack_nerve && singleplayer))
```
