### ISSUE TITLE
SDL_RenderSetIntegerScale

### ISSUE THREAD

**Issue by fatalfeel** [coelckers/prboom-plus#455]

**Comment by fabiangreffrath** [comment]
You mean like this? 
https://github.com/coelckers/prboom-plus/blob/aebe20a5f828f5911681739a2ece894e8f1e4da3/prboom2/src/SDL/i_video.c#L1286-L1287

**Comment by fatalfeel** [comment]
build ok it's SDL version problem
answer:
https://fatalfeel.blogspot.com/2013/09/build-3d-game-doom1-on-ubuntu-1604.html
