### ISSUE TITLE
Add a drop-down console

### ISSUE THREAD

**Issue by JadingTsunami** [coelckers/prboom-plus#458]
I've seen many requests over time for a Quake-style console, as well as requests like #457 for one-off cheats that display some variable or state information. I think it would be a good idea to consolidate these into a drop-down console. Thanks to @fabiangreffrath I was made aware that dsda-doom has something similar already so there is some precedent.

I have a pseudo-console implementation in my [personal PrBoom fork](https://github.com/JadingTsunami/prboom-plus/tree/jds) which is only used by me.

I opened this issue to discuss:

* Is this something we want to explore for PrBoom-Plus?
* What is the minimum viable feature set we would like to see?
* What visual presentation style is best? (Right now for mine I have a flat black backdrop, but this is easy to change.)

For reference, the commands I have implemented are:
```
(All standard cheats (e.g., iddqd, idclip, ...))
resurrect
god
noclip
noclip2 (noclip+fly)
quit / exit
print (prints a message)
toggle_psprites (turns off player weapon sprites, good for screenshots)
snd_sfxvolume / snd
snd_musicvolume / mus
kill <class>
```

**Comment by fabiangreffrath** [comment]
Thank you for the insight! However, to be hontest, I believe that a console doesn't really *add* that much value. Most of the commands that you suggest are merely shortcuts to existing cheats or to menu switches. Given that PrBoom+ is in strict maintenance mode now and for quite some time, and that its successor in spirit (DSDA-Doom) already has a rudimentary console. I'd suggest to focus on completing this instead of adding another potentially fragile feature here.

**Comment by JadingTsunami** [comment]
> Thank you for the insight! However, to be hontest, I believe that a console doesn't really _add_ that much value. Most of the commands that you suggest are merely shortcuts to existing cheats or to menu switches. Given that PrBoom+ is in strict maintenance mode now and for quite some time, and that its successor in spirit (DSDA-Doom) already has a rudimentary console. I'd suggest to focus on completing this instead of adding another potentially fragile feature here.

Hmm, so why did you suggest I post this [here](https://github.com/coelckers/prboom-plus/pull/457#issuecomment-1015116643)? What changed?

**Comment by fabiangreffrath** [comment]
Sorry, I was just curious.

**Comment by JadingTsunami** [comment]
> Sorry, I was just curious.

Ah, OK. My take is basically this: even though this fork is nominally in "maintenance mode," the reality is "QoL" requests are being approved and accepted, even if they are new features (#457, #436, #230, etc.).

A console is another "QoL" improvement that makes adjusting settings, executing commands, and displaying information easier. This is why all modern non-vanilla ports have them and players often request them, including here. The starting command set may be initially limited, but the console will be built in a way to accept new commands easily so its use can be expanded.

As far as fragility, that seems a bit unfair: there is no reason to believe a console by itself would make the game more fragile than adding one-off cheats and menu options here and there that do the same things.

I am not sure if this is really open for discussion or not, but I thought I'd at least try to put forward the case for it. In my own play, this is my most-used feature and I think others might get benefit from it as well.

**Comment by kraflab** [comment]
I'd suggest to stop accepting these kinds of QoL requests just to stop the signaling that the port is NOT in maintenance mode 😉

**Comment by srludicolo** [comment]
To be honest, if you want a vanilla/Boom/MBF-style port with a drop-down console, you should prabably look into Doom Retro.

**Comment by srludicolo** [comment]
> As far as fragility, that seems a bit unfair: there is no reason to believe a console by itself would make the game more fragile than adding one-off cheats and menu options here and there that do the same things.

Although I don't see a reason for a console besides maybe a -statdump cheat, I do think its a bit silly to call stability into question. Maybe an option to toggle the console before starting a game would remedy this if it is that big of an issue? (Similar to how some settings don't change until the program is restarted in some source ports)

**Comment by fabiangreffrath** [comment]
> I do think its a bit silly to call stability into question. 

Every new feature requires a non-trivial amount of maintenance. That's not stupidity, that's experience.

**Comment by srludicolo** [comment]
> That's not stupidity, that's experience. 

I never said it was stupid, my friend. I apologize if it came off that way. I was just making a suggestion, there's no need for hostilities.

**Comment by JadingTsunami** [comment]
I realized we could also easily add a way to read and modify config file variables from the console. This could be a useful addition to console capabilities that provides unique benefits.

**Comment by JadingTsunami** [comment]
Closing this since there is no intention to merge these changes.

Any who are interested can use dsda-doom or [my fork](https://github.com/JadingTsunami/prboom-plus/tree/jds) if they really want.
