### ISSUE TITLE
help question for z-axis

### ISSUE THREAD

**Issue by fatalfeel** [coelckers/prboom-plus#460]
like this example how to do z axis for floor need paste texture
https://www.mediafire.com/file/yqvnw7ovrovtmg3/doomengine.tar.gz/

normally its a ray casting 2d but how to do Z for stairs

**Comment by fabiangreffrath** [comment]
Sorry, but I don't have the faintest idea what you are asking for here. Please take the time and ask some actual questions before you expect others to take their time and answer.
