### ISSUE TITLE
Problem with partime and endgame

### ISSUE THREAD

**Issue by Boryzeo** [coelckers/prboom-plus#474]
If a map defined in the UMAPINFO file uses endcast, endbunny, endpic or endgame = true, then the game will ignore the partime key.
```
MAP MAP03
{
	partime = 60
	endcast = true
}
```
In this example, the par time for MAP03 is defined to be 1 minute, but when the map ends the par time is shown to be 2 minutes, which is the par time for “The Gantlet”.

**Comment by JadingTsunami** [comment]
The responsible line is here:

`src/g_game.c:1646`
```c
	  if (next[0])
	  {
		  G_ValidateMapName(next, &wminfo.nextep, &wminfo.next);
		  wminfo.nextep--;
		  /*...*/
		  wminfo.partime = gamemapinfo->partime;
```

To resolve this, this function would need to be refactored.

Depending on how much refactoring is desired, the function could be mostly rewritten to avoid the `goto` or an else-if clause for mapinfo par time loading could be added around line 1767.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/d97cb0e78558b83e8c33d9a1d0129570f5b7563e
