### ISSUE TITLE
Doom II monster exclusion bug interrogative

### ISSUE THREAD

**Issue by Acts19quiz** [coelckers/prboom-plus#481]
Might not be an issue per se, but I couldn't find anywhere else to ask this and find out information on it (a Discord, PrBoom+ Wiki, etc.).

<https://doomwiki.org/wiki/Doom_II_monster_exclusion_bug> According to Doomwiki, PrBoom is supposed to have no special behaviour for DOOM II monster DoomEdNums used in Ultimate DOOM format maps (E#M#), the same category as ZDoom and Eternity. However, this has not been my experience. All testing I've done, both with PrBoom+ as well as original PrBoom, shows they're in the second category (original intended behaviour, like Y2K-era Boom). This includes all compat modes.

Looking into Doomwiki didn't shed any light, other than to show that that information was part of the first draft of that wiki page. Is this a PrBoom+ bug? Is the Wiki wrong? Is the Wiki correct but for a really ancient version of PrBoom? Am I missing some undocumented command line to change this behaviour? Thanks in advance.

**Comment by kraflab** [comment]
If the wiki is wrong then the wiki is wrong :^)
It sounds like it is from what you tested.

**Comment by fabiangreffrath** [comment]
PrBoom has always been in the second category, i.e. calling `continue` in the loop instead of `break`. The check has been externalized meanwhile for no apparent reason, but the logic remains the same. 

https://github.com/coelckers/prboom-plus/blame/fa76f157bc8f2f2ae9ac6e5f214a8f557ec497d4/prboom2/src/p_setup.c

**Comment by Acts19quiz** [comment]
Thank you two for your replies. I was afraid this was the case, but I had to make sure. I was really hoping the Wiki was implying there was a way to force this. That'd be real cool. My primary interest was actually a feasibility test of porting over ZDoom mods to Boom. Looks like that's not happening. I was hoping to find a good use or home for these icons (which load jankily within custom IWADs anyway since PrBoom+ is the few source port I've tested that actually loads its auxiliary resources _after_ the IWAD rather than _before_, like ZDoom, Eternity, even Crispy Doom--i.e., replacements in custom IWADs get squashed)
![M_WEAP](https://user-images.githubusercontent.com/63941237/155254161-4e9398b5-7935-465b-8eb4-32efefea7b42.png)
![M_AMMO](https://user-images.githubusercontent.com/63941237/155254163-329eb126-eb6b-4449-af50-9c3c29cbd798.png)
![M_ARMOUR](https://user-images.githubusercontent.com/63941237/155254165-69cb4a53-b724-426a-bad1-22ca8536f54f.png)
.

**Comment by fabiangreffrath** [comment]
> [...] PrBoom+ is the only source port I've tested that actually loads its auxiliary resources _after_ the IWAD rather than _before_, like ZDoom, Eternity, even Crispy Doom--i.e., replacements in custom IWADs get squashed). 

Sorry, but Crispy Doom doesn't load any auxiliary resources at all.
