### ISSUE TITLE
99ways.wad linedef type 97 does not work

### ISSUE THREAD

**Issue by doggodanubus** [coelckers/prboom-plus#484]
I'm baffled by this. 55602b0871155ae544584e03dfddaae075abae83c03ae599746b6e5f4f2fcaa0  99ways.wad

This wad has a teleport at the top of a lift on the outer linedefs of sector 324, linedefs 2267-2270 and they will not work. This works fine in prboom. The wad comes from doom world. https://www.doomworld.com/idgames/levels/doom2/0-9/99ways

I've attached a file with 99ways.wad map01_withoutbug.wad map03_withbug.wad
I stripped everything except the two sectors out of my map03 and the bug persists. 
I created map01_withoutbug from scratch and the bug is not there. 

[99bugmaps.zip](https://github.com/coelckers/prboom-plus/files/8210445/99bugmaps.zip)

**Comment by JadingTsunami** [comment]
UV Skill flag isn't set on the teleport destination.

**Comment by doggodanubus** [comment]
I see the flag missing. Vanilla doom.exe from ultimate doom works. Prboom 2.5.0 works without adding -complevel. Prboom-plus latest git pull does not work. Prboom-plus does not work with -complevel 1 for 1.666 which is the same as the doom.exe I used. So prboom-plus needs some help to mimic at minimum doom.exe as something has changed between Prboom 2.5.0 and Prboom-plus. Either a complevel change or add a complevel for prboom 2.5.0 perhaps?

**Comment by JadingTsunami** [comment]
It does not work with vanilla Doom 2 1.666 on ultra-violence. Are you *absolutely sure* you are playing on the *same* skill level across all your tests?

**Comment by doggodanubus** [comment]
You are correct and thank you for your time Jading. That is an odd one and I did not know teleports could be changed in that manner.  This is not a bug and I will close this.
