### ISSUE TITLE
TNT Evolution Will Not Launch

### ISSUE THREAD

**Issue by ForeskinJohn** [coelckers/prboom-plus#485]
I cannot get TNT EVO to launch at all, whether dragging and dropping the IWAD, or using ZDL to load it, I always get an error stating that its "exiting on signal 11"

**Comment by fabiangreffrath** [comment]
Well, it works for me. Is there any nore information that you could perhaps provide?

**Comment by ForeskinJohn** [comment]
im not sure what else i could provide, although i can get it to launch if i dont launch into the main menu for the wad, as in, if i launch TNT on map01, I can load my save and continue from there. just a weird issue, maybe its my compatibility settings?

**Comment by ForeskinJohn** [comment]
So i have reinstalled my PRBoom+ and TNT launches now, it will still crash and give me the error but it at least loads the main menu, ill take that until this issue gets fixed.

**Comment by fabiangreffrath** [comment]
Could you please choose a different music backend, e.g. OPL, and restart?

**Comment by JadingTsunami** [comment]
This person's issue was resolved by (apparently) rebooting their computer. See [this thread](https://www.doomworld.com/forum/post/2473999).
