### ISSUE TITLE
[Feature] Add complevel number in menu

### ISSUE THREAD

**Issue by NightFright2k19** [coelckers/prboom-plus#487]
In the ingame menu options, it would be helpful to add the complevel numbers for the "Default Compatibility Level" choices. For example, instead of "Boom", it could be "Boom (9)".

I am asking since mostly you just need a few complevels (2, 4, 9) while PrBoom+ offers a lot more and for a noob like me it's hard to keep them apart by name only. E.g. I was wondering whether "Boom Vanilla" or "Boom" is the right setting for complevel 9. In the PWAD readmes, they often mention complevel numbers, so it seems reasonable to also show them in the menu.

**Comment by facespkz** [comment]
Turns out the function for drawing strings didn't support newlines. Ugh. Is this close to what you're looking for?

![doom03](https://user-images.githubusercontent.com/22137884/161160189-5c9cd99c-2597-4fcd-b24a-b0aa6a9564d8.png)

**Comment by NightFright2k19** [comment]
Pretty much, yeah. For me, something like "CL9" would have been enough, actually, but I guess other names are already so long it's gonna clip into the next line, anyway, so this is as good as anything.

**Comment by fabiangreffrath** [comment]
The complevel->string table can be found here:
https://github.com/coelckers/prboom-plus/blob/d9716acadff8ac16cb5aa39b1a3a432713a6ef6b/prboom2/src/m_menu.c#L3301-L3323

It should be possible to prefix each string with the numerical complevel, e.g. "9/Boom" or similar. That'd be as fancy as it gets, though.

**Comment by NightFright2k19** [comment]
As long as the number shows up in some way, it'd be just fine.

**Comment by facespkz** [comment]
That does work, but I had to pad out the numbers a bit and shift the setting's x-coordinate.

![image](https://user-images.githubusercontent.com/22137884/161212727-d2a2c758-7daa-479d-8588-f17bec7ed16f.png)

It's not perfect, but it's neater than using two lines.

**Comment by NightFright2k19** [comment]
Looks good! With all these complevels available, numbers really help.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/784a17d73818cffa4ec3114cef99bcc990d157f4

**Comment by NightFright2k19** [comment]
Cool beans! Thanks a lot!
