### ISSUE TITLE
Custom blood not working?

### ISSUE THREAD

**Issue by mooreye** [coelckers/prboom-plus#492]
I loaded the following `.bex` file because I want to add Spectre's blood as grey (doesn't seem to be possible to make it fuzzy/transparent):

```
Thing 58
Blood color = 1
```

However, it's still red with both enabled and disabled "Colored blood and gibs" menu option.

**Comment by lafoxxx92** [comment]
Which version are you using? 2.6.1. is required.
Do other colors work?

**Comment by mooreye** [comment]
I use `v2.6.2` on Fedora 35 from official repos. No, no other colors and things seem to work.

**Comment by facespkz** [comment]
You're using the DoomEd number for a Spectre, not the Thing number, which should be 14. You can find Thing numbers on the [Doom Wiki.](https://doomwiki.org/wiki/DeHackEd#Thing_numbers)
