### ISSUE TITLE
When door sector is set to type 10 the linedef tag 117 turbo door requires two door presses.

### ISSUE THREAD

**Issue by doggodanubus** [coelckers/prboom-plus#494]
In the first two goodies doors off the start sector in fartnok.wad the door sector is set at 10 for close door after 30 seconds even though it's closed. It's facing linedef is tagged 117 turbo door open. This causes the door to not open on first press but takes another press. If you strip off the sector type which for this level should be done, it works fine. 

But there's a quirk that is cool. If you set the sector type to 14 door opens after 300 seconds it still takes two presses AND there are no door opening or closing sounds for that door. Perhaps a boon to deathmatch or very secret traps. I'm putting this here as advisory as this trick is pretty cool. If it is a bug that needs fixed it should be a compatibility option. This only seems to be the sector types that manipulate doors so 10 and 14. I only checked linedef tag 117 and the normal door linedef type of 1. 1 does not trigger this bug.

ef8a0e9faff5e8b0e9af91506b66c75a  fartnok.zip
From here
https://www.doomworld.com/idgames/levels/doom2/d-f/fartnok

**Comment by fabiangreffrath** [comment]
I guess we are not going to change the engine's behavior with tagged sectors for obvious reasons - even if the current behavior is deemed buggy or inconsistent.

**Comment by doggodanubus** [comment]
Well duh. I checked this with the original doom2 and it is exactly the same. Sorry to bother you. I may have found an original way to make silent doors. ;)

**Comment by doggodanubus** [comment]
I'm closing this, thanks.
