### ISSUE TITLE
UMAPINFO: Inconsistent behavior when endgame and nextsecret are present in a map

### ISSUE THREAD

**Issue by JadingTsunami** [coelckers/prboom-plus#496]
In the example map, the blue skull switch is a secret exit and the stone switch is a normal exit.

1. Choose the secret exit, and the map will restart
2. Choose the normal exit, and the map will end
3. If you have used the normal exit at least once, start a new game and choose the secret exit, and the game will proceed to map02
4. Remove "intertextsecret" from UMAPINFO and the map will end when either the normal or secret exit is chosen.

Recommend to honor "nextsecret" if present, regardless of "endgame" flags.

[secret.zip](https://github.com/coelckers/prboom-plus/files/8496835/secret.zip)

**Comment by NightFright2k19** [comment]
Does this mean it will be possible to end a game when leaving a map through regular exit, but continue through the secret exit? (And if so: What's the syntax?)

**Comment by rfomin** [comment]
> Would this work, then?

Yes, it will work if this PR is merged.
