### ISSUE TITLE
I can't get the correct music to play.

### ISSUE THREAD

**Issue by CricetoYT** [coelckers/prboom-plus#501]
No matter what I select, it just plays what sounds like Soundblaster music. For context, I just downloaded the latest build after using an older one for a while, and I know for a fact I could use Roland SC-55 music there. Actually, I just restored that old build from my recycle bin and yeah, it's working just fine, and I don't have anything extra added or downloaded in the folder. I have fluidsynth selected and I've restarted it several times but nothing still on the new build. Is there something I have to enable that I'm forgetting? I tried in 8-32 bit modes and OpenGL and it still doesn't work. Incase it's important I'm running the game on Windows 10, with DOOM.WAD from the Ultimate Doom on Steam (I took the WAD from the original DOS version, not the Unity rerelease folder).

**Comment by fabiangreffrath** [comment]
Do you have the "snd_soundfont" config key point to your soundfont file?
