### ISSUE TITLE
2s line midtexture vibration

### ISSUE THREAD

**Issue by simc2** [coelckers/prboom-plus#505]
If there's a midtexture on a 2s line the texture will shiver or vibrate vertically if behind it there is a upper/lower texture from a moving ceiling/floor plane covering parts of the midtexture. That is when the midtexture is stationary or inmovable relative to the backside ceiling/floor movement.

A 10% speed gif animation of the effect:
![Untitled 4 (1)](https://user-images.githubusercontent.com/27227020/171330003-2601844f-cf78-4292-88ac-075e269fa7d0.gif)

This happens in *Opelgl renderer only* and when the *uncapped framerate is on* (default). Happens in both Prboom-plus, and DSDA-Doom.

Doesn't appear to happen in sw renderer or in opengl when the uncapped framerate is off. Also it doesn't happen to the midtexture on the same side than the moving plane. 

A test wad for map01 Doom2. Should work if PrBoom-plus is run without config, Options > General >Video mode: opengl as the only change.
[texvibra.zip](https://github.com/coelckers/prboom-plus/files/8811167/texvibra.zip)

**Comment by JadingTsunami** [comment]
PR with proposed fix in #507.

**Comment by fabiangreffrath** [comment]
https://github.com/coelckers/prboom-plus/commit/acd8ce1a426e9856026dbb5d4d51da4f0945e3f5
