### ISSUE TITLE
Demo desync depending on the OS

### ISSUE THREAD

**Issue by Pedro-Beirao** [coelckers/prboom-plus#511]
Tested in PrBoom+, dsda-doom and Woof!

Game: Doom 2
Complevel: 9
Wad: https://www.doomworld.com/applications/core/interface/file/attachment.php?id=188069
Demo: https://www.doomworld.com/applications/core/interface/file/attachment.php?id=188068

On MacOS, in any of these ports, the demo exits with 3821/3821 kills
On Windows, in any of these ports, the demo exits with 3820/3821 kills
I havent tested Linux

Using the "health above enemies" option of dsda-doom, the demo ends with the remaining cyberdemon having 1 HP. My guess is that there are rounding differences between the OSes.

The demo was recorded on MacOS by [Sturrum](https://www.doomworld.com/profile/36362-sturrum/), and because of the desync, it cannot be uploaded to dsdarchive.

**Comment by fabiangreffrath** [comment]
Reminds me of this: 
https://github.com/coelckers/prboom-plus/issues/74#issuecomment-633972552

**Comment by Pedro-Beirao** [comment]
Removing the -ffast-math flag does not fix the issue. I still get 3821 kills on Mac.

**Comment by fabiangreffrath** [comment]
Aw, too bad.

**Comment by rfomin** [comment]
@Pedro-Beirao Can you re-upload these files elsewhere (or right here on GitHub), DW doesn't give me access. I want to try the clang build for Linux/Win. MacOS on ARM?

**Comment by JadingTsunami** [comment]
> @Pedro-Beirao Can you re-upload these files elsewhere (or right here on GitHub), DW doesn't give me access. I want to try the clang build for Linux/Win. MacOS on ARM?

Appears to be sourced from [this](https://www.doomworld.com/forum/post/2508926) post.

**Comment by rfomin** [comment]
> Appears to be sourced from [this](https://www.doomworld.com/forum/post/2508926) post.

Thanks, got it.

I can confirm that on Windows with MSVC 3820 kills, on Ubuntu WSL with clang 3821.

**Comment by fabiangreffrath** [comment]
So, we have the same issue on Woof?! Oh my, we seem to be deep into the realm of "undefined behavior" or "implementation-defined behavior" which could be just about anything. 🤷

**Comment by rfomin** [comment]
This fixes it: https://github.com/team-eternity/eternity/blob/master/source/r_main.cpp#L203
But this is needed for clang in general, on Win/Linux too.

**Comment by fabiangreffrath** [comment]
Sorry, but I don't understand this fix at all. What could be volatile about a variable that is passed to a function?

**Comment by rfomin** [comment]
`volatile` tells the compiler not to optimize anything that has to do with the `volatile` variable. To be honest, I haven't used this keyword much, but I think the issue is clang optimization.

**Comment by fabiangreffrath** [comment]
Yes, right, it affects all places where these variables are involved. May be it's some kind of "cannot get negative" assumption. Could you try with this sign bit check?
```diff
--- a/prboom2/src/r_main.c
+++ b/prboom2/src/r_main.c
@@ -182,8 +182,8 @@ PUREFUNC int R_PointOnSide(fixed_t x, fixed_t y, const node_t *node)
   y -= node->y;

   // Try to quickly decide by looking at sign bits.
-  if ((node->dy ^ node->dx ^ x ^ y) < 0)
-    return (node->dy ^ x) < 0;  // (left is negative)
+  if ((node->dy ^ node->dx ^ x ^ y) & 0x80000000)
+    return (node->dy ^ x) & 0x80000000;  // (left is negative)
   return FixedMul(y, node->dx>>FRACBITS) >= FixedMul(node->dy>>FRACBITS, x);
 }


```

**Comment by rfomin** [comment]
> Could you try with this sign bit check?

I've got a crash with this patch.

**Comment by fabiangreffrath** [comment]
He? Perhaps `return ((node->dy ^ x) & 0x80000000)` then?

**Comment by fabiangreffrath** [comment]
Ah, because it's return value is actually supposed to be boolean and is used as an array index. How about `return (((node->dy ^ x) & 0x80000000) != 0)` then?

**Comment by rfomin** [comment]
No crash, but still desync 3821 kills.

**Comment by fabiangreffrath** [comment]
Okay, I just wondered if using Choco's variant of that function would fix it.

**Comment by rfomin** [comment]
Alternative is `__attribute__((optnone)) int R_PointOnSide(fixed_t x, fixed_t y, node_t *node)` but it's notably slower than `volatile` solution. `volatile` don't have performance penalty from my testing.

**Comment by fabiangreffrath** [comment]
There must be something ambigious in this code that the compiler opts out.

**Comment by mikeday0** [comment]
`volatile` is used heavily in embedded. It tells the compiler that this variable's value can change outside the scope of the normal program flow. For example if you have a variable tied to memory address which contains a hardware counter value, ADC reading, state of an IO pin, etc then you would declare it as `volatile`. It's also used for global variables that can be modified by interrupt routines. It essentially tells the compiler that the program should **always** read the value of the variable from memory. This isn't exactly the same as disabling optimizations, but it does prevent the compiler from applying certain kinds of optimizations.

All that said, the fact that `volatile` fixes this issue rubs me the wrong way. 😛 These variables aren't actually `volatile` per the usual definition. It is a bit of a hack, albeit an effective one. What a crazy bug.

**Comment by Pedro-Beirao** [comment]
The workaround works on my machine

Thanks for digging into this!
