### ISSUE TITLE
 UMAPINFO: Par times do not work (without dehacked)

### ISSUE THREAD

**Issue by Mabadman** [coelckers/prboom-plus#535]
Setting par times with UMAPINFO will not work as intended as the map will display the IWAD's par time for that map instead.
Only way to get it to work is to create a DEHACKED lump and set a par time for any map. Once the par time is set, regardless of which map it is, par times set by UM will work as intended.

WADs used for testing:
[umapinfo.zip](https://github.com/coelckers/prboom-plus/files/9669218/umapinfo.zip)

**Comment by JadingTsunami** [comment]
Are you using the latest development version?

**Comment by Mabadman** [comment]
> I suspect this testing was done on an old version
Yes, I had to use the latest release as I don't know how to build PrBoom+ on my own.
Thank you for the info. I'll close this issue.

**Comment by JadingTsunami** [comment]
> > I suspect this testing was done on an old version
> 
> Yes, I had to use the latest release as I don't know how to build PrBoom+ on my own. Thank you for the info. I'll close this issue.

You may find [these posts](https://www.doomworld.com/forum/post/2519297) helpful to download the latest development version.
