### ISSUE TITLE
Scythe 30 OpenGL HOM

### ISSUE THREAD

**Issue by kraflab** [coelckers/prboom-plus#541]
There is a HOM in the floor in opengl on map 30 of scythe (top right of map):
![doom00](https://user-images.githubusercontent.com/25529060/200894715-bac4a1f1-07d2-4508-88d2-71a40e73da0d.png)

**Comment by JadingTsunami** [comment]
That's a bug in the map. Line 3188 and 3190 are erroneous. In the software renderer, it ends up not being visible.

**Comment by kraflab** [comment]
Ah ok, good to know
