### ISSUE TITLE
Software renderer error in olnoname.wad

### ISSUE THREAD

**Issue by kraflab** [coelckers/prboom-plus#556]
Wad: https://www.doomworld.com/idgames/levels/doom2/Ports/m-o/olnoname
Map: 01
Area: turn immediately left and then right, the fan is on the wall down the steps.

<img width="1512" alt="prb_sw_texture_error" src="https://user-images.githubusercontent.com/25529060/209855383-422e0b49-7340-4e73-a55b-e6febb809235.png">

It looks fine in opengl, but has these junk pixels in software mode.

**Comment by XaserAcheron** [comment]
This may be a user error -- that's a translucent midtexture. Maybe a zdoomism? GZDoom draws transparent pixels in a texture as black (or probably whatever color 0 is) if you place it on a 1-sided line.

That said, GZD's behavior is hella convenient as a mapper, so if y'all want to "canonize" that for pr+ software mode then I certainly wouldn't complain. :P

**Comment by kraflab** [comment]
Cleaning up (closing) some old issues
