### ISSUE TITLE
Command-line/path issues with Windows builds

### ISSUE THREAD

**Issue by ceski-1** [coelckers/prboom-plus#561]
Starting with https://github.com/coelckers/prboom-plus/commit/bddfb3be2c178f40b0d68fea33cd47090666409f command-line paths no longer function correctly when compiling for Windows using MSYS2 (MinGW 64-bit). Drag-n-drop for wads works, but `-iwad` and `-file` do not. I'm using a script similar to the following:

<details><summary>Example bash script</summary>

```console
# updates
pacman -Sy --noconfirm
pacman -Suu --noconfirm
pacman -Scc --noconfirm

# packages
pacman -S --needed --noconfirm git zip base-devel mingw-w64-x86_64-cmake \
  mingw-w64-x86_64-toolchain mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_net \
  mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_mixer \
  mingw-w64-x86_64-libmad mingw-w64-x86_64-fluidsynth mingw-w64-x86_64-dumb \
  mingw-w64-x86_64-libvorbis mingw-w64-x86_64-portmidi

cd ~
git clone https://github.com/coelckers/prboom-plus
cd prboom-plus/prboom2
mkdir build
cd build
cmake .. -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -Wno-dev
make -j$(nproc)

cd ..
mkdir release
cp ./build/*.exe ./release/
cp ./build/*.wad ./release/
cd release

# note: add dsound.dll to mingw-bundledlls blacklist
~/mingw-bundledlls --copy prboom-plus.exe
~/mingw-bundledlls --copy prboom-plus-game-server.exe

strip *.exe
zip -j -r ~/prboom-plus-$(date +"%Y%m%d")-win64.zip *
cd ~
```
</details>

[Related Doomworld thread](https://www.doomworld.com/forum/topic/106866-prboom-262-feb-11-2022/?page=55&tab=comments#comment-2597290)

**Comment by rfomin** [comment]
It works for me in MSYS2 terminal and with MSVC build.

I tried using `mingw-bundledlls` and indeed the resulting distribution doesn't work, exits on `M_LoadDefaults()`. Not sure what's going on.

**Comment by ceski-1** [comment]
MSYS2 and MSVC builds work now, thanks!
