### ISSUE TITLE
[64-bit/Windows] Portmidi does not play music

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/prboom-plus#64]
So, I have managed to compile a build with yesterday's master .zip, and although things are in place, there are some issues.

Notably, Portmidi does not play any music once switched to it. Music simply stops. The soundfont is also missing after the building process finishes, although it can easily be grabbed from 2.5.1.5 or the web.

**Comment by alexey-lysiuk** [comment]
See https://github.com/coelckers/prboom-plus/commit/7c7991fcff48312929f230fbadd3f8e51d0afd3a. PortMIDI was fixed in our dependency package, but not in the latest stable version, e.g. installed by `vcpkg`.

**Comment by sinisterseed** [comment]
> See [7c7991f](https://github.com/coelckers/prboom-plus/commit/7c7991fcff48312929f230fbadd3f8e51d0afd3a). PortMIDI was fixed in our dependency package, but not in the latest stable version, e.g. installed by `vcpkg`.

Call me dumb, but I'm not following.

The portmidi.dll I am using is the one from the dependency package (x64 version), and it does not work.

**Comment by alexey-lysiuk** [comment]
Please take a look at the change. It disables PortMIDI for x64 Windows target regardless of DLL. There is no way to determine is it fixed or not.

**Comment by sinisterseed** [comment]
> Please take a look at the change. It disables PortMIDI for x64 Windows target regardless of DLL. There is no way to determine is it fixed or not.

Ah, so you mean it was disabled in the engine then, I guess? That explains why it does nothing.

**Comment by coelckers** [comment]
It had to be disabled because it was outright crashing the engine. If the dependency can be updated to a non-crashing version, the player can be re-enabled.

**Comment by alexey-lysiuk** [comment]
It should be fixed already. I cannot verify this right now, but I remember it worked for me with [the patch](https://github.com/coelckers/prboom-plus/blob/d965be38a1bea0eb4790a83c99d86d435a6c8aa4/.github/workflows/portmidi/winmm-x64.patch). The current version of dependencies package contains PortMIDI built with it.

**Comment by sinisterseed** [comment]
I think we're speaking in tongues here :v .

Eh, at any rate, I have compiled an x86 version in the meantime, now Portmidi actually works.

**Comment by alexey-lysiuk** [comment]
The crash affects Windows 64-bit build only.

**Comment by sinisterseed** [comment]
Compiled a new x64 build today and I can indeed confirm that Portmidi is now working again, and correctly after it was re-enabled. Groovy.
