### ISSUE TITLE
Prboom_plus.exe does not get built

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/prboom-plus#66]
This was reported by **maxmanium** a while ago (see this: https://www.doomworld.com/forum/topic/110955-building-glboom/ ) , and I noticed this today as well.

Prboom_plus.exe does not get built along with glboom_plus.exe. According to mental this was actually done on purpose, but I think adding it might be a good idea since some people do want to use it.

There is also another issue, the .exe was renamed which is very misleading. The executable that gets built is **NOT** prboom_plus.exe but glboom_plus.exe, just renamed. If there is no desire to support building prboom_plus.exe as well, this can just be closed I guess.

But I do believe the .exes should have their original names restored...

**Comment by alexey-lysiuk** [comment]
While working on CMake based build system, I had no interest in software renderer. If Graf asked me to add it, probably I could do this.
Actually, software renderer still can be enabled by setting `BUILD_GL` to `NO` during CMake configuration step. It's just impossible to build both executable files together.

**Comment by sinisterseed** [comment]
Ah, damn, it's actually not possible to build both simultaneously? Alright, then that part can be ignored.

That executable still has its purpose, for now. While the SW renderer can also be switched to from the GL executable, it does have some issues unique to it - notably, projectile translucency does not work, they are always rendered opaque even when transparency is enabled.

The name issue remains though.
