### ISSUE TITLE
Location of inputs in the code needed

### ISSUE THREAD

**Issue by tryhardsnipehrd** [coelckers/prboom-plus#72]
I would like to know the locations of the inputs...
I am trying to add support for mouse buttons but I cannot find the location of the keyboard/mouse inputs for it to work. If anyone could point me there that would be great!

**Comment by alexey-lysiuk** [comment]
The starting point would be [I_SDLtoDoomMouseState()](https://github.com/coelckers/prboom-plus/blob/4ec412e49443a1ac105c1d82451818a61742eb22/prboom2/src/SDL/i_video.c#L218) function. Taking into account that SDL supports 5 mouse buttons, I'm not sure that you can add something to existing code.

**Comment by fabiangreffrath** [comment]
Low level code would be here:
https://github.com/coelckers/prboom-plus/blob/master/prboom2/src/SDL/i_video.c#L229

Binding of low level events to game events would be here:
https://github.com/coelckers/prboom-plus/blob/master/prboom2/src/g_game.c#L454

**Comment by fabiangreffrath** [comment]
Is this really an issue or can we close this?

**Comment by fabiangreffrath** [comment]
Closing this after a month of silence.
