### ISSUE TITLE
[Request] Linux version

### ISSUE THREAD

**Issue by Birdman7** [coelckers/prboom-plus#73]
The Linux version of PrBoom+ seems to be out of sync, considering this is the port's new home. Can you provide a guide to install this version or a .deb/appimage file please?

**Comment by alexey-lysiuk** [comment]
For Ubuntu it's something like this
```
sudo apt install git cmake g++ libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libpcre3-dev libmad0-dev libfluidsynth-dev libdumb1-dev libvorbis-dev libportmidi-dev
git clone https://github.com/coelckers/prboom-plus.git
cd prboom-plus
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../prboom2
make
```

**Comment by fabiangreffrath** [comment]
I'll update the prboom-plus Debian package wiyh this fork as soon as it sees a release.

**Comment by fabiangreffrath** [comment]
Good news:
https://tracker.debian.org/news/1146772/accepted-prboom-plus-22517umgit72-1-source-into-unstable/

**Comment by Birdman7** [comment]
Thanks man
