### ISSUE TITLE
Demo desync

### ISSUE THREAD

**Issue by Cryoniq** [coelckers/prboom-plus#74]
Greetings. I downloaded latest sources of PrBoom-Plus (master branch) and built 64-bit binary on macOS. Then i recorded UV-MAX demo of one map. This demo plays back correctly with that binary however gets desynced if played on Windows via [2.5.1.5 binaries](http://prboom-plus.sourceforge.net/prboom-plus-2.5.1.5.r4526-win32.zip). I also built 64-bit macOS binary from ["official" sources (svn repo)](https://svn.prboom.org/repos/branches/prboom-plus-24/prboom2/) and it played demo back correctly too. I even compiled 64-bit binary for Windows from master branch sources and tried to play this demo back on it but also got desync.

What could cause this?

Demo and WAD in attachment below. Recorded with "complevel 9", iwad "doom2.wad". Desync happens after 5m 30s

[entx3320.zip](https://github.com/coelckers/prboom-plus/files/4344446/entx3320.zip)

**Comment by fabiangreffrath** [comment]
So we have a built-on-mac vs. built-on-windows issue here, right? Might as well boil down to built-with-clang vs. built-with-gcc. The question is, which one is correct, i.e. which build replicates DOOM2.EXE properly. Could you probably check this, please?
Also, I  remember a similar issue being mentioned on the forum with a link to this:

https://github.com/team-eternity/eternity/blob/master/source/r_main.cpp#L203

**Comment by Cryoniq** [comment]
I'm sorry but I don't understand what I have to do now. How could I check which build replicated DOOM2.EXE (vanilla one?) Properly? I mean I can make a 64-bit build with gcc or clang on Linux for example but what to do after that?

Also I tried to replace "fixed_t x, fixed_t y" with "volatile fixed_t x, volatile fixed_t y" and still got no desync on macOS.

**Comment by fabiangreffrath** [comment]
Sorry, I should have been more clear.

We have a demo sync problem between Mac and Windows builds. The important part to know first is which of the builds records "true" Vanilla demos (and plays them back without desync). This could be checked e.g. by recording a (say, complevel 2) demo with each build and testing it in e.g. Chocolate Doom or DOOM2.EXE in Dosbox.

Does your Mac build properly playback other more complex (e.g. complevel 9) demos?

**Comment by Cryoniq** [comment]
Just tried to play back two demos recorded with complevel 9 ([swift death d2all made by ClumsyDoomer](https://dsdarchive.com/files/demos/swideath/23480/swallx249.zip) and [sunlust d2all made by Azuruish](https://dsdarchive.com/files/demos/sunlust/23278/slallx3638.zip)) - both got desync on mac build. However on Windows everything played back properly. 

I'll also try to record some demos with both builds and post results here.

**Comment by fabiangreffrath** [comment]
Thank you! I guess your results already identify the Mac build as the odd one. Does changing the variable declarations to `volatile` bring demo sync on the Mac back?

**Comment by Cryoniq** [comment]
No, it doesn't. These demos are still desyncing.

**Comment by fabiangreffrath** [comment]
Phew, okay. Does it make a difference if you build withour any optimization enabled (`CFLAGS = "-O0"`)?

**Comment by Cryoniq** [comment]
Built binary with "make CFLAGS='-O0'" command - now everything plays back correctly. Previous demos (swift death and sunlust) got no desync and my demo from first comment desyncs exactly on the same time as it does in Windows. I guess I just have to record new demo now and test it :D

I'll post the new results here.

**Comment by fabiangreffrath** [comment]
So, we have a ill-guided optimization attempt by clang here. Now the questions are, where so we have it and how do we pevent it?

**Comment by Cryoniq** [comment]
Well, last demo I've recorded is playing back correctly in Windows build too. [And also in PrBoom+2.5.1.5r4526 (last "official" testing version)](http://prboom-plus.sourceforge.net/prboom-plus-2.5.1.5.r4526-win32.zip)

So the question is, how to prevent this optimization (these optimizations?) and what can I do for helping with this?

**Comment by fabiangreffrath** [comment]
Just some brainstorming: I think we need to isolate at least the offending source file first. Is it possible for you to build all sources with `-O3` and only one of `src/p_*.c` with `-O0` at a time and see if the linked binary desyncs or not?

**Comment by fabiangreffrath** [comment]
Does your demo-desyncing issue still persist if you change nothing more than removing the `-ffast-math` optimization flag from here and build as usual?

https://github.com/coelckers/prboom-plus/blob/master/prboom2/CMakeLists.txt#L176

**Comment by Cryoniq** [comment]
Greetings. 
I'm terribly sorry for being inactive for so long. 

> Just some brainstorming: I think we need to isolate at least the offending source file first. Is it possible for you to build all sources with `-O3` and only one of `src/p_*.c` with `-O0` at a time and see if the linked binary desyncs or not?

> Does your demo-desyncing issue still persist if you change nothing more than removing the `-ffast-math` optimization flag from here and build as usual?
> 
> https://github.com/coelckers/prboom-plus/blob/master/prboom2/CMakeLists.txt#L176

Thank you very much. I'll try both your suggestions as soon as possible and post the results here.

**Comment by Cryoniq** [comment]
Okay, there is something i can't understand. Maybe since when i was inactive something was updated in prboom-plus sources and something got fixed or i don't know. I built prboom-plus 2.5.1.7um from the last sources (taken from this repo, as of 05/29/2020) and used NO additional optimization commands. It's just a regular build made via cmake. Then i tried to playback demos mentioned earlier (swift death and sunlist) and everything played back correctly. I really have no clue how this was fixed or how and why i got desyncs earlier. Now i'm thinking about ways to recreate this issue.

**Comment by fabiangreffrath** [comment]
Do you change your compiler or linker meanwhile?

**Comment by Cryoniq** [comment]
No and no. Everything is exactly same as before.

**Comment by fabiangreffrath** [comment]
moon phase...

**Comment by Cryoniq** [comment]
Indeed lol.
In fact - I feel dumb now... I only tried to do exactly same steps to build prboom-plus from sources as i did earlier.

**Comment by fabiangreffrath** [comment]
Have you removed all `CMakeFiles` etc.? CMake is rather stubborn with its caching, so it possible that same CFLAGS are still cached somewhere.

**Comment by Cryoniq** [comment]
I don't think it's a problem as I've made a completely new build in the separate folder.
