### ISSUE TITLE
Automap no lines OpenGL Linux

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#89]
**Followed these steps**
```
rm -fr ~/.prboom-plus
clone https://github.com/coelckers/prboom-plus.git
cd prboom-plus/prboom2
cmake .
make
./glboom-plus -iwad DOOM2.WAD
```
options > general > 
screen resolution > 1920x1080
video mode > opengl

press Escape > new game > hurt me plenty
press Tab

**Expected**
- lines around textured 2d floors
- grid when pressing G

**Actual**
- can see textures but no lines
- no grid when pressing G
- no change when pressing O (no lines)
- no change when toggling textures on automap (binded it to T, no lines)

**Comment**
Interestingly pressing M shows the markings.
This problem disappears entirely when the "video mode" is set to anything other than "opengl" but I want to use opengl.
When built and followed same steps with https://aur.archlinux.org/packages/prboom-plus/ - the automap lines appeared fine.
I'm not sure which commit introduced this issue but can see if I can pinpoint it - if it's any help.

Please let me know if you can if there's anything I could test for, or if you know what might be the problem, or if I'm doing something wrong here.

Cheers.

![2020-05-28-191858_1920x1080_scrot](https://user-images.githubusercontent.com/2176657/83179350-d3546800-a119-11ea-902c-b3a9963c29f6.png)

**Comment by fabiangreffrath** [comment]
Just a guess,  is this probably related?

https://github.com/coelckers/prboom-plus/commit/d4079ea28ae331d142c973d050d6d83a056a8d87#diff-13ffbdec4f35b1f7a4abe16fc2ae3a5a

**Comment by runlow** [comment]
Thank you for the hint. At the moment I am unsure if what you have mentioned is related but I will look into it further.

Meanwhile I believe I have narrowed down the number of commits that could be introducing this issue.

When I built 7b48369b06 and chose opengl as the video mode - the lines on the automap were OK.
When I built 09063fc06d and chose opengl as the video mode -  I could no longer see the automap lines.

The two commits are two weeks apart and they were created during migrating to SDL2.

**Comment by fabiangreffrath** [comment]
Sorry, but that commit interval is pretty useless, as it contains the entire SDL2 migration.

Does the problem persist if you use any other screen resolution than 1920x1080?

The actual line drawing function in OpenGL mode is `gld_DrawLine_f()` in `gl_main.c`. There are two code paths separated by an `#if ... #else ... #endif`. Could you try forcefully enabling one or the other?

**Comment by fabiangreffrath** [comment]
Does rotate mode work?

**Comment by runlow** [comment]
Yes, the problem seems to persist on other resolutions than 1920x1080 (here it's 800x600).

![doom02](https://user-images.githubusercontent.com/2176657/83255907-422cd200-a1a9-11ea-911e-74b23fc98ebc.png)

![doom00](https://user-images.githubusercontent.com/2176657/83256624-a734f780-a1aa-11ea-8548-87576dc62f47.png)

Rotate mode (toggled by pressing R) seems to work although only the textures are being displayed (not the lines).

![doom00](https://user-images.githubusercontent.com/2176657/83256113-bbc4c000-a1a9-11ea-9acd-88c48d467aeb.png)

Will test forcefully enabling the code paths you mentioned.

**Comment by runlow** [comment]
Looks like this is it!

I've commented out the first half between `#if `and `#else` directives (as well as those directives themselves) in `gl_main.c` for `gld_DrawLine_f()` and now I can see the map lines and the grid lines when I press Tab.

![doom01](https://user-images.githubusercontent.com/2176657/83260886-6c36c200-a1b2-11ea-8e2f-b65c35b05869.png)

Also noticed that after making this change the lines still disappear when the overlay mode is on and the textured mode is off.

![doom03](https://user-images.githubusercontent.com/2176657/83261305-07c83280-a1b3-11ea-8bac-e6012940164e.png)

The lines display fine without textures when the overlay mode is off again.

![doom01](https://user-images.githubusercontent.com/2176657/83261518-64c3e880-a1b3-11ea-97e3-082610b78dfb.png)

Much closer to a solution now than I was before. Thank you.

**Comment by runlow** [comment]
These were [the](/coelckers/prboom-plus/tree/master/prboom2/src/gl_main.c#L806-L834) exact [lines](/coelckers/prboom-plus/tree/master/prboom2/src/gl_main.c#L849) (linked) which I commented out in the previous message.

**Comment by runlow** [comment]
Was able to accomplish the same result as the previous by first doing
`git checkout .`
to undo the previous workaround
and then only commenting out [this one line](https://github.com/coelckers/prboom-plus/blob/master/prboom2/src/gl_opengl.h#L41) in `gl_opengl.h` like so
`//#define USE_VERTEX_ARRAYS`
and then typing
`make`

Also noticed something bizarre. With the above change - picking up a shotgun or a chainsaw makes the previously invisible (when overlay mode is on and texture mode off) map lines display on the automap. While shooting from a shotgun the lines disappear momentarily. With the double barrel it's the opposite - no lines while holding it but the lines appear for a moment while shooting from it.

With the texture mode switched on gladly everything seems to work fine now. Another workaround I've found is to set
`map_textured_overlay_trans    0`
in the config file if I don't want to see textures in the automap with the overlay mode on.

The above workarounds work well enough for me for the time being for the purpose of just playing doom. Ideally these issues should be fixed. Not sure I understand well enough what the problem is to write a fix myself but I will see what I can do.

Hopefully this helps someone else who encounters the same issue.

**Comment by runlow** [comment]
Don't know how relevant this is but I have noticed that with the above change - even with "overlay mode" off - the colours of the map lines appear different in "opengl" and "8bit" video modes

8bit
![doom01](https://user-images.githubusercontent.com/2176657/83420872-2599cf80-a41f-11ea-93e8-c15264011ed8.png)

opengl
![doom02](https://user-images.githubusercontent.com/2176657/83420904-30ecfb00-a41f-11ea-85fd-a79004ed92cf.png)

**Comment by runlow** [comment]
This fully fixes all the problems I reported in this issue! (on my setup)

Can make a pull request if that's preferable to me pasting diffs here although I'm not sure how this change would impact others with different a different hardware/setup.

It's just what makes the lines appear properly for me but perhaps it would break the automap for someone else? It's one thing to write a quick fix for myself that's good enough to just play the game, another to keep things working for everyone.

Let me know your input.

```diff
--- a/prboom2/src/gl_main.c
+++ b/prboom2/src/gl_main.c
@@ -838,6 +838,7 @@ void gld_DrawLine_f(float x0, float y0, float x1, float y1, int BaseColor)
   if (alpha == 0)
     return;
 
+  glDisable(GL_TEXTURE_2D);
   glColor4f((float)playpal[3*BaseColor]/255.0f,
             (float)playpal[3*BaseColor+1]/255.0f,
             (float)playpal[3*BaseColor+2]/255.0f,
@@ -846,6 +847,7 @@ void gld_DrawLine_f(float x0, float y0, float x1, float y1, int BaseColor)
     glVertex2f( x0, y0 );
     glVertex2f( x1, y1 );
   glEnd();
+  glEnable(GL_TEXTURE_2D);
 #endif
 }

--- a/prboom2/src/gl_opengl.h
+++ b/prboom2/src/gl_opengl.h
@@ -38,7 +38,7 @@
 #include "config.h"
 #endif
 
-#define USE_VERTEX_ARRAYS
+//#define USE_VERTEX_ARRAYS
 //#define USE_VBO
 
 #include <SDL.h>
```

**Comment by fabiangreffrath** [comment]
Posting diff is okay as long as we are in a diffuse state of collecting ideas IMHO. 

Entirely indefining `USE_VERTEX_ARRAYS` is probably too drastic at this point. The function actually responsible for drawing lines in this code path can be found here. May you can find a little patch to fix this instead. 

https://github.com/coelckers/prboom-plus/blob/128297cfccaef8a2618bbb4d0f4b670fcfe268a7/prboom2/src/gl_map.c#L238

**Comment by fabiangreffrath** [comment]
Just reporting here that I *cannot* reproduce this issue on a Debian system with 1920x1080 OpenGL rendering.

**Comment by runlow** [comment]
No problem, will keep posting diffs then if I get anything to work the proper way.
Will check gld_DrawMapLines().

As for not being able to reproduce the issue - perhaps it has to do with my particular driver or setup, or some flags when compiling?

Did you build prboom-plus by cloning the repository or did you install the debian package?

I'm using the nvidia driver on Archlinux with Nvidia Geforce GT 730.

**Comment by fabiangreffrath** [comment]
I think it was the Debian package. But it shouldn't make a huge difference, as Debian doesn't pass any fancy flags for compilation.

**Comment by fabiangreffrath** [comment]
Do you build your executable with Legacy GL or GLVND support? I.e. what does the "-- Found OpenGL:" line say when you run cmake?

**Comment by fabiangreffrath** [comment]
> Do you build your executable with Legacy GL or GLVND support?

@runlow ?

**Comment by runlow** [comment]
Sorry for the late response.
Just done a `git pull` on master and ran `cmake . -B ../build` with nothing changed yet.
```
  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:61 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/libOpenGL.so
```
Then ran `cd ../build; make
When I run the newly built executable and press Tab I see no lines.

As "LEGACY" seems to be the default for me I've applied the "GLVND" preference
```diff
diff --git a/prboom2/CMakeLists.txt b/prboom2/CMakeLists.txt
index fbd77b28..696838d9 100644
--- a/prboom2/CMakeLists.txt
+++ b/prboom2/CMakeLists.txt
@@ -60,0 +61 @@ if(BUILD_GL)
+    set(OpenGL_GL_PREFERENCE "GLVND")
```
`rm -fr ../build/*; cmake . -B ../build/`

`-- Found OpenGL: /usr/lib/libOpenGL.so`
nothing other related lines.

`cd ../build; make`
```
/usr/bin/ld: CMakeFiles/glboom-plus.dir/gl_main.c.o: undefined reference to symbol 'glStencilOp'
/usr/bin/ld: /usr/lib/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/glboom-plus.dir/build.make:1915: glboom-plus] Error 1
make[1]: *** [CMakeFiles/Makefile2:241: src/CMakeFiles/glboom-plus.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
My [workaround from before](https://github.com/coelckers/prboom-plus/issues/89#issuecomment-637265322) still seems to work well enough.
Let me know if there's anything else I should test.

**Comment by stephenbourke** [comment]
Hi @runlow ,

I ran into this issue as you have described when compiling on macOS (Big Sur). The build went fine but I later noticed I had omitted installing the dependency sdl2_image. When opening the auto-map I saw the exact problem you are experiencing. After looking though the code (linked below), it seems the auto-map render code path is determined based on whether sdl2_image is installed and hence it wont enter the line rendering path when this library is not installed. 

https://github.com/coelckers/prboom-plus/blob/18e16269a71034ff8aec3a2687d008390b6a3a6d/prboom2/src/am_map.c#L2326

After installing sdl2_image (brew install sdl2_image [Debian: apt install libsdl2-image-dev]) and rebuilding the binary the auto-map renders lines as expected, both in full and overlay mode.

Perhaps you have the same issue and are missing libsdl2-image-dev on your installation? It appears the list of installed dependencies on Debian is as follows:

libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libpcre3-dev libmad0-dev libfluidsynth-dev libdumb1-dev libvorbis-dev libportmidi-dev

https://github.com/coelckers/prboom-plus/blob/18e16269a71034ff8aec3a2687d008390b6a3a6d/.github/workflows/continuous_integration.yml#L69

**Comment by fabiangreffrath** [comment]
Thank you very much @stephenbourke ! This condition is obviously bogus.

**Comment by jackrjli** [comment]
I can't speak for @runlow, but I had this same problem on my laptop and 489c27e2574571faa8381e7e033bc5b3a1a77ca8 fixed it. Checked afterwards and found that I don't have SDL2-image installed on this computer. Nice find @stephenbourke!

**Comment by runlow** [comment]
I do seem to have the sdl2_image package installed.

```
% pacman -Q | grep sdl2_image
sdl2_image 2.0.5-2

% pacman -Ql sdl2_image
[...]
sdl2_image /usr/include/SDL2/SDL_image.h
sdl2_image /usr/lib/
sdl2_image /usr/lib/libSDL2_image-2.0.so.0
[...]
```
 Not sure if I did have it though at the time of reporting this issue.

Recompiled the master branch after 489c27e - the map lines seem to appear fine and I no longer need my workaround!

Big thanks @stephenbourke and @fabiangreffrath

Closing this issue I guess.
