### ISSUE TITLE
Automap markers move incorrectly in 16:9 ratio

### ISSUE THREAD

**Issue by runlow** [coelckers/prboom-plus#90]
**Expected**

Automap markers move with the rest of the automap in follow mode in every direction when the player moves - regardless of the aspect ratio.

**Actual**

The map markers appear to "hover" or "slide" over the map in 16:9 ratio either towards "East" or "West" depending on which direction the player is headed. It resembles the parallax scrolling effect when moving. Especially noticeable on larger maps. It makes the feature almost unusable in 16:9 aspect ratio.

When the aspect ratio is set (or detected) to be 4:3 the markers appear to work correctly.
When only moving "North" or "South" (according to the automap) then the markers appear to move correctly in both aspect ratios.

**How to reproduce it**

1. `glboom-plus -iwad DOOM2.WAD -warp 12 -nomonsters`
2. Set aspect ratio to 16:9
3. Press Tab
4. Press M
5. Move right and left (on the map)
6. Notice the automap mark "hovering" right and left faster than the rest of the map
7. Move up and down (on the map)
8. Notice no "hovering"
9. Set aspect ratio to 4:3
10. Move right and left (on the map)
11. Notice no "hovering"

Please let me know if there's anything I should test or if I'm doing something wrong here.

**Comment by runlow** [comment]
Here are some screenshots.

Setting the first marker "0". Notice its position relative to other things on the map.

![doom02](https://user-images.githubusercontent.com/2176657/83337464-755b8800-a2b3-11ea-80b7-3e6e7883b63a.png)

Now moving "west" - notice that the "0" no longer appears where it's expected to be (expecting it to be in the same position relative to the rest of the map).

![doom03](https://user-images.githubusercontent.com/2176657/83337490-b5bb0600-a2b3-11ea-9e5a-fe75e198ab23.png)

**Comment by runlow** [comment]
Somewhat ugly solution but it fixes the issue for me
(for my particular resolution `1920x1080` and particular aspect ratio `16:9`).
Hopefully this will help in writing a proper fix.

```diff
--- a/prboom2/src/am_map.c
+++ b/prboom2/src/am_map.c
@@ -2112,7 +2112,7 @@ static void AM_drawMarks(void)
       p.y = CYMTOF(p.y) - markpoints[i].h * SCREENHEIGHT / 200 / 2;
       if (am_frame.precise)
       {
-        p.fx = CXMTOF_F(p.fx) - (float)markpoints[i].w * SCREENWIDTH / 320.0f / 2.0f;
+        p.fx = CXMTOF_F(p.fx)*1.33-320 - (float)markpoints[i].w * SCREENWIDTH / 320.0f / 2.0f;
         p.fy = CYMTOF_F(p.fy) - (float)markpoints[i].h * SCREENHEIGHT / 200.0f / 2.0f;
       }
```

**Comment by fabiangreffrath** [comment]
What if you simply add `wide_offsetx` to`p.fx`?

**Comment by runlow** [comment]
Thank you for the hint. Unfortunately doing what you described doesn't fix the issue for me (unless I'm doing something wrong of course).

**Comment by runlow** [comment]
```p.fx = CXMTOF_F(p.fx) - (float)markpoints[i].w * SCREENWIDTH / 320.0f / 2.0f;```

While at it - not sure I understand this line very well. Looks like entryway wrote it 9 years ago.

`p.fx` doesn't seem initialized anywhere prior and yet its "value" is used to calculate ...its own value?

The meaning of 200 and 320 numbers isn't clear to me either. I'm guessing they're a resolution of some sort but not sure of what yet. I see those numbers often in the file so it must be something common.

The rest is relatively self-evident to me.

**Comment by runlow** [comment]
Confirming that this seems to be fixed now.
Thanks @jackrjli !
Closing issue I guess.

**Comment by fabiangreffrath** [comment]
Sorry, guys, but for me the following happens. Start a new game, open the map, type IDCLIP, type M, press right, see how the marker moves relative to the screen.

**Comment by jackrjli** [comment]
Copying my comment from #222 here:

Hmm, I can't reproduce the issue with this patch applied. I know that when using the software renderer the markers jitter around as you move the map, but they remain centered around the same point. (When using OpenGL am_frame.precise is set to true and the markers move more smoothly, and if you use the "icons" thing appearance setting, it uses a different function entirely for drawing the markers.)

However, I did just notice a different issue this created, which is that if you set the aspect ratio setting to 5:4, the positions of the markers get changed compared to all the other aspect ratio settings.

**Comment by fabiangreffrath** [comment]
I am inclined to entirely revert this commit, because when grepping through the code, you'll notice that `VPT_ALIGN_MAX` isn't even a valid value for the alignment flag, but only a marker to count the proper values in `enum patch_translation_e`:

https://github.com/coelckers/prboom-plus/blob/6046b35756b53d747ffc8ff8c4d1f68bc83bd45a/prboom2/src/doomtype.h#L154
https://github.com/coelckers/prboom-plus/blob/6046b35756b53d747ffc8ff8c4d1f68bc83bd45a/prboom2/src/r_main.c#L547

Passing `VPT_ALIGN_MAX` to ` V_DrawPatch()` should be equivalent to passing `0`.

**Comment by runlow** [comment]
I see. Sorry for closing it. Reopening. Everything seems to work ok here after 6046b35 even if I change the aspect ratio - although I only tested it in OPENGL video mode.

**Comment by jackrjli** [comment]
I did some more testing and found that whether the markers shift around depends on the "status bar and menu appearance" setting. Before my commit, when that setting is set to "fit to width," the markers don't shift around, but with other values they do. My commit made it so that if it's set to "Doom format," the markers don't shift around, but when it's "not adjusted," the markers do. If you set it to "fit to width," the game crashes when it tries to display a marker.

I agree with reverting my commit (especially in light of that crash), but hopefully that's a helpful clue toward finding a proper fix.
