### ISSUE TITLE
Is the independent "glboom-plus" binary really necessary?

### ISSUE THREAD

**Issue by chungy** [coelckers/prboom-plus#91]
The non-fork version of prboom-plus on Linux only builds a single binary, "prboom-plus", that can run in software or gl mode from there. When I built this repository, it first surprised me by running slow with just ./prboom-plus, then I noticed the extra binary that does what I really want.

It feels like this is a regression.

**Comment by alexey-lysiuk** [comment]
No, it’s not, see #66.

**Comment by chungy** [comment]
I don't think that issue answers the question. I feel like the original non-fork prboom-plus did it better, a single binary that supports both modes.

**Comment by alexey-lysiuk** [comment]
Currently, GLBoom binary supports both modes while PrBoom is software only.
The linked issue explains why the latter was added. TLDR: people complained.

The original version did it wrong because the result depended on chosen build system. And it had plenty of those.
Could you please explain how you built the original?

**Comment by chungy** [comment]
>  Could you please explain how you built the original?

`./configure && make` -- I don't think that's really surprising.

It seems strangest of all to decide on "glboom-plus" as being a default when the name of the upstream builds only "prboom-plus"

**Comment by alexey-lysiuk** [comment]
Visual Studio solution had projects for two game binaries. This is how it was built on Windows.

**Comment by chungy** [comment]
I've never built nor ran on it Windows. At least on Linux, there is only a singular prboom-plus binary that did the job that both of these do.

**Comment by fabiangreffrath** [comment]
I did this in the Debian package: 
https://salsa.debian.org/games-team/prboom-plus/-/blob/master/debian/rules#L12

**Comment by chungy** [comment]
Thanks @fabiangreffrath -- seems like the best solution if this issue is ignored.

**Comment by sinisterseed** [comment]
To further expand on this, it also needs to be noted that there are some differences between the executables as well, so yes, building both is not pointless at all. For instance, GlBoom has a textured automap, which, to my knowledge, is not present in the PrBoom executable, and the PrBoom executable also doesn't support changing the renderers, only 8-bit is available there (at least on Windows, on Linux/macOS I don't know).

And yes, people also complained, including yours truly.
