### ISSUE TITLE
Wrong aspect ratio at 320x200

### ISSUE THREAD

**Issue by tpoppins** [coelckers/prboom-plus#94]
![aspect-prb](https://user-images.githubusercontent.com/10210507/84113956-874ad280-a9f9-11ea-8b19-bc79e92af1ed.png)
prboom-plus, own build from latest src, `screen_resolution         "320x200"` in config

![aspect-crispy](https://user-images.githubusercontent.com/10210507/84113965-8b76f000-a9f9-11ea-8023-5090fa8fc14e.png)
Crispy, own build from latest source, hires off

The pictures are cropped roughly to the LCD monitor's borders. Sorry for the quality, had to take the pictures with my phone to demonstrate the difference in the pillarboxing, the games' internal screenshot functions would be useless for that. 

The prboom-plus screen is much too wide at 320x200 (or multiples thereof like 640x400). Using 320x240 in prboom-plus' config fixes the aspect ratio to match that of Crispy (and Choco) but that res is too high for my taste. ;)

Nvidia K2000 video card on AOC 2367 monitor (1920x1080 native res). Win 7 x64 Pro SP1. The Windows desktop and both games run at 1280x720@60 Hz. Both games use the same SDL2 backend so there's something wrong with how prboom-plus treats 320x200.

**Comment by tpoppins** [comment]
Also note that the 320x200 screen is essentially widescreen, with a noticeably wider FOV. 

Unless it's a bug nested inside another bug, the engine doesn't seem to realize that it's doing widescreen, as all three values of "Status Bar and Menu Appearance"  under Options/General produce the same stretched status bar. The aspect ratio of the rest of the screen can be corrected by setting the "Aspect Ratio" option to 16:10, but really, widescreen rendering should not happen unless the user specifically requests it (which is currently not an option, AFAIK).

**Comment by fabiangreffrath** [comment]
The main difference is that in Chocolate forks in 320x200 mode the game is rendered to a 320x200 canvas which is then vertically stretched to 320x240 dimensions. This doesn't seem to happen in PrBoom+, thus the picture appears wider than in the other ports.

**Comment by fabiangreffrath** [comment]
@tpoppins I somehow cannot reproduce the first screenshot that you posted, i.e. the one showing PrBoom+ rendering the game as widescreen with 320x200 resolution. Please make sure to have the "Aspect Ratio" option set to "Auto". It seems that you have set it to "16:10" in your screenshot.

When set to "Auto", the screen should look exactly as on the lower screenshot, but vertically squashed. Could you please confirm? I would like to be 100% sure before merging https://github.com/coelckers/prboom-plus/pull/162.

**Comment by tpoppins** [comment]
The first screenshot was taken with the AR set to "Auto". My latest build (from September) exhibits the same issue.

**Comment by tpoppins** [comment]
I can confirm that the changes in #162 solve the issue for me with 320x200 and 640x400.
