### ISSUE TITLE
Garbage lines at the top of weapon sprites

### ISSUE THREAD

**Issue by tpoppins** [coelckers/prboom-plus#95]
A long-standing issue that I once brought to  entryway's attention who shrugged it off as "a Prboom's bug". Affects the software renderer in resolutions other than 320x200 and 640x400. Most evident when the plasma gun bobs up and down while you walk.

Own ticket on the original tracker
https://sourceforge.net/p/prboom-plus/bugs/136/

Blondie's ticket ibid
https://sourceforge.net/p/prboom-plus/bugs/160/

Discussed several times on DW:

[Gray bar on top of the chaingun?](https://www.doomworld.com/forum/topic/69800-gray-bar-on-top-of-the-chaingun/)

In the original Prboom-plus thread: 
[example 1](https://www.doomworld.com/forum/topic/31039-prboom-plus-ver-2514/?do=findComment&comment=1100009)
[example 2](https://www.doomworld.com/forum/topic/31039-prboom-plus-ver-2514/?do=findComment&comment=1853730)
[RjY's explanation](https://www.doomworld.com/forum/topic/31039-prboom-plus-ver-2514/?do=findComment&comment=1855810)

Example pics:

![doom00](https://user-images.githubusercontent.com/10210507/84122828-08f52d00-aa07-11ea-847c-dcdd7230d05f.png)
![doom01](https://user-images.githubusercontent.com/10210507/84122990-3cd05280-aa07-11ea-82f2-b0066e4628d2.png)

As a workaround I'm using a custom prboom-plus.wad, with three edited sprites of the plasma gun and the chaingun (the center of the bottom line of each painted black): [prboom-plus.zip](https://github.com/coelckers/prboom-plus/files/4750808/prboom-plus.zip)

**Comment by fabiangreffrath** [comment]
This subtle change seems to fix it for me:

```
--- a/prboom2/src/r_things.c
+++ b/prboom2/src/r_things.c
@@ -1000,7 +1000,7 @@ static void R_DrawPSprite (pspdef_t *psp)
   vis = &avis;
   vis->mobjflags = MF_PLAYERSPRITE;
    // killough 12/98: fix psprite positioning problem
-  vis->texturemid = (BASEYCENTER<<FRACBITS) /* +  FRACUNIT/2 */ -
+  vis->texturemid = (BASEYCENTER<<FRACBITS) + FRACUNIT/4 -
                     (psp_sy-topoffset);
 
   // Move the weapon down for 1280x1024.
```

**Comment by fabiangreffrath** [comment]
@tpoppins Do you have a chance to check if the change I proposed in https://github.com/coelckers/prboom-plus/pull/157 fixes the issue for you?

**Comment by tpoppins** [comment]
This is it!
Thank you, Fabian.

**Comment by fabiangreffrath** [comment]
Don't close, please, it hasn't been applied yet.

**Comment by fabiangreffrath** [comment]
What resolution did you test this patch with?

**Comment by tpoppins** [comment]
Yes, I closed it too soon.

Seemed fine @320x240; still with a bright white line at the top of the plasma rifle @640x480. The chaingun looks correct, though.

**Comment by fabiangreffrath** [comment]
Okay, seems this is due to the weapon sprite being scaled by some odd or non-integer factors. For e.g. 800x600 the sprite needs to get scaled by factor 3, so the step in source pixels for each screen pixel is `FRACUNIT/3`. With `FRACUNIT = 1<<16`, this value won't result in FRACUNIT again when multiplied with 3.

Whatever, could you please check the following patch?

```
--- a/prboom2/src/r_things.c
+++ b/prboom2/src/r_things.c
@@ -564,6 +564,7 @@ static void R_DrawVisSprite(vissprite_t *vis)
   // check to see if weapon is a vissprite
   if(vis->mobjflags & MF_PLAYERSPRITE)
   {
+    while (dcvars.iscale * vis->scale < FRACUNIT) dcvars.iscale++;
     dcvars.texturemid += FixedMul(((centery - viewheight/2)<<FRACBITS), dcvars.iscale);
     sprtopscreen += (viewheight/2 - centery)<<FRACBITS;
   }
```

**Comment by tpoppins** [comment]
Looks clean at all resolutions I tried: 640x480, 720x480, 800x600, 1024x768, 1280x720, 1280x768, 1280x960, 1280x1024, 1600x900 and 1980x1080.

**Comment by fabiangreffrath** [comment]
Cool, so this seems to be it. Now I need to get rid of this naive iterative approach and implement something that's faster. This, and I still don't have a clue about the distorted lower line of the SSG flash sprite when sloped patch edges are enabled...

**Comment by fabiangreffrath** [comment]
This is currently the most clever thing that I can come up with:
```
diff --git a/prboom2/src/r_main.c b/prboom2/src/r_main.c
index 13568805..734433c0 100644
--- a/prboom2/src/r_main.c
+++ b/prboom2/src/r_main.c
@@ -806,6 +806,9 @@ void R_ExecuteSetViewSize (void)
   pspritexscale = (wide_centerx << FRACBITS) / 160;
   pspriteyscale = (((cheight*viewwidth)/SCREENWIDTH) << FRACBITS) / 200;
   pspriteiscale = FixedDiv (FRACUNIT, pspritexscale);
+  pspriteiyscale = FixedDiv (FRACUNIT, pspriteyscale);
+  while (FixedMul(pspriteiyscale, pspriteyscale) < FRACUNIT)
+    pspriteiyscale++;
 
   //e6y: added for GL
   pspritexscale_f = (float)wide_centerx/160.0f;
diff --git a/prboom2/src/r_things.c b/prboom2/src/r_things.c
index 5582c9d2..6c769bbf 100644
--- a/prboom2/src/r_things.c
+++ b/prboom2/src/r_things.c
@@ -61,6 +61,7 @@ fixed_t pspriteiscale;
 // proff 11/06/98: Added for high-res
 fixed_t pspritexscale;
 fixed_t pspriteyscale;
+fixed_t pspriteiyscale;
 
 static const lighttable_t **spritelights;        // killough 1/25/98 made static
 
@@ -564,6 +565,7 @@ static void R_DrawVisSprite(vissprite_t *vis)
   // check to see if weapon is a vissprite
   if(vis->mobjflags & MF_PLAYERSPRITE)
   {
+    dcvars.iscale = pspriteiyscale;
     dcvars.texturemid += FixedMul(((centery - viewheight/2)<<FRACBITS), dcvars.iscale);
     sprtopscreen += (viewheight/2 - centery)<<FRACBITS;
   }
diff --git a/prboom2/src/r_things.h b/prboom2/src/r_things.h
index 51ccc021..2267cb83 100644
--- a/prboom2/src/r_things.h
+++ b/prboom2/src/r_things.h
@@ -60,6 +60,7 @@ extern fixed_t pspriteiscale;
 /* proff 11/06/98: Added for high-res */
 extern fixed_t pspritexscale;
 extern fixed_t pspriteyscale;
+extern fixed_t pspriteiyscale;
 //e6y: added for GL
 extern float pspritexscale_f;
 extern float pspriteyscale_f;
```

**Comment by fabiangreffrath** [comment]
@tpoppins May I ask you to check if the patch from my previous post leads to similarly satisfying results?

**Comment by fabiangreffrath** [comment]
Also, the garbage line at the bottom of the SSG flash with "Drawing of Patch Edges = Sloped" is because of this code:

https://github.com/coelckers/prboom-plus/blob/8340ffc505b9d7aa3406a2be144474d40e849b3d/prboom2/src/r_drawcolumn.inl#L184

This divides some shift value by the value of `dcvars->iscale`, which is the reciprocal of the weapon sprite scaling factor. So, for our example above with 800x600 resolution, the weapon sprite is scaled by factor 3 relative to the original resolution which results in 1/3 (= 0.333333...) for the `iscale` value. This would be impossible to properly represent even as a floating point number, let alone as a binary representation, let alone in values of FRACUNIT. 

Plus, we now increase this value so that `scale * iscale >= FRACUNIT` or trivially `x * 1/x >= 1`. This doesn't really help with the calculation of the shift value, so I'll probably have to reduce its precision a bit. We'll see...

**Comment by tpoppins** [comment]
> 
> 
> @tpoppins May I ask you to check if the patch from my previous post leads to similarly satisfying results?

Done. I reverted the iterative patch from Jan 14 and used the diff from your PR. No artifacts observed. Same resolutions as before plus a few oddball ones, like 720x576, 1152x864 and 1366x768 (this old Quadra supports a lot of them). 

re: SSG+Sloped Edges: I fail to see those lines. I don't see them with earlier own builds either, e.g. the Jan 12 one, even after reverting own fix to its prboom-plus.wad.

**Comment by fabiangreffrath** [comment]
So you confirm this is ready to mere?

**Comment by tpoppins** [comment]
Affirmative.

**Comment by fabiangreffrath** [comment]
Thank you for all the checks you performed, highly appreciated! 👍
