### ISSUE TITLE
Umapinfo intermission screens showing wrong episode map in Doom 1

### ISSUE THREAD

**Issue by UnluckySpade7** [coelckers/prboom-plus#98]
I've been experimenting with a personal wad that allows me to play all the Doom 1 episodes in a continious playthrough but there's a minor issue exclusive to prboom plus that gzdoom doesn't have related to the map screens.

When I IDCLEV to a map with Umapinfo enabled and finish it the intermission map of the previous episode displays.
![umapinfobug](https://user-images.githubusercontent.com/39349626/84772852-6f63e780-afd3-11ea-9d2a-ba4395463a32.png)
Then when i go to start the next map the regular map shows up but with leftovers from the first.
![umapinfobug2](https://user-images.githubusercontent.com/39349626/84772975-a1754980-afd3-11ea-9012-31948e3c8dad.png)

This also applies to going from episode 2 to episode 3 where the map doesn't get cleared of blood spots from the previous map and the "you are here" arrow points to the wrong part of the map.
![umapinfobug3](https://user-images.githubusercontent.com/39349626/84773265-1183cf80-afd4-11ea-9578-f2ee0f4556a7.png)

Here is the wad I've been using to test this: 
[umaptest.zip](https://github.com/coelckers/prboom-plus/files/4786539/umaptest.zip)

**Comment by fabiangreffrath** [comment]
Does it work if you move the `wminfo.nextep = wminfo.epsd = gameepisode -1;` and `wminfo.last = gamemap -1;` lines from L1615 up to L1569 right before the `if (gamemapinfo)` block?

https://github.com/coelckers/prboom-plus/blob/HEAD/prboom2/src/g_game.c#L1615

**Comment by UnluckySpade7** [comment]
I don't know how I could test that since I've been using pre-made builds from the forum and don't know how to build it myself

**Comment by fabiangreffrath** [comment]
Sorry, I was assuming everybody is a coder. 😁 

The first chunk fixes the intermissions screens during episode switch for me. The second chunk fixes the crash when switching to episode 4. It would be nice if somebody else could confirm these fixes before I apply them.

```
diff --git a/prboom2/src/g_game.c b/prboom2/src/g_game.c
index 5f5e50d2..c809d891 100644
--- a/prboom2/src/g_game.c
+++ b/prboom2/src/g_game.c
@@ -1564,6 +1564,9 @@ void G_DoCompleted (void)
   if (automapmode & am_active)
     AM_Stop();

+  wminfo.nextep = wminfo.epsd = gameepisode -1;
+  wminfo.last = gamemap -1;
+
   wminfo.lastmapinfo = gamemapinfo;
   wminfo.nextmapinfo = NULL;
   if (gamemapinfo)
@@ -1612,8 +1615,6 @@ void G_DoCompleted (void)
   }

   wminfo.didsecret = players[consoleplayer].didsecret;
-  wminfo.nextep = wminfo.epsd = gameepisode -1;
-  wminfo.last = gamemap -1;

   // wminfo.next is 0 biased, unlike gamemap
   if (gamemode == commercial)
diff --git a/prboom2/src/wi_stuff.c b/prboom2/src/wi_stuff.c
index 182124ae..bc420cce 100644
--- a/prboom2/src/wi_stuff.c
+++ b/prboom2/src/wi_stuff.c
@@ -418,7 +418,7 @@ static void WI_slamBackground(void)

   if (state != StatCount && enterpic) strcpy(name, enterpic);
   else if (exitpic) strcpy(name, exitpic);
-  else if (gamemode == commercial || (gamemode == retail && wbs->epsd == 3))
+  else if (gamemode == commercial || (gamemode == retail && (wbs->epsd == 3 || (state != StatCount && wbs->nextep == 3))))
     strcpy(name, "INTERPIC");
   else
     sprintf(name, "WIMAP%d", state == StatCount? wbs->epsd : wbs->nextep);

```

**Comment by fabiangreffrath** [comment]
> The first chunk fixes the intermissions screens during episode switch for me. 

Not entirely, though. The animations are still messed up.
